### ISSUE TITLE
When using pydantic mypy plugin, mypy 1.11.0 uses wrong return type for pydantic.v1.BaseModel.construct()

### ISSUE THREAD

**Issue by LHCGreg** [pydantic/pydantic#10000]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using mypy 1.11.0 and mypy.ini has `plugins = pydantic.mypy,pydantic.v1.mypy`, mypy sees the return type of `pydantic.v1.BaseModel.construct()` as `_PydanticBaseModel` instead of the model type being constructed, resulting in type errors when running mypy. If I switch to mypy 1.10.1, the error goes away. If I remove the use of the pydantic mypy plugins, the error goes away. I expect `MyModel.construct()` to have the type `MyModel`, not `_PydanticBaseModel`.

### Example Code

```Python
from pydantic.v1 import BaseModel as v1BaseModel, StrictStr as v1StrictStr

from pydantic import BaseModel, StrictStr


class MyModelV1(v1BaseModel):
    text_field: v1StrictStr


class MyModelV2(BaseModel):
    text_field: StrictStr


def main() -> None:
    # With mypy 1.11.0 and plugins = pydantic.mypy,pydantic.v1.mypy, this errors:
    #
    # Incompatible types in assignment (expression has type "_PydanticBaseModel", variable has type "MyModelV1")  [assignment]
    #
    # With mypy 1.10.1 and plugins = pydantic.mypy,pydantic.v1.mypy, it does not error.
    # With mypy 1.11.0 and no plugins, it does not error.
    v1_model: MyModelV1 = MyModelV1.construct(text_field="hello")

    # This line is fine
    v2_model: MyModelV2 = MyModelV2.construct(text_field="hello")


main()

##########################
# mypy.ini
[mypy]
files = mypy_cls_generic_repro/
plugins = pydantic.mypy,pydantic.v1.mypy
strict_equality = True
disallow_untyped_defs = True
disallow_untyped_calls = True
disallow_untyped_decorators = True
no_implicit_optional = True
strict_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_no_return = True
warn_return_any = True
warn_unreachable = True
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\GNAJDA\AppData\Local\pypoetry\Cache\virtualenvs\mypy-cls-generic-repro-WKFX0hC2-py3.12\Lib\site-packages\pydantic
               python version: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
                     platform: Windows-11-10.0.22631-SP0
             related packages: mypy-1.11.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by dmontagu** [comment]
Does this only affect pydantic v1 models? In particular, do we not get a similar error for `pydantic.BaseModel.model_construct`?

**Comment by dmontagu** [comment]
If this is only affecting v1 usage, I'll just note that it may be possible to address this through maintenance on the `pydantic.v1.mypy` module to make it more like the `pydantic.mypy` module. In particular, I can see that `pydantic.v1.mypy.PydanticModelTransformer.add_construct_method` is quite different from `pydantic.mypy.PydanticModelTransformer.add_model_construct_method`, which I think is probably a reflection of the fact that the mypy APIs have slowly evolved/changed, but we basically haven't touched the v1 plugin since the v2 release.

I am generally not very keen to continue maintaining the pydantic v1 mypy plugin for a variety of reasons, not least of which being that `@dataclass_transform` now provides much of the value that the original plugin did and does not require ongoing maintenance to support deprecated versions of the library. But if someone wants to put in the effort to make it compatible with mypy 1.11 I could review a PR.

**Comment by sydney-runkle** [comment]
Going to close this as not planned, given our version policy. See [these docs](https://docs.pydantic.dev/latest/version-policy/#pydantic-v1) for more details.

I agree with @dmontagu - happy to review PRs here, but not worth our investment at the moment.

**Comment by LHCGreg** [comment]
@sydney-runkle that version policy ("critical bug fixes and security vulnerabilities will be fixed in V1 for one year after the release of V2 (June 30, 2024)") applies to the v1 support inside the v2 package as well as the 1.x line of packages? I guess that makes sense, I'm sure it's the same code underneath.
