### ISSUE TITLE
np.int64 and np.uint64 casting to int creates an overflow with large numbers

### ISSUE THREAD

**Issue by Allaway11** [pydantic/pydantic#10016]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using a BaseModel with field type of `int`. If you input a large numpy integer, the value held in that field differs from the input value. This is perhaps an overflow issue after casting to a type that appears to be 48 bit integer space (observed by looking at the hex)? This issue doesnt persist if you cast the numpy integer to python int, so this could be a numpy bug 🐛 also 🤷 
https://www.reddit.com/r/Python/comments/urwoto/whats_up_with_uint64_in_numpy/

### Example Code

```Python
import numpy as np
from pydantic import BaseModel


class Number(BaseModel):
    value: int


integer = 8889891283923431349
np_integer = np.int64(integer)
number = Number(value=integer)
np_number = Number(value=np_integer)

assert integer == np_integer
assert integer == number.value
assert np_integer == np_number.value
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/georgeallaway/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Jun  4 2024, 17:12:23) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.3.1-arm64-arm-64bit
             related packages: typing_extensions-4.8.0
```

**Comment by MattOates** [comment]
So this appears to be an issue with Pydantic "int" forcing numpy <-> cpython integer type interaction described here https://www.reddit.com/r/Python/comments/urwoto/whats_up_with_uint64_in_numpy/ which is to say numpy when dealing with arithmetic operations between the cpython integer object and a numpy 64bit integer it "promotes" to a numpy 64bit float which obviously has less integer space to work with. Ultimately this is hitting a long standing numpy bug. I suspect it could be avoided by first coercing the numpy type to a python integer explicitly then storing this.

```
>>> import numpy
>>> numpy.uint64(8889891283923431349)
8889891283923431349
>>> numpy.uint64(numpy.float64(numpy.uint64(8889891283923431349)))
8889891283923431424
```

**Comment by sydney-runkle** [comment]
@MattOates, great find.

Going to close this as resolved for now - seems like there's a reasonable workaround, and it's not something that can be fixed on our end.

**Comment by MattOates** [comment]
@sydney-runkle there is a Pydantic bug here, I was more trying to highlight more detail on what it might be. I was showing what's being invoked within Pydantic, but its done in a way thats very unobvious this is what will happen. Somewhere Pydantic is doing an arithmetic operation between a numpy type and int(0) cpython int if you pass in the numpy integer (assumedly). Almost anyone would expect this to be a casting and assignment operation with int() not arithmetic, which as I demonstrated would work fine. I suspect this will be catching loads of people out they just wont notice the bug, because they can't really see the numpy bad case as its within the Pydantic internals.

**Comment by sydney-runkle** [comment]
Gotcha. Makes sense, thanks for following up!
