### ISSUE TITLE
How to share config for many models?

### ISSUE THREAD

**Issue by cdeil** [pydantic/pydantic#1019]
First of all, thank you so much for developing this wonderful package, and writing such great documentation. It's awesome!

@bultako and I are currently exploring options for our config settings handling, and we're considering switching from a homegrown JSON schema solution to pydantic (see evaluation of options [here](https://github.com/cdeil/gammapy-config)).

Is there a way to share config across many models?
We have ~ 10 models, and would like all of them to have the same settings.
Below is an example with 2 models (LogModel and AnalysisModel) and config MyConfig.

Currently we do this by defining the config once, and then assigning the class to each model.
This seems to work fine.
Is this the best way to do it?
Or is there a better way?
Maybe subclassing?
What is your recommendation?

Or maybe you could offer this as an option to `BaseModel` to set the config?
```
class LogModel(BaseModel(config=MyConfig))
```
Or via a decorator, similar to how it works for dataclasses?

cc @bultako

```py
from pydantic import BaseModel

class MyConfig:
    validate_assignment = True
    extra = "forbid"

class LogModel(BaseModel):
    level = "info"
    filename: str = None

    Config = MyConfig

class AnalysisModel(BaseModel):
    log = LogModel()
    outdir = "."

    Config = MyConfig
```

**Comment by samuelcolvin** [comment]
assignment as you've done here works fine.

I would say the best option is probably subclassing, something like

```py
class MyBaseModel(BaseModel):
    class Config:
        validate_assignment = True
        extra = 'forbid'

class LogModel(MyBaseModel):
    level = 'info'
    filename: str = None
```

pydantic does some magic:

https://github.com/samuelcolvin/pydantic/blob/56ba84a195a40c766fa49bbeffac4b518ee08edb/pydantic/main.py#L94-L101

So that inheriting from `MyBaseModel` in `LogModel` will mean `LogModel.Config` inherits from `MyBaseModel.Config` which wouldn't be the case normally.

We should probably document this. PR welcome to add this to the config page in docs.

**Comment by dmontagu** [comment]
Closing for now, but I've added a note to the v2 documentation project to make sure we document config inheritance properly.
