### ISSUE TITLE
Set default field value via Generics

### ISSUE THREAD

**Issue by bram-tv** [pydantic/pydantic#10215]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

This is similar to #7884 but that use-case looks a bit more complex (especially the explanation) 

Our use case is using this in combination with [Discriminated Unions with str discriminators](https://docs.pydantic.dev/latest/concepts/unions/#discriminated-unions-with-str-discriminators).

But explaining it is easier with code so let's just do that.

In essence what we have (without generic, and which works) is something similar to:
```python
from typing import Literal, Union

from pydantic import BaseModel, Field


class Pet(BaseModel):
    pet_type: str
    name: str
    age: int


class Cat(Pet):
    pet_type: Literal["cat"] = "cat"
    meows: int


class Dog(Pet):
    pet_type: Literal["dog"] = "dog"
    barks: float


class Model(BaseModel):
    pet: Union[Cat, Dog] = Field(..., discriminator="pet_type")


print(Model(pet=Cat(meows=3, name="aa", age=2)).model_dump_json())
print(Model(pet=Dog(barks=4, name="bb", age=3)).model_dump_json())
```

One of the issue with the above is that the `pet_type: str` in `Pet` is not entirely correct. When using type checkers (for example pyright) it will flag the overriding of `pet_type` in `Cat` and `Dog` as an incompatible override. <details>
    <summary>(pyright output)</summary>

```
....py:13:5 - error: "pet_type" overrides symbol of same name in class "Pet"
  Variable is mutable so its type is invariant
    Override type "Literal['cat']" is not the same as base type "str" (reportIncompatibleVariableOverride)
....py:18:5 - error: "pet_type" overrides symbol of same name in class "Pet"
  Variable is mutable so its type is invariant
    Override type "Literal['dog']" is not the same as base type "str" (reportIncompatibleVariableOverride)
```
</details>

There are some possible solutions:
- Remove the `pet_type: str` from `Pet` (but then the `Pet` model is less complete; after all every `Pet` should have a `pet_type`)
- Silence/Ignore the type checker error
- (others?)
- Make `Pet` a Generic model

Ideally the above would be changed into something like:
```python
from typing import Generic, Literal, TypeVar, Union

from pydantic import BaseModel, Field

_T = TypeVar("_T", bound=str)


class Pet(BaseModel, Generic[_T]):
    pet_type: Literal[_T] = _T
    name: str
    age: int


class Cat(Pet["cat"]):  # or class Cat(Pet[Literal["cat"]]):
    meows: int


class Dog(Pet["dog"]): # or class Dog(Pet[Literal["dog"]]):
    barks: float


class Model(BaseModel):
    pet: Union[Cat, Dog] = Field(..., discriminator="pet_type")


print(Model(pet=Cat(meows=3, name="aa", age=2)).model_dump_json())
print(Model(pet=Dog(barks=4, name="bb", age=3)).model_dump_json())
```

but that currently fails with:
```
Traceback (most recent call last):
  File "....py", line 26, in <module>
    print(Model(pet=Cat(meows=3, name="aa", age=2)).model_dump_json())
  File "..../lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
pet
  Input tag '~_T' found using 'pet_type' does not match any of the expected tags: 'cat', 'dog' [type=union_tag_invalid, input_value=Cat(pet_type=~_T, name='aa', age=2, meows=3), input_type=Cat]
    For further information visit https://errors.pydantic.dev/2.8/v/union_tag_invalid
```

(In our code the `pet_type` field is a bit more complex because we also add Annotations on it, Annotations that we now need to repeat in all of the subclasses. If the generic would work then our `pet_type` would eventually look like: `pet_type: Annotated[Literal[_T], Annotation1, Annotation2] = _T`)

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [X] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@bram-tv,

Thanks for your request. I think this is definitely reasonable - I'm not sure exactly how complex implementation will be during the core schema build, but this is something I think we should support (and relates to many other currently open `generics` issues).

I anticipate doing a lot of work on core schema generation during the coming months, and would be happy to take a look at some of the generics logic during that process. Anyone interested in contributing should also feel free to take a stab at this!

**Comment by Viicos** [comment]
I think this already works, just that your code is invalid. Could you try with the following and report if it works as expected?

```python
from typing import Generic, Literal, TypeVar, Union

from pydantic import BaseModel, Field

_T = TypeVar("_T", bound=str)


class Pet(BaseModel, Generic[_T]):
    pet_type: _T
    name: str
    age: int


class Cat(Pet[Literal["cat"]]):
    meows: int


class Dog(Pet[Literal["dog"]]):
    barks: float
```

The default value `= _T` doesn't work, but I'm unsure this is a pattern we wan't to support. Currently it isn't accepted by type checkers as well.

**Comment by Viicos** [comment]
> The default value is the entire point.

The issue is that such a behavior isn't compatible with how Python typing works.

When you define a class a being generic:

```python
from typing import Generic, TypeVar

T = TypeVar("T")

class Model(Generic[T]):
    attr: T
```

`T` refers to a type variable, i.e. a type that can vary.

```python
Cat = Model[Literal["cat"]]

# roughly equivalent to:

class Cat:
    attr: Literal["cat"]
```

In this case, `Literal["cat"]` _is a type_ (we could have used `int` in the example as well) (or more precisely – iirc – it is a [type expression](https://typing.readthedocs.io/en/latest/spec/annotations.html#type-expression)).

Now regarding the pattern `attr: T = <default>`, `<default>` refers to a value, and `Literal["cat"]` can't be used in such a context.

This would mean the following:

```python
T = TypeVar("T")

class Model(Generic[T]):
    attr: T = T

Cat = Model[Literal["cat"]]

# roughly equivalent to:

class Cat:
    attr: Literal["cat"] = Literal["cat"]  # invalid: `Literal["cat"]` has no meaning as a value.
```

The example with `Literal["cat"]` is a bit special: it could be that `"cat"` is used for the default value: should be `attr: Literal["cat"] = "cat"` (and this what you are requesting). However, it only could make sense with this example. Consider what should happen if we used `Literal["cat", "other"]`:

```python
Cat = Model[Literal["cat", "other"]]

# roughly equivalent to:

class Cat:
    attr: Literal["cat", "other"] = ???
```

---

I can see you've tried circumventing this behavior by doing the following:

```
class Pet(BaseModel, Generic[_T]):
    pet_type: Literal[_T] = _T
    name: str
    age: int


class Cat(Pet["cat"]):
    meows: int
```

But this is not how the Python type system works, as `"cat"` (what's being used to parametrize `_T`) does not refer to a type, but a value [^1]

I can understand the frustration of having to define the default value for each model, but it is in fact required to have things working correctly: you used an instance of `Cat` when instantiating `Model`, but you will get a validation error if you do the following:

`Model.model_validate({"pet": {"name": "a", "age": 2, "meows": 1}}).model_dump()`

[^1]: Actually, type checkers will treat `"cat"` as being a forward reference to a type named `cat`.

**Comment by Viicos** [comment]
On a side note:

> But again whatever syntax is used is irrelevant as long as there is a syntax that can be used. [...] it does not have meaning today doesn't mean it can't have meaning tomorrow. [...] But again that brings us back to what syntax should/could be used and the exact syntax that is needed is irrelevant.

I have to disagree on this point. Pydantic uses information provided by type hints at runtime. This has the benefit of having type checker/IDE support (thanks to some constructs such as [`dataclass_transform()`](https://typing.readthedocs.io/en/latest/spec/dataclasses.html#the-dataclass-transform-decorator)) on top of runtime validation. As such, we try to stick as much as possible to the Python typing specification, and avoid using custom constructs that are not understood by type checkers.

On another note:

> One **random** idea - which I just thought of - could be to add a `Discriminator` type to pydantic which can be used for typing the generic. I.e. that the example becomes something like: `Pet[pydantic.Discriminator[Literal["Cat"]]]`. But again whatever syntax is used is irrelevant as long as there is a syntax that can be used.

Is a syntax that can _almost_ be made compatible with the typing semantics. `Discriminator` already exists in Pydantic so I'm going to tweak the example a bit:

```python
from typing import TYPE_CHECKING, Annotated, Generic, Literal, TypeVar, get_args, get_origin

from pydantic import BaseModel, Field

T = TypeVar("T")

if TYPE_CHECKING:
    DiscriminatorWithDefault = Annotated[T, ...]
else:
    class DiscriminatorWithDefault:
        def __class_getitem__(cls, arg):
            if isinstance(arg, tuple):
                raise RuntimeError("'DiscriminatorWithDefault' can only be parametrized with a single element.")
            if get_origin(arg) is not Literal:
                raise RuntimeError("'DiscriminatorWithDefault' can only be parametrized with a Literal.")

            args = get_args(arg)
            if len(args) > 1 or len(args) == 0:  # second check is to satisfy the type checker
                raise RuntimeError("'DiscriminatorWithDefault' expects a single literal value.")

            default_value = args[0]

            return Annotated[arg, Field(default=default_value)]

_T = TypeVar("_T", bound=str)

class Pet(BaseModel, Generic[_T]):
    pet_type: _T
    name: str
    age: int


class Cat(Pet[DiscriminatorWithDefault[Literal["cat"]]]):
    meows: int
```

I said _almost_ because type checkers still think `pet_type` is required, i.e. `Cat(name="", age=1, meows=1)` is a type error, but works at runtime. You may try to add `= ...` to `pet_type: _T` to trick the type checkers.

For this reason and because I consider this as an uncommon pattern, I don't think we will add such a functionality built in Pydantic. The workaround can be shipped in projects directly. We could reconsider if we get similar feature requests in the future.

**Comment by bram-tv** [comment]
> Altering the example a bit futher and using Field in the Annotation I think we would rather use something like:
>
> ```py
> from typing import Annotated, Generic, Literal, TypeVar, Union
> 
> from pydantic import BaseModel, Field
> 
> _T = TypeVar("_T")
> 
> class Pet(BaseModel, Generic[_T]):
>     pet_type: _T = ...  # type: ignore
>     name: str
>     age: int
> 
> 
> class Cat(Pet[Annotated[Literal["cat"], Field(default="cat")]]):
>     meows: int
> ...
> ```
> ...

A small update on this: the syntax above:
- worked on pydantic v2.11.10
- worked on pydantic v2.12.0 - v2.12.5 but with a warning (`UnsupportedFieldAttributeWarning: The 'default' attribute with value 'cat' was provided to the Field() function, ...`)
- stopped working in pydantic v2.13.0

**Comment by Viicos** [comment]
This may be unexpected, I'll investigate.

**Comment by Viicos** [comment]
I took a deeper look:

In Pydantic 2.11, we had the following which was a bit inconsistent:

```python
class Model(BaseModel):
    a: Annotated[int, Field(default=1)] = 2
    b: Annotated[int, Field(default=1)] = ...

Model.model_fields
# {
#    'a': FieldInfo(annotation=int, required=False, default=2),
#    'b': FieldInfo(annotation=int, required=False, default=1)
# }
```

For `a`, the priority is given to the assignment value, but for `b` the `...` assignment (which means it is required) is discarded.

In >=2.12, the assignment always take priority.

I'm not sure I want to change anything here. Using the ellipsis is a remnant of Pydantic V1, that [we discourage using](https://pydantic.dev/docs/validation/latest/concepts/fields/). As a workaround, an `if TYPE_CHECKING:` block can be used:

```python
class Pet(BaseModel, Generic[_T]):
    if TYPE_CHECKING:
        pet_type: _T = ...  # type: ignore
    else:
        pet_type: _T
```
