### ISSUE TITLE
Bug: `TypeError: cannot pickle 'staticmethod' object` with a `Field.default`

### ISSUE THREAD

**Issue by jamesbraza** [pydantic/pydantic#10551]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

For some reason, I can't use `staticmethod` with the `default` argument for a `Field`

### Example Code

```Python
from collections.abc import Callable

from pydantic import BaseModel, Field


class SomeModel(BaseModel):
    @staticmethod
    def default_int_factory() -> int: ...

    # This is fine
    # int_factory: Callable[[], int] = default_int_factory
    # This blows up: TypeError: cannot pickle 'staticmethod' object
    int_factory: Callable[[], int] = Field(default=default_int_factory)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /path/to/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.5 (main, Aug 27 2024, 12:00:37) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.5-arm64-arm-64bit
             related packages: fastapi-0.115.0 mypy-1.11.2 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
Interesting things are happening here. `staticmethod` is a descriptor. When it is referenced within the class definition (no matter if it wrapped in the `Field` call or not), the class doesn't exist yet and so:

```python
class SomeModel(BaseModel):
    @staticmethod
    def default_int_factory() -> int: ...

    int_factory_1: Callable[[], int] = default_int_factory
    int_factory_2: Callable[[], int] = Field(default=default_int_factory)
```

`int_factory_1` and `int_factory_2.default` are both instances of the `staticmethod` descriptor class. At some point in the `BaseModel`'s metaclass' `__new__` implementation, the class is created. Once this is done, we call `collect_model_fields` with the newly created class. In this function, we need to handle two cases:
- annotated fields without any assignment, e.g. `field: int`.
- annotated fields with an assignment, e.g. `field: int = 2`.

The second case is safely handled by this code:

https://github.com/pydantic/pydantic/blob/eda3eb472ce07e314858a7469e663f2e3c883578/pydantic/_internal/_fields.py#L196-L200

(not that `default` here has a poor naming as it refers to the assignment, it isn't necessarily a default value. For instance, you could have `field: int = Field(description='test')`, `field` is still required).

For both `int_factory_1` and `int_factory_2`, we won't get any attribute error. However, for `int_factory_1`, because it is a `staticmethod` instance (and thus, a descriptor), doing `getattr(cls, cls_name)` results in the descriptor taking effect (and will thus return the underyling function, which can be deepcopied/pickled).

---

I think we either:
- Align the `Field(default=...)` behavior with `= ...`., by calling the mimicking the class attribute access on the descriptor (that is, calling `default.__get__(None, cls)`). This avoids having to fix the `FieldInfo.get_default` function doing a deep copy of the default, which is the reason why it fails (this could be considered a Python bug, but according to [this comment](https://github.com/python/cpython/issues/95196#issue-1315858592) it seems to be intentional).
- Align the `= ...` behavior with `Field(default=...)`, that is changing `default = getattr(cls, ann_name, PydanticUndefined)` to `default = cls.__dict__.get(ann_name, PydanticUndefined)`. This will require fixing the `FieldInfo.get_default` function.

**Comment by jamesbraza** [comment]
To me, I think bullet 1 sounds better because it seems:

1. Bullet 1 more complies with the "principle of least surprise"
2. Bullet 2 will lead to different behaviors across Python versions, which is a headache
3. Bullet 2 involves breaking `int_factory_1` from working

**Comment by Viicos** [comment]
Related discussion for stdlib dataclasses: https://github.com/python/cpython/issues/102646
