### ISSUE TITLE
`str` does not converted to `Enum` as expected when extra typehints provided.

### ISSUE THREAD

**Issue by JamesCrumble** [pydantic/pydantic#10752]
### Initial Checks

- [x] I confirm that I'm using Pydantic V2

### Description

Single typehint `Enum` are converted successfully but after providing extra, things just don't work properly. 
Case where `decimal` -> `float` conveting works as expected whatever typehints provided after leading one.
Might be a mistake somewhere...

### Example Code

```Python
from enum import Enum
from typing import Any
from decimal import Decimal
from pydantic import BaseModel


class PeriodType(Enum):
    PAST_DAY: str = 'PAST_DAY'
    PAST_WEEK: str = 'PAST_WEEK'
    PAST_MONTH: str = 'PAST_MONTH'
    PAST_YEAR: str = 'PAST_YEAR'
    CURRENT_DAY: str = 'CURRENT_DAY'


class ModelWithConvertingToEnum(BaseModel):
    values: list[PeriodType]  # converts as expected
    value_non_list: PeriodType  # converts as expected


class ModelWithoutConvertingToEnum(BaseModel):
    values: list[PeriodType | Any]  # do not converts str -> enum due first position enum type
    value_non_list: PeriodType | Any  # do not converts str -> enum due first position enum type


class ModelWithConvertingOtherWay(BaseModel):
    values: list[float | Any]  # converts decimal -> float due first position float type
    value_non_list: float | Any  # converts decimal -> float due first position float type


# values=[<PeriodType.PAST_DAY: 'PAST_DAY'>] value_non_list=<PeriodType.PAST_DAY: 'PAST_DAY'>
print(ModelWithConvertingToEnum(values=[PeriodType.PAST_DAY.value], value_non_list=PeriodType.PAST_DAY.value))

# values=['PAST_DAY'] value_non_list='PAST_DAY'
print(ModelWithoutConvertingToEnum(values=[PeriodType.PAST_DAY.value], value_non_list=PeriodType.PAST_DAY.value))

# values=[1.1] value_non_list=1.1
print(ModelWithConvertingOtherWay(values=[Decimal(1.1), ], value_non_list=Decimal(1.1)))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /home/james/projects/bi-reports-api/venv_313/lib/python3.13/site-packages/pydantic
               python version: 3.13.0 (main, Oct  8 2024, 08:51:27) [GCC 9.4.0]
                     platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
             related packages: pydantic-settings-2.5.2 pydantic-extra-types-2.9.0 typing_extensions-4.12.2 fastapi-0.115.2
                       commit: unknown
```

**Comment by mpkocher** [comment]
1. When defining a Union type, this is going to be a new Type and will have different casting behavior than the individual types
2. `Any` is going to create some friction points here
3. I'm not sure this is completely correct, but I believe the basic algo for casting is: first pass to see if any type is matched (e.g., `isinstance` check), if nothing matches, then start left to right and try to cast. Hence, the `Any` is create some unexpected behavior. 
4. You can workaround this by using `AfterValidator` 

Here's an example:

```python
from typing import Any, Annotated
from enum import Enum
from pydantic import BaseModel, AfterValidator

class A(Enum):
    a = "a"
    b = "b"


def to_a(xs: Any) -> Any:
    if isinstance(xs, str):
        try:
            return A(xs)
        except ValueError:
            return xs
    return xs


class M0(BaseModel):
    alpha: A | int


class M1(BaseModel):
    alpha: A | int | str


class M2(BaseModel):
    # the after validator will provide some slop for casting
    alpha: Annotated[A | Any, AfterValidator(to_a)]


def demo() -> None:

    # All work as expected
    for x in (A.a, "1", 1, "a"):
        m = M0(alpha=x)
        print((x, m))

    for x in (A.a, 1, "a"):
        print((x, M1(alpha=x)))


    # not the AfterValidator will "fix" the last two cases.
    for x in (A.a, 1, "a", "b"):
        print((x, M2(alpha=x)))
```

**Comment by JamesCrumble** [comment]
@mpkocher Thanks for answer. It's working, right, but not the real solution and more like workaround. 
I know how to create hako to solve this problem in different way and the goal is to not overhead such case but make it handle problem as pydanticV1 handles. Make sense to not thinking about it and not make boilerplated code every time u face this issue

**Comment by sydney-runkle** [comment]
@JamesCrumble,

Thanks for your question. We offer builtin support for this kind of preference. You can use our `union_mode` setting with a `left_to_right` specification as follows:

Instead of doing:
```py
PeriodType | Any
```

Do:
```py
from typing import Annotated
from pydantic import Field

Annotated[PeriodType | Any, Field(union_mode='left_to_right')]
```

This ensures that the first union member that qualifies as a match (either in lax or strict mode is used), so in this case, you'll ge the expected result of conversion to an enum.

We default to `smart` mode which attempts to pick the best match. In the case above, it was choosing `Any`, as the match to your `PeriodType` enum was lax.

Let me know if you have any other questions, hope this helps!

**Comment by mpkocher** [comment]
It's nice that this feature is supported. 

The details of `smart` are a bit more involved than I realized. Between the configuration from `ConfigDict` and `Field`, there's a lot going on and it can be a bit challenging to internalize the expected behavior.  It's also a bit unclear how the "smart" scoring mechanism for Unions is supposed to work with `Strict=True` (#10571). 

https://docs.pydantic.dev/latest/concepts/unions/#smart-mode

I get that naming is challenging, but perhaps the name style should have focused on what it was doing (in other words, the matching approach), not the order.  In a western world, we assume the left to right order. Communicating the "best" match, and "first" match might have been more useful and intuitive? 

* `left_to_right` -> `first` or `eager`
* `smart` -> `best`

**Comment by sydney-runkle** [comment]
> Communicating the "best" match, and "first" match might have been more useful and intuitive?

Perhaps, I do think that's a more clear way to think about it. However, it'd be breaking to rename this now, and so many useres are dependent upon the current pattern, that I think we'll leave it as is for the time being.

Thanks for your feedback - feel free to submit a PR to update the docs if you feel they're missing something that could be helpful to users.
