### ISSUE TITLE
Slow setting an value of a basic Model

### ISSUE THREAD

**Issue by Tobestar86** [pydantic/pydantic#10853]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Comparing times between instantiating a complete yet simple model and just setting one value of that same model is weird.
Instantiating is 2 times faster than just setting the value.

Here are the results (python 3.12.7, pydantic 2.9.2):
settings the value:           4.338046199991368s
instantiating the model:  2.0315376999787986s

In comparison to pydantic V1 (python 3.10.15, pydantic 1.10.17):
settings the value:           1.136024700012058
instantiating the model:  5.844023300043773

### Example Code

```Python
import timeit
from pydantic import BaseModel


class MyObj(BaseModel):
    name: str
    value: int | None


if __name__ == "__main__":
    my_obj = MyObj(name="a", value=1)

    def set_obj(obj):
        obj.value = 10
        return obj

    def instantiation():
        return MyObj(name="a", value=1)

    print(timeit.timeit("set_obj(my_obj)", globals=globals(), number=1000000))
    print(timeit.timeit("instantiation()", globals=globals(), number=1000000))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\tweber\.conda\envs\optimizer_be_dev\Lib\site-packages\pydantic
               python version: 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 15:47:54) [MSC v.1941 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: fastapi-0.112.2 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by MarkusSintonen** [comment]
Yes, I have also seen this. It is because `__setattr__` does large amount of checks every time for normal attribute setting [here](https://github.com/pydantic/pydantic/blob/0157e343bac2313064492744ef07493b5c42bd5b/pydantic/main.py#L938). The data validation works a bit differently hence it's faster (it doesn't need to similar checks every time afaik).

I would wish the `__setattr__` would have a fast path for the usual case of setting normal model attributes. So models would have info about the attribute names that just need to set the value to the `__dict__` and `__pydantic_fields_set__`. Instead of having to do all the checks every time.

**Comment by MarkusSintonen** [comment]
Fixing this would be relatively straight forward https://github.com/pydantic/pydantic/pull/10868
