### ISSUE TITLE
2.10: `mypy` (with pydantic.mypy) complains about Too few arguments on default factory 

### ISSUE THREAD

**Issue by l00ptr** [pydantic/pydantic#10945]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi,

with the latest version of pydantic (`2.10.1`) and the mypy plugin, we observe some false positive with type validation.

When running mypy over that piece of code, we observe that kind of error:
``` console
test_default_factory.py:16: error: Too few arguments  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

I think it's some kind of regression, but i still don't know if it's on the mypy plugin or pydantic itself.

### Example Code

```Python
from typing import Annotated
from pydantic import BaseModel, Field


class P(BaseModel):
    age: Annotated[
        int,
        Field(
            default_factory=lambda: 0
        ),
    ]


f = P.model_fields["age"]
assert f.default_factory is not None
f.default_factory()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.1
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: /home/jvb/Dalibo/repo/dev/pglift/pglift/.tox/typing/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0]
                     platform: Linux-6.1.0-25-amd64-x86_64-with-glibc2.36
             related packages: mypy-1.13.0 typing_extensions-4.12.2 pydantic-settings-2.6.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
This is odd bc `default_factory` is typed as Callable[[], Any] | Callable[[dict[str, Any]], Any] | None

**Comment by Viicos** [comment]
In 2.10, default factories may accept a new `validated_data` argument. This means that field defaults are not necessarily independent of each other anymore, and are not "inspectable" at the class level (meaning if a default factory makes use of this `validated_data` argument, the default value may vary between instances, which wasn't the case before — assuming the default factory function was pure). We know this can be painful for code fetching a default value from a `FieldInfo` instance (to generate an OpenAPI spec, for instance).

We discussed this internally, but decided to keep the existing implementation.

Here are a couple actions that could be taken to mitigate the issue:
- Your `get_raw` function could be defined as:
  ```python
    @override
    def get_raw(self, item: str) -> Any:
        if item in self._cache:
            return self._cache[item]
        field = self._config_model.model_fields[item]
        if not field.is_required():
            self._cache[item] = field.get_default(call_default_factory=True)
        else:
            raise KeyError(f"config item {item!r} has no default value.")
  ```
  Note that `get_default` may raise a `ValueError` if the default factory requires a `validated_data` argument. But at least, you avoid the type checker error.
- We can add a new `default_factory_takes_validated_data` attribute on the `FieldInfo` class, so that you can check for this attribute before calling `get_default`.

**Comment by l00ptr** [comment]
@Viicos i think your reply is not related to this issue.
