### ISSUE TITLE
field annotation not respected by mypy when updated by a decorator

### ISSUE THREAD

**Issue by BarrettStephen** [pydantic/pydantic#11055]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

This decorator successfully makes the field optional (no runtime errors from this code), but mypy throws saying it is required. I'm unclear where the issue is between mypy, pydantic, pydantic mypy plugin, python, and this code.

Thanks!

### Example Code

```python
from typing import Type, Callable, Optional
from pydantic import BaseModel


def make_optional() -> Callable:
    """Return a decorator to make all model fields optional."""

    def decorator(cls: Type[BaseModel]) -> Type[BaseModel]:
        for field in cls.model_fields.values():
            if not field.is_required():
                continue
            field.default = None
            field.annotation = Optional[field.annotation]  # type: ignore
        cls.model_rebuild(force=True)
        return cls

    return decorator


@make_optional()
class MyModel(BaseModel):
    my_field: int


my_partial = MyModel()  # mypy throws: Missing named argument "my_field" for "MyModel"
```

### Python, Pydantic & OS Version

```Text
        pydantic version: 2.10.3
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: /home/sbarrett2/tmp/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.7 (main, Jan 22 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)]
                     platform: Linux-5.14.0-427.el9.x86_64-x86_64-with-glibc2.34
             related packages: typing_extensions-4.12.2 mypy-1.13.0 typing_extensions-4.12.2 mypy-1.13.0
                       commit: unknown
```

**Comment by BarrettStephen** [comment]
I messed up my reproduction. Will close this and open a new one if I need to. Sorry for the noise.

**Comment by BarrettStephen** [comment]
OK Fixed it and reopened. thanks!

**Comment by Viicos** [comment]
There's currently no way to indicate to type checkers that a decorator is applying changes to the field of a dataclass-like class such as Pydantic's `BaseModel`. There is some discussion [here](https://discuss.python.org/t/introduce-partial-for-typeddict/45176) to add a a similar feature to typed dictionaries, and dataclasses have been discussed as well. You can subscribe to [this issue](https://github.com/pydantic/pydantic/issues/1673) to be notified if we implement such a type safe feature (don't expect things to move before a year or so, this would require a PEP to be accepted first).

Regarding your decorator, I would at least suggest defining it like this:

```python
from typing import TypeVar

from pydantic import BaseModel

ModelTypeT = TypeVar('ModelTypeT', bound=type[BaseModel])

def make_optional(cls: ModelTypeT, /) -> ModelTypeT:
    for field in cls.model_fields.values():
        if not field.is_required():
            continue
        field.default = None
        field.annotation = Optional[field.annotation]  # type: ignore
    cls.model_rebuild(force=True)
    return cls

@make_optional
class MyModel(BaseModel):
    my_field: int
```

- Because `make_optional` doesn't take any arguments, you can make it so it takes the class directly as an argument.
- Using a type variable allows type checkers to understand the relationship between the argument and the return value. With the type variable, `MyModel` is still understood as `type[MyModel]` by mypy. Without the type variable, it will be understood as `type[BaseModel]`. Note that `MyModel(...).my_field` is still going to be typed as `int`, and not `Optional[int] = None`, but this is due to the limitation I mentioned above.

If you want `make_optional` to be usable as a bare decorator (`@make_optional`) or called (`@make_optional()`), the signature is more complicated. Refer to [this section](https://mypy.readthedocs.io/en/stable/generics.html#decorator-factories) of the mypy documentation for more info.

**Comment by BarrettStephen** [comment]
Thank you so much for the help and the effort to explain this in detail!
