### ISSUE TITLE
The default value in the annotated type does not apply

### ISSUE THREAD

**Issue by 9en9i** [pydantic/pydantic#11051]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi, I have a model that uses this construction in fastapi
```python
type Maybe[T] = Annotated[T | None, Field(None)]
```
Today I upgraded pydantic from 2.9.2 to 2.10.3 and now I get the `Field required` error. I tried rolling back the pydantic version and this error was not there, as expected the field can be left blank.

I have created a small example that reproduces this behavior. When using version 2.9 `field` can be left blank, whereas in version 2.10 I get the error.

### Example Code

```Python
from typing import Annotated

import uvicorn
from fastapi import FastAPI
from pydantic import Field, BaseModel

type Maybe[T] = Annotated[T | None, Field(None)]

app = FastAPI()


class Item(BaseModel):
    field: Maybe[int]


@app.post("/items/")
async def create_item(item: Item):
    return item


uvicorn.run(app)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.3
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/denis/Projects/project/backend/.venv/lib/python3.13/site-packages/pydantic
               python version: 3.13.1 (main, Dec  5 2024, 14:24:26) [Clang 16.0.0 (clang-1600.0.26.3)]
                     platform: macOS-15.0-arm64-arm-64bit-Mach-O
             related packages: fastapi-0.115.6 pydantic-settings-2.6.1 mypy-1.13.0 pyright-1.1.390 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sangameshbagewadi** [comment]
Key Changes:- 
Maybe[T] = Union[T, None]: We use Union from typing instead of Annotated for the Maybe type. This allows you to represent a field that can either be of type T or None.
Field(None) for the default value: The Field(None) ensures the field is optional and the default value is None.

Instead of using Annotated[T | None, Field(None)] directly, assign the default value separately.
Use Optional or Union with a default value in Field.

`from typing import Union
from pydantic import BaseModel, Field
import uvicorn
from fastapi import FastAPI

# Adjusting Maybe type to use Union for handling None type.
type Maybe[T] = Union[T, None]

app = FastAPI()

class Item(BaseModel):
    field: Maybe[int] = Field(None)  # Use Field(None) for default value

@app.post("/items/")
async def create_item(item: Item):
    return item

uvicorn.run(app)
`

**Comment by Viicos** [comment]
It's a long time since I've used FastAPI but:

- On both Pydantic 2.9 and 2.10, I get the query required error.
- FastAPI does not support the `Field` function. Instead you should use `Query`. But even then, the following results in a runtime exception from FastAPI:
  ```python
  @app.post("/items/")
  async def create_item(item: Annotated[int | None, Query(None)]):
      return item
  # AssertionError: `Query` default value cannot be set in `Annotated` for 'item'. Set the default value with `=` instead.
  ```
- FastAPI doesn't support the new type syntax: https://github.com/fastapi/fastapi/issues/10719.

**Comment by 9en9i** [comment]
@Viicos In version 2.9 exactly in the code I gave as an example there is no error. The field is not used as a query parameter but as a part of the query body

**Comment by Viicos** [comment]
Can you please double check your code snippet? Did you perhaps mean to use `Item` and not `Maybe[int]` as a type annotation for `create_item`?

**Comment by 9en9i** [comment]
Yes, typo. It should be using Item

**Comment by 9en9i** [comment]
@Viicos Can you reopen this issue? Or did you fail to reproduce it?

**Comment by Viicos** [comment]
A recent change in 2.10 related to schema building revealed a long standing issue in `pydantic-core`. Here is a reproducible example:

```python
from pydantic_core import SchemaValidator

schema = SchemaValidator({
    'type': 'definitions',
    'schema': {'type': 'definition-ref', 'schema_ref': 'field_ref'},
    'definitions': [
        {
            'type': 'default',
            'schema': {'type': 'int'},
            'default': 1,
            'ref': 'field_ref',
        },
    ],
})

schema.get_default_value()
#> None, i.e. no default value while it should be `Some(1)`.
```

I'm surprised we only hear about this today.
