### ISSUE TITLE
Type checking error with default value incompatible with annotation and `validate_default=True`

### ISSUE THREAD

**Issue by gadenbuie** [pydantic/pydantic#11083]
I just noticed that with pydantic 2.10.0, using `Field()` with `validate_default=True` when the `default` value doesn't match the expected final type causes pyright errors. For example, this example originally posted in https://github.com/pydantic/pydantic/issues/10973#issuecomment-2498985272

```py
from pydantic import BaseModel, ByteSize, Field

class MyModel(BaseModel):
    size: ByteSize = Field(default="100 MiB", validate_default=True)

print(MyModel().model_dump())
#> {'size': 104857600}
```

passes pyright checks cleanly with pydantic 2.9.2

```
uv add pyright==1.1.390 pydantic==2.9.2
uv run pyright repro.py
#> 0 errors, 0 warnings, 0 informations
```

but fails with pydantic 2.10.0

```
uv add pyright==1.1.390 pydantic==2.10.0
uv run pyright repro.py
#> /../repro.py
#>  /.../repro.py:4:22 - error: Type "str" is not assignable to declared type "ByteSize"
#>    "str" is not assignable to "ByteSize" (reportAssignmentType)
#> 1 error, 0 warnings, 0 informations
```

Is there a recommended approach we should use in this case or is ignoring the type error the best approach?

**Comment by Viicos** [comment]
In 2.10, the `Field` function had improvements related to type checking, so that `a: int = Field(default="str")` raises a type checking error.

> ignoring the type error the best approach?

This is probably the best way. I understand it can be annoying for some types such as `ByteSize`, where you don't want to think about what should be the correct int value (in your case 104857600).

If we get more reports like this, we might consider reverting/adding an extra overload to the `Field` function, so that if `validate_default=True`, we don't return the type variable (but this won't account for `validate_default` at the model config level).

**Comment by gadenbuie** [comment]
Thanks for the quick answer! I'll ignore the `reportAssignmentType` error for now.
