### ISSUE TITLE
Bools gets cast to str

### ISSUE THREAD

**Issue by jaroel** [pydantic/pydantic#1130]
# Bug
* OS: **MacOS Catalina**
* Python version : **3.8.0 (default, Dec 25 2019, 00:46:07)  [Clang 11.0.0 (clang-1100.0.33.16)]**
* Pydantic version : **1.3**

Bools get converted to the str representation by default.
ie False -> "False"

I'm unsure if that is the intended behavior?

```py
import pydantic
from pydantic import BaseModel

class NoteInNormal(BaseModel):
    text: str

(Pdb) NoteInNormal(text=False)
NoteInNormal(text='False')
...
```

**Comment by samuelcolvin** [comment]
What do you think should happen?

**Comment by samuelcolvin** [comment]
Problem is that it's often desired for ints to be cast to strings, maybe weird for bools to behave differently?

**Comment by jaroel** [comment]
I guess it would make sense -if the field is optional- that a json `false` would result in a python `None` - or the default if that's set. A string "False" makes no sense to me at all.
I'd rather just get a validation error when a bool is passed in, as `True` or `False` are no sensible values for a str field whatsoever. Clearing an optional field would use `None`, right?

Casting int to str makes some sense, but it probably indicates an badly implemented client.
Any string that uses leading zeros would become invalid when ints are allowd. This happens often with EAN, where a leading zero indicated a 12 number UPC instead of a 13 number EAN code.

I would special case bool and handle it as invalid input; hope this helps.

**Comment by dmontagu** [comment]
I think this gets back to the issue of strictness modes, which has been raised on many occasions.

-----

It seems like the three most commonly requested modes boil down to:

* Minimally strict (cast whenever possible; standard behavior)
* Maximally strict (essentially run-time type checking)
* JSON-strict (disallow conversions between types that would be represented as different JSON types)

In general, my opinion is that pydantic should try to be as un-opinionated as possible where there is controversy. I think there is relatively little controversy that the minimally-strict mode is useful (at least to *some* people, even if *you specifically* would prefer stricter checks), and there is also relatively little controversy about the utility or mechanics of the maximally-strict mode (though it hasn't yet been fully implemented).

However, in regard to the JSON mode, @samuelcolvin is right that there are frequently times when a number should be converted to a str, and conversely when a str should be converted to a number. While `bool` -> `str` may be particularly rare as a desirable conversion, 1) I can certainly imagine people designing applications with that expectation (for better or, more likely, worse), and 2) it just seems more internally consistent to me to perform the conversion here by default, since we do so everywhere else it is possible too.

In general, I think people are likely to have differing opinions on a variety of JSON-parsing edge cases. So I'm inclined to opt for simplicity and consistency and not try to take an opinionated stand on the specific ways JSON types should be allowed to be converted, and to just have users rely on a `StrictX` type if that's the parsing logic they want.

-------

I'm open to counter-arguments though, especially if we can achieve broad consensus on the desired conversions. At this point though, I personally would want to see a large degree of interest before changing any parsing behavior (even during a major version update) to minimize upgrade pain.

**Comment by jaroel** [comment]
Note: I've removed the strictmodel as it is not relevant to this issue.

Hi,

Thank you for your elaborate response. I understand your stance on this, though I don't agree.

As a consumer of this code, I found the behavior really weird.
Converting `int` to `str`, `str` to `int` and `null` to `None` make somewhat sense to me, but converting a `bool` to it's string representation seems odd for a validation lib to do.

By the looks of I don't agree with the values of this project at all, so I'm stepping out of this discussion.
Best wishes, and take care!

**Comment by dmontagu** [comment]
@jaroel For what it's worth, @samuelcolvin may have a different take.

At any rate, if you find a library that you think does a better job of (flexibly) supporting the specific validations you want, please let us know -- perhaps it will make use of patterns we could learn from and use to improve the project.

**Comment by samuelcolvin** [comment]
Given that #1098 seems to have no clear solution I'm leaning towards slowly make pydantic stricter in specific ways (upon major releases obviously) rather than a grand move to a strict mode (though I'm not yet certain).

Regarding this specific case I'm incined to agree that we should be less willing to coerce things to strings. Strings are a special case since everything has `__str__` methods so they can be displayed, that doesn't mean they make any sense.

So perhaps we should stop bools, ints & floats being cast to strings in v2?

**Comment by dmontagu** [comment]
@samuelcolvin I think that makes sense as default behavior, but I think if we do that we should probably add a number-to-string-friendly type (maybe with some relationship to `Decimal` and/or a maximum precision).

**Comment by espdev** [comment]
I have the same issue

```
class MyModel(BaseModel):
    name: str

MyModel(name=1)
Out[227]: MyModel(name='1')
```

**Comment by petebue** [comment]
I would like to +1 on this as today I came across where my tests against model validation passed when I passed in an integer because it was cast to a string.  My thoughts are if you are using this for any type of validation checks, like the value is a true string not an integer that was then cast to a string this would not really throw the ValidationError you were expecting to get.  I do see the other side of this in that maybe having a less strict mode would be valuable.  My thoughts would be to create flags for this in the Config class, maybe even have the more strict version that one that the flag would enable to maintain backwards compatibility with those that are expecting it to behave the way it already behaves.

**Comment by SebastianoF** [comment]
> What do you think should happen?

a `ValidationError` with "string type expected" error message would be helpful.

**Comment by samuelcolvin** [comment]
This is fixed on main and will be included in V2, you can try it now on the alpha release.

**Comment by michaelgmiller1** [comment]
@sydney-runkle any updates on the v2 startup performance issues? we also encountered this bug in v1, and I'm guessing the fix will not be ported to v2.

**Comment by michaelgmiller1** [comment]
actually this is an issue with our code  (not this bug) 😳. but still curious about any updates :)

**Comment by sydney-runkle** [comment]
@michaelgmiller1,

Great question! We're going to pour some resources into improving startup time shortly. Working on getting out the next release here soon, but that'll be a significant focus for v2.9.0!
