### ISSUE TITLE
Keep pydantic type information at runtime

### ISSUE THREAD

**Issue by stereobutter** [pydantic/pydantic#1245]
While trying to figure out [https://github.com/samuelcolvin/pydantic/issues/1243](https://github.com/samuelcolvin/pydantic/issues/1243) I stumbled over the following behavior:

```python
class Foo(BaseModel):
    bar: PositiveInt

foo = Foo(bar=1)
type(foo.bar)  # int
```

I think it would be useful if `foo.bar` in the example above were of type `PositiveInt` at runtime since runtime checks seem to work as expected with `PositiveInt`, notice:

```python
assert isinstance(PositiveInt(1), PositiveInt) 
assert isinstance(PositiveInt(1), int) 

assert not isinstance(1, PositiveInt)  # PositiveInt is more specific than int
assert not isinstance(PositiveInt(1), NegativeInt)
```

Minimal example where this would be useful: 

```python
from functools import singledispatch

class NaturalNumber(PositiveInt): pass

@singledispatch  # if no implementation is found
def my_abs(i): raise TypeError(f"bad operand type for my_abs(): '{type(i).__qualname__}'")
    
@my_abs.register  # handling 0, see End of the question for implementation of  'Zero'
def _(i: Zero) -> NaturalNumber: return NaturalNumber(0)

@my_abs.register # handling integers > 0 
def _(i: PositiveInt) -> NaturalNumber: return NaturalNumber(i)

@my_abs.register # handling integers < 0
def _(i: NegativeInt) -> NaturalNumber: return NaturalNumber(-i)
```

then the following works at runtime:

```python
assert isinstance(my_abs(PositiveInt(1)), NaturalNumber) 
assert isinstance(my_abs(NegativeInt(1)), NaturalNumber)
assert isinstance(my_abs(Zero(0)), NaturalNumber)
assert not isinstance(NegativeInt(-2), NaturalNumber)  # -2 is not a natural number
```
----
## Sidenotes/Questions:
- fields types (like `PositiveInt` and also my implementation of `Zero`) do not perform runtime checks on their own e.g. (`PositiveInt(-1)` does raise an exception). This is somewhat unexpected; could this be changed without breaking existing code?
- I tried having `NaturalNumber` inherit from `Zero` and `PositiveInt` but got `TypeError: multiple bases have instance lay-out conflict`, so without resolving this `isinstance(Zero(0), NaturalNumber)` would not work

---- 
## Extras:
Implementation of `Zero` used above:

```python
class Zero(int):

    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        if not v == 0 :
            raise ValueError('Non-zero integer passed to constructor')
        return cls()
```

**Comment by samuelcolvin** [comment]
Humm, I'm not sure I agree though I agree it can be confusing.

I think this would cause more problems than it would solve, e.g. with other libraries not knowing how to deal with `PositiveInt`.

It would also be confusing since we can't return an instance if the type annotation in all cases, e.g. `Json`.

**Comment by samuelcolvin** [comment]
I think we should document this rather than changing the behavior.

**Comment by SaschaSchlemmer** [comment]
- When `PositiveInt` is a _reasonable_ subclass of `int` _reasonable_ functions **(1)** that take `int` should be able to handle this at runtime ( try `PositiveInt(2) > 1` or `PositiveInt(1) + 1)`). For mypy this works out as well, since `PositiveInt` being a subclass of `int` makes it a sub type and functions behave covariantly with respect to their arguments. 
- Another nice benefit where mypy is concerned: observe `type(PositiveInt(1) +1))` being `int` i.e. using "impure" functions like `__add__` that know nothing about `PositiveInt` (and thus could violate the constraints of `PositiveInt`) downgrade the type to `int`. Any consumer of this result that expected an `PositiveInt` would now raise a TypeError because it can't be guaranteed that `PositiveInt(1) + someInt` is still positive. 
- Concerning `Json` over at [https://github.com/python/typing/issues/182](https://github.com/python/typing/issues/182) someone suggested using 
    ```python
    JSONType = t.Union[str, int, float, bool, None, t.Dict[str, t.Any], t.List[t.Any]]
    ```

**(1)** [https://en.wikipedia.org/wiki/Liskov_substitution_principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle)

**Comment by Congee** [comment]
Ummm, this is really a deal breaker as I cannot use a custom json encoder on subclass instances of primitive types. :cry:

**Comment by samuelcolvin** [comment]
information is available in V2 via `model.model_fields`.
