### ISSUE TITLE
Make dict validation stricter

### ISSUE THREAD

**Issue by and-semakin** [pydantic/pydantic#1268]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/andreisemakin/.local/share/virtualenvs/popapi-7C7w-VGz/lib/python3.7/site-packages/pydantic
               python version: 3.7.6 (default, Dec 30 2019, 19:38:26)  [Clang 11.0.0 (clang-1100.0.33.16)]
                     platform: Darwin-19.3.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Consider following code snippet:

```python
from pydantic import BaseModel, constr
from typing import Dict, Union


NotEmptyStr = constr(strict=True, min_length=1)


class RequestModel(BaseModel):
    value: Union[None, NotEmptyStr, Dict[str, NotEmptyStr]] = None


model = RequestModel.validate({"value": ""})
```

What would you expect `model.value` to be equal? I would expect it to raise `ValidationError`, because empty strings are not allowed, but apparently it coerces to dictionary:

```python
In [4]: model.value
Out[4]: {}
```

**Comment by samuelcolvin** [comment]
I think a string (empty or not) should never be valid as a dict.

Only question is whether this counts as a "breaking change" and therefore needs to wait for v2?

@dmontagu @tiangolo thoughts?

**Comment by and-semakin** [comment]
Ok, then I'll split out `condict` part from this issue to a separate one.

**Comment by and-semakin** [comment]
More cases (continuation of previous snippet):

```python
# list
In [5]: model2 = RequestModel.validate({"value": []})

In [6]: model2
Out[6]: RequestModel(value={})

# tuple
In [7]: model3 = RequestModel.validate({"value": ()})

In [8]: model3
Out[8]: RequestModel(value={})

# set
In [10]: model4 = RequestModel.validate({"value": set()})

In [11]: model4
Out[11]: RequestModel(value={})
```

So I guess any empty iterable can be coerced to dictionary.

**Comment by samuelcolvin** [comment]
Yes, so can a list of pairs.

All we really do is call `dict()` on the thing which is not sufficient. But to block all of this would definitely be a breaking change.

**Comment by and-semakin** [comment]
It may be a perfect use case for `condict(strict=True)` 🤔

**Comment by dmontagu** [comment]
The problem is that python can and will convert any iterable to a dictionary via `dict(...)` if all of the items are pairs.

As a result, any iterable that has no items will be converted to `{}`.

I personally would vote to change this behavior in v2 so that anything that isn't a subclass of `dict` just fails the `dict` validator. It wouldn't surprise me if there were reasonable uses of pydantic that this would break, but I personally feel this is an important enough change to be worth making in v2 despite posing backwards compatibility issues.

I'd be curious if there are any common uses of this functionality that could pose a more serious obstacle to making this change. (For example, if we need pydantic to be able to parse a model to a `Dict[str, Any]` under some circumstances, or similar.)

If we are going to change this behavior in v2, I would suggest we don't add `condict` as a type in pydantic-proper. But @and-semakin that wouldn't stop you from making use of a custom implementation in your own code in the mean time.

Thoughts?

**Comment by and-semakin** [comment]
Connected issue: https://github.com/samuelcolvin/pydantic/issues/558

**Comment by and-semakin** [comment]
Do we have any plans or estimation about when v2 will be ready?

I agree with your arguments @dmontagu. Do we want to save current behaviour of `dict`, maybe under some other name?

**Comment by samuelcolvin** [comment]
I agree with @dmontagu. I too thought there must be a situation where lists of pairs are coerced to a dict, but then couldn't think of one.

In terms of v2, I was originally hoping for the end of March, but I think that's no unrealistic.

Hopefully not too long through.

**Comment by spacemanspiff2007** [comment]
I have another case:
```python
"options": [
    {
        "value": "OPEN",
        "label": "Open"
    },
    {
        "value": "CLOSED",
        "label": "Closed"
    }
]
```
validated with
```python
options: Dict[str, str] = {}
```
becomes
```
{'value': 'label'}
```
which is quite wrong!

**Comment by samuelcolvin** [comment]
Agreed, I think for simplicity we should not allow lists as inputs to dicts in V2.

**Comment by tiangolo** [comment]
Yeah :thinking: 

Agreed with @dmontagu as well. :point_up:

**Comment by HansBrende** [comment]
Here's a slightly less intrusive tweak that would fix many of these bugs while remaining backwards-compatible with the existing ability to coerce a dict from a list of tuples. Maybe something like this can be added sooner than v2? https://github.com/samuelcolvin/pydantic/issues/2513#issuecomment-798806480
