### ISSUE TITLE
configuration of `title` should be similar to `alias`

### ISSUE THREAD

**Issue by skewty** [pydantic/pydantic#1361]
# Feature Request

Further to:  https://github.com/samuelcolvin/pydantic/issues/1186 I believe it would be wise to also handle `title` as you do `alias` because all the same caveats exist.  Additionally, if I am not mistaken, `alias` affects the `title` generated.

**Comment by samuelcolvin** [comment]
So in summary you want a method to generate titles? Makes sense.

I know I told you to create a new issue, but I agree this relates to #1186 - should we have different methods for each thing, or one method that can customise `title`, `alias` and anything else?

What other things might we want to customize?

**Comment by skewty** [comment]
I can't imagine any scenarios where a combined method might work better.  Perhaps if any come to to your mind you could share them?  Perhaps they might change my answer.

The following method seems sufficient to me at this time:

```python
class Config(BaseConfig):
    @classmethod
    def generate_title(cls, field_name: str, field_alias: Optional[str], field_title: str) -> str:
        return field_title
```

**Comment by samuelcolvin** [comment]
> I can't imagine any scenarios where a combined method might work better.

agreed, just thinking out loud.

**Comment by samuelcolvin** [comment]
happy to add `title_generator` to model config.

**Comment by dmontagu** [comment]
I have no problems with this, but I think if we add it we should call it `field_title_generator` rather than `title_generator`, as I think it is confusing since the model's `title` is something separate from what is discussed here.

Also, while I don't think this would be especially _challenging_ to implement (though may still be somewhat time consuming and will require some care around the use of something like `field_title_priority` with similar behavior to `alias_priority`), I think given the age of the request it would be best for us to wait to implement it until there is a broader expression of interest, or to accept a PR from a member of the community who cares enough to implement this functionality in a pull request.

**Comment by dmontagu** [comment]
I'm going to close this in favor of https://github.com/pydantic/pydantic/issues/4632 as that issue goes into a bit more detail. But don't worry, this hasn't been dropped!
