### ISSUE TITLE
Allow Infinity, -Infinity and NaN values on Decimal field

### ISSUE THREAD

**Issue by umatbro** [pydantic/pydantic#1885]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
 pydantic version: 1.4
            pydantic compiled: False
                 install path: <virtual env path>
               python version: 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18)  [Clang 6.0 (clang-600.0.57)]
                     platform: macOS-10.15.6-x86_64-i386-64bit
     optional deps. installed: []
```

`Infinity`, `-Infinity` and `NaN` decimal values should be allowed.
```py
import pydantic
from decimal import Decimal

class MyModel(pydantic.BaseModel):
    value: Decimal

m = MyModel(value="infinity")
assert m.value == Decimal("inf")
```

Currently this code would raise an error:
```
pydantic.error_wrappers.ValidationError: 1 validation error for MyModel
value
  value is not a valid decimal (type=value_error.decimal.not_finite)
```

This is caused by a check in the [`decimal_validator`](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/validators.py#L294).
This is inconsistent, because:
* `Infinity`, `-Infinity` and `NaN` are valid Decimal values.
* if we pass `Decimal` instance as a value (not a string) - there is no error
```
In[1]: MyModel(value=Decimal("inf"))
Out[1]: MyModel(value=Decimal('Infinity'))
```

Also, docs do not state that those values are excluded - https://pydantic-docs.helpmanual.io/usage/types/#constrained-types
> decimal.Decimal
    pydantic attempts to convert the value to a string, then passes the string to Decimal(v)

**Comment by sm-Fifteen** [comment]
The reason for this might be because, while those values are valid IEEE 754 floating point values (so they would be accepted both by Python's `float` and `Decimal` types), they are illegal in well-formed JSON according to [the JSON spec (RFC 7159), Section 6](https://tools.ietf.org/html/rfc7159#section-6):

> Numeric values that cannot be represented in the grammar below (such as Infinity and NaN) are not permitted.

With that being said, even though Pydantic usually follows very JSON-like parsing rules, it performs no such check when parsing `float` (which are supposed to follow the same restrictions) or `int` (which are not guaranteed to be correctly readable by all JSON parsers if they take up more than 53 bits) values, so removing that check would at least be consistent with other types.

NaN and Infinity do also this null-like quality to them in that they work unlike every other possible value (neither of them are considered to be equal to themselves and `NaN < 0 == false` but also `NaN >= 0 == false`, so adding those values makes lists of floats potentially unorderable), so there would be good reasons to leave them out, or at least make them opt-in.

**Comment by wozniakty** [comment]
I would also warn that, as unlikely as it may seem, it's hard to be certain that code might not be written by a pydantic consumer that depends upon these errors for functionality.  This would therefore represent a theoretically breaking change to the interface.

I echo @sm-Fifteen's concerns that there are a variety of reasons why Infinity and NaN might be excluded from the basic definition.  I would recommend that instead of changing the behavior of the decimal handler, we consider adding an alternate type for people who would like this functionality.  Something like `UnboundedDecimal` (name TBD) which would allow for these values, and also be explicit in documentation about how the value might be represented when calling `.json`.

**Comment by shifqu** [comment]
The issue I see with the current state of  the `decimal_validator` is that passing `Decimal("Infinity")` is allowed, but when passing the string `"Infinity"` the validation fails (as mentioned in the second bullet point by @umatbro).

```python
from decimal import Decimal

from pydantic import BaseModel, ValidationError


class Model(BaseModel):
    n: Decimal


try:
    Model(n="Infinity")
except ValidationError as e:
    print(str(e))
    """
    1 validation error for Model
    n
      value is not a valid decimal (type=value_error.decimal.not_finite)
    """

validated_model = Model(n=Decimal("Infinity"))
print(validated_model.n)
"Infinity"
```

This is because the first thing `decimal_validator` checks is if the provided value is a `Decimal` and if so, returns the object.

IMO before returning we should also check that the Decimal is not infinite and raise accordingly. (Then it would be consistent with passing a string.)
Another way would be to remove the `isinstance` check and let the decimal be converted to a string and carry on with the rest of the function. So the way I see it, either code is duplicated OR unnecessary conversions are done in case an actual `Decimal` is passed.
