### ISSUE TITLE
"extra" to replace values, field and config as validator arguments

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#2034]
As demonstrated by #2018 and #1993, the use of `values`, `field`, `config` as extra but optional arguments to validators is a pain.

My solution (partially outlined on #1984) is to create a new object `extra` (better name required maybe) which is just a namespace for extra stuff which validators might need access to, effectively something equivalent to

```py
@dataclass
class Extra:
    values: Dict[str, Any
    field: Field
    config: BaseConfig
    context: Any
```

This would mean:
* adding context was fairly easy #1549
* validators could easily call other validators without needing to know exactly which of `values`, `field`, `config` they need access to. This in turn will lead to big performance improvements since we can either remove or mostly stop using the whole "iterate through a list of validators" thing, and instead call validators from other validators
* all the lambdas in `_generic_validator_basic` and `_generic_validator_cls` can be removed

This of course requires v2.

**Comment by samuelcolvin** [comment]
We could also go back to using `**kwargs`, i once thought it was ugly, but it's a lot less ugly than what we have now.

Which is more performant?

Is using `**kwargs` and just telling people to allow for more arguments in their custom validators as a best practice a recipe for compatibility problems?

**Comment by PrettyWood** [comment]
It's funny I would have chosen `Context` for the whole dataclass with a key `extra`

**Comment by samuelcolvin** [comment]
Yes me too, but that's pretty confusing if we have `context` too.

**Comment by daviskirk** [comment]
> Which is more performant?

I think if this is super performance relevant passing `**kwargs` is slightly slower that just passing positional args (at least in python).
On the other hand we do have to construct the dataclass, but that's only once per object.
I don't know how cython affects all of this.

While not real benchmarks, here's a few timeit results:
```
In [2]: def f(a, b):
   ...:     return (a,b)
   ...: 

In [3]: d = {'a': 1, 'b': 4}

In [4]: a = (1, 4)

In [5]: %timeit f(*a)
122 ns ± 2.4 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [6]: %timeit f(**d)
208 ns ± 0.796 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [7]: %timeit f(a=1, b=4)
128 ns ± 1.7 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [8]: %timeit f(1, 4)
106 ns ± 1.36 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [9]: def f2(a, b):  # additional wrapper function (for example to modify args)
   ...:     return f(a, b)
   ...: 

In [10]: %timeit f2(*a)
195 ns ± 2.47 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [11]: %timeit f2(**d)
278 ns ± 0.602 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [12]: %timeit f2(a=1, b=4)
205 ns ± 2.02 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [13]: %timeit f2(1, 4)
181 ns ± 3.16 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

> Is using **kwargs and just telling people to allow for more arguments in their custom validators as a best practice a recipe for compatibility problems?

I think it would be if we don't check the signature beforehand and having some sort of partial/lambda in between (which I'm guessing is exactly what we want to avoid here).

Another possibility is to not go by names at all but pass by position no matter how the arguments are named.  That would make passing arguments based on the signature of the function pretty trivial and the "partial" would probably also be really fast since we're just cutting off a tuple of arguments.  Obviously removing the partial/lambdas all together is probably better for performance, but if we have to have them anyway if we want to differentiate between validators that pass "cls" and those that don't.

but I think I probably like the passing a single object better.

> It's funny I would have chosen Context for the whole dataclass with a key extra

This would be my intuition as well, so something like:

```python
@dataclass
class Context:
    values: Dict[str, Any
    field: Field
    config: BaseConfig
    extra: Any
```
