### ISSUE TITLE
Simplified length limited string

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#2104]
I often want `constr(max_length=XXX, strip_whitespace=True)`. Could we add a shortcut for this that worked better with mypy?

E.g. something like

```py
class Foobar(BaseModel):
    name: StrLimit[63]
```

This would be equivalent to `constr(max_length=63, strip_whitespace=True)`, e.g a field with a max length of `63`, no min limit, `strip_whitespace` enabled.

The name `StrLimit` is debatable. I think using `ConStr` might be confusing, but perhaps would make more sense?

We could also allow `StrLimit[10, 63]` which would be equivalent to `constr(min_length=10, max_length=63, strip_whitespace=True)`. However this would not be very pythonic in that the first argument meaning would change. Also I find myself wanting this very rarely.

thoughts?

**Comment by layday** [comment]
You can't really do this with typing in Python, I don't think.  The issue here is that to parametrise ('subscribe') a class for type checkers, it needs to be made generic.  But a generic type can only be parametrised with other types - `63` is an instance of `int` and would be invalid.  The only exception to this is [`Annotated`](https://www.python.org/dev/peps/pep-0593/).

**Comment by JacobHayes** [comment]
Perhaps this would be possible/clean with #2129 ([working prototype](https://github.com/JacobHayes/pydantic-annotated#pydantic-annotated))?

```
class Foobar(BaseModel):
    name: Annotated[str, MaxLen(63), StripWhitespace()]
```

**Comment by antonagestam** [comment]
@layday StrLimit doesn't need to be a class, it can be a subscribable object.

@samuelcolvin If we want to support both upper and lower bounds, perhaps `StrLimit[:63]` makes sense as syntax?

**Comment by adriangb** [comment]
I don't think this is necessary any more.
