### ISSUE TITLE
Remove Config.orm_mode and from_orm

### ISSUE THREAD

**Issue by charlax** [pydantic/pydantic#2283]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Feature Request

I see two issues with the `orm_mode` setting:

- It seems to imply that `orm_mode` modifies some other things to the model configuration or behavior. Yet, unless I'm wrong after reading the code, the only real place where it's used is in `from_orm`, and it's only to check that `Config.orm_mode` is set to True. Yet if we're using `from_orm` explicitly, it implies that we want the `orm_mode`... so it seems redundant.
- ORM is not a great name in this context, because (again, from what I understand), it actually only uses simple attribute access, without really knowing what the object is (it could be a plain object, not necessarily tied to a DB like the ORM name implies).

So, what do you think about simplifying and:

1. Dropping `orm_mode` from the configuration.
2. When instantiating a model from "something", trying first as a dict, then as a model, then as a plain object (logic in the classmethod `validate` in `main.py`). (btw, I think this is what marshmallow does)

This is somewhat related to https://github.com/tiangolo/fastapi/issues/2644

**Comment by daviskirk** [comment]
I don't know the implications of "implicitly" using orm mode as suggeted in (2). It might be that there would be too much "magic" and unwanted validation bugs where unknown object that either have "__getattr__" set or something like that?

However, I do agree that the naming "orm_mode" is a bit unintuitive (depending on the context) because as explained it actually just works on plain objects/attribute access and not "orm objects".
Anecdotally, I've also found that lots of devs are confused because of the "from_obj" which many devs assume to be what is now "from_orm". 

Unfortunately, I wouldn't know how to change this without massively breaking backwards compatability.
Might be something that could be done in a "v2" change?

**Comment by Kludex** [comment]
Both keywords are removed from V2.
