### ISSUE TITLE
Setting value of a field with sub-classed type outside constructor gets highlighted by mypy

### ISSUE THREAD

**Issue by tuukkamustonen** [pydantic/pydantic#2861]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

According to [pydantic docs](https://pydantic-docs.helpmanual.io/mypy_plugin/):

> Pydantic works well with mypy right out of the box.

However, `constr()` (and other similar) cannot be used without `mypy` nagging about them (see https://github.com/samuelcolvin/pydantic/issues/156#issuecomment-832982432). Workaround is to sub-class instead, like:

```py
class MyStr(pydantic.StrictStr):
    pass
```

However, while above passes `mypy` validation, setting fields for an already instantiated class does not:

```py
from pydantic import StrictStr, BaseModel

class MyStr(StrictStr):
    pass

class Model(BaseModel):
    field: MyStr

m = Model(field='jaja')  # works
m.field = 'override'  # gets highlighted
```

```console
$ mypy file.py
file.py:10: error: Incompatible types in assignment (expression has type "str", variable has type "MyStr")
Found 1 error in 1 file (checked 1 source file)
```

From `mypy` perspective, above probably makes sense (although `MyStr` inherits from `str`, it may... be different?). Not sure.

You can avoid the error at least two ways:

1. By actually using the sub-class:

   ```py
   m.field = MyStr('override')  # works
   ```

2. By mimicing `pydantic` code:

   ```py
   if TYPE_CHECKING:
       MyStr = str
   else:
       class MyStr(StrictStr):
           pass
   ```

However, both are very inconvenient. Surely not the solution intended here?

I believe docs should mention these oddities/shortcomings, and/or code should be fixed.

Potentially related: https://github.com/samuelcolvin/pydantic/issues/2329

# Env

```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/musttu/.pyenv/versions/3.7.10/envs/famp/lib/python3.7/site-packages/pydantic
               python version: 3.7.10 (default, Mar 19 2021, 13:17:32)  [GCC 9.3.0]
                     platform: Linux-5.8.0-53-generic-x86_64-with-debian-bullseye-sid
     optional deps. installed: ['typing-extensions']
```

**Comment by dmontagu** [comment]
In V2, the solution is to use `Annotated[StrictStr, annotated_types.Len(min_length, max_length)]` or similar. You can also use `Annotated[str, Field(strict=True, min_length=10)]`, etc.

You can see more details in the implementation of `constr` in v2, and using this `Annotated` approach (rather than the calls to the `constr` function) _should_ play nice with type checkers.

In general, I would advise against using the `constr` etc. functions in v2, precisely because they don't play nice with type checkers and the `Annotated` approach exists.

If you have more issues and aren't able to achieve what you want in v2, please let us know.

----

I recognize this may be frustrating, but at this point I don't think we will be releasing a fix for this in v1; if you need this pattern to work in v1, I would unfortunately recommend using one of the "very inconvenient" approaches described in the original issue.

**Comment by tuukkamustonen** [comment]
Thanks for taking time to respond 👍🏻

I've seen the advertised typing improvements in other tickets, happy to switch to `Annotated` and V2 ... once it's out 🥳
