### ISSUE TITLE
`.json()` does not use nested model's `Config`

### ISSUE THREAD

**Issue by a1350** [pydantic/pydantic#2972]
This looks like a duplicate of #1699 but both my models here are extending from the same `BaseModel`

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
pydantic compiled: True
install path: /***/python3.6/site-packages/pydantic
python version: 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01)  [GCC 9.3.0]
platform: Linux-3.10.0-***
optional deps. installed: ['typing-extensions']
```

Consider the following snippet
```py
from pydantic import BaseModel
from datetime import date
class Inner(BaseModel):
    d: date
    class Config:
        json_encoders = {
            date: lambda d: d.strftime("%d/%m/%Y")
        }

class Outer(BaseModel):
    inner: Inner

i = Inner(d=date(2021,7,9))
print(i.json())
print(Outer(inner=i).json())
```

This prints
```json
{"d": "09/07/2021"}
{"inner": {"d": "2021-07-09"}}
```

but `Outer.json()` should respect `Inner.Config`, i.e. it should be
```json
{"inner": {"d": "09/07/2021"}}
```

This might be the expected behaviour but it seems counter intuitive. Is there a nice workaround if it isn't a bug?

**Comment by mpkocher** [comment]
I believe I've run into a similar issue. A workaround can be to define a base model for your entire project/app. This can also help with consistency within a project/app.

```python
import pydantic
from datetime import date


class BaseModel(pydantic.BaseModel):
    class Config(pydantic.BaseConfig):
        json_encoders = {
            date: lambda d: d.strftime("%d/%m/%Y")
        }

class Inner(BaseModel):
    d: date


class Outer(BaseModel):
    inner: Inner


i = Inner(d=date(2021,7,9))
print(i.json())
print(Outer(inner=i).json())
```

Outputs: 

```bash
{"d": "09/07/2021"}
{"inner": {"d": "09/07/2021"}}
```

**Comment by dmontagu** [comment]
In v2, our new suggested approach to handling this is to create an annotated version of `date` that adds a PlainSerializer in an annotation, like this:
```python
from datetime import date

from typing_extensions import Annotated

import pydantic
from pydantic.annotated_arguments import PlainSerializer

DateWithSlashes = Annotated[
    date,
    PlainSerializer(
        lambda d: d.strftime("%d/%m/%Y"), json_return_type="str", when_used="json"
    ),
]

class Inner(pydantic.BaseModel):
    d: DateWithSlashes

class Outer(pydantic.BaseModel):
    inner: Inner

i = Inner(d=date(2021, 7, 9))
print(i.model_dump_json())
# > {"d":"09/07/2021"}
print(Outer(inner=i).model_dump_json())
# > {"inner":{"d":"09/07/2021"}}
```
While technically this does cannot be used to replace the behavior of `Config.json_encoders` in all circumstances, it seems that in most cases this behavior is actually preferable to the `json_encoders` behavior anyway (e.g., due to the consistency issue pointed out by mpkocher).

If you need to make use of the old-style json_encoders logic in a way that the new serializers functionality cannot replicate, please create an issue and we will come up with a way to address it.
