### ISSUE TITLE
Schema generated does not account for possibility of field names when `allow_population_by_field_name` is `True`

### ISSUE THREAD

**Issue by jpribyl** [pydantic/pydantic#3004]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
When the schema is generated on a model that has `allow_population_by_field_name` in it's config, pydantic should acknowledge that the fields might be populated with keys corresponding to their aliases or their field names.

Ideally, pydantic would show the user that keys may be `anyOf` the field names or aliases.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: False
                 install path: /home/j/kod/liquet/pydantic/pydantic
               python version: 3.9.6 (default, Jun 30 2021, 10:22:16)  [GCC 11.1.0]
                     platform: Linux-5.10.6-arch1-1-x86_64-with-glibc2.33
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```

See related issue that I opened here for a code snippet describing the bug: https://github.com/tiangolo/fastapi/issues/3559

I can see an argument to fix it here or there, but I think it is probably cleaner to fix in pydantic

**Comment by Kludex** [comment]
On the main branch, the following code...

```python
from pydantic import BaseModel, ConfigDict, Field
from rich.pretty import pprint

class User(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    id: int = Field(alias='user_id')
    name: str = 'John Doe'

pprint(User.model_json_schema())
```
Gives the following schema:
```python
{
   'type': 'object',
   'properties': {'user_id': {'type': 'integer', 'title': 'User Id'}, 'name': {'type': 'string', 'default': 'John Doe', 'title': 'Name'}},
   'required': ['user_id'],
   'title': 'User'
}
```

I think it makes sense for us to use `anyOf` here. 👍

**Comment by dmontagu** [comment]
I don't think using some sort of `anyOf` approach to adding this to the JSON schema is a good idea, at least certainly not by default.

* It's _very_ common that people have `allow_population_by_field_name` because they want this to work from the python API, but do not want to document it as part of their generated schemas.
* Using an `anyOf` in this way would result in _much_ uglier generated API clients if using something like `openapi-generator` with the schema, which many users of FastAPI (and therefore, indirect users of pydantic's JSON schema) do.

-----

In v2, we have made it much easier to modify JSON schema generation by subclassing `pydantic.json_schema.GenerateJsonSchema` and passing the subclass in as the `schema_generator` argument to `BaseModel.model_json_schema`. I would suggest that if you want to generate a schema that includes both the alias and the field name, you override the appropriate methods in the `GenerateJsonSchema` class to generate the schema you want.

(That said, I might hold off on this for a bit longer because the APIs for GenerateJsonSchema might change a bit prior to official release of v2.)

-----

In v1 or v2 today, if it is possible to make the changes you want inside `__modify_schema__` (which is deprecated in v2, but there is a migration path using the new `__get_pydantic_json_schema__`), that might be the simplest solution, but I think we would need to see significant community consensus before in any way modifying the default behavior related to this.
