### ISSUE TITLE
Custom error messages

### ISSUE THREAD

**Issue by SerhiyRomanov** [pydantic/pydantic#322]
# Question
I have question about l10n and i18n. Are possible to localize error messages using Python gettext for example?

**Comment by cjw296** [comment]
@samuelcolvin - great to see this, was just wondering about it, I wonder if it's worth re-opening this as a documentation issue, or did I miss more docs somewhere? :-)

**Comment by samuelcolvin** [comment]
Absolutely, pr welcome.

**Comment by molto0504** [comment]
> ```python
> def _(msg_id):
>     """
>     Very simple translation engine to demonstate,
>     use gettext in real life with mo, po files etc.
>     """
>     translations = {
>         'Value is not a valid float': "La valeur n'est pas un float valide",
>         'Not a valid path: "{path}"': 'Chemin non valide: "{path}"',
>     }
>     try:
>         return translations[msg_id]
>     except TypeError as e:
>         raise RuntimeError(f'no translations for "{msg_id}"') from e
> ```

Thanks for your code, It really helped me. `TypeError` -> `KeyError` by the way.

**Comment by rockallite** [comment]
Just to mention that the `'type'` naming logic is [here](https://github.com/samuelcolvin/pydantic/blob/13a5c7d676167b415080de5e6e6a74bea095b239/pydantic/error_wrappers.py#L139), or in `pydantic.error_wrappers:_get_exc_type`.

**Comment by dukkee** [comment]
@samuelcolvin @SerhiyRomanov @cjw296 Hey guys, I created a simple wrapper inspired by the Samuel's snippet: https://github.com/boardpack/pydantic-i18n

@samuelcolvin maybe it makes sense to add a page to the pydantic docs about it? I will create a PR if you agree :grinning:

**Comment by quang-megatron** [comment]
> Do you know how to get list of all the `error['type']` in `pydantic`? I just researched on `pydantic-core` and it seems to generate the `error-type` the lib combine `{x}_error.{type}.{error_type}`.
Or if we want to customize any error message, we need to try to input the error one to see the `type` then customize them later?

**Comment by samuelcolvin** [comment]
Also "type" is not unique, so it should be fairly easy to write custom error messages in other languages.

**Comment by quang-megatron** [comment]
@samuelcolvin Can you run that function and give me the error list when you are available, please? I don't know the Rust language so it seems hard for me to find that function and run it

**Comment by quang-megatron** [comment]
@samuelcolvin but the problem is I don't know what is the function name or where it is that you're talking about 🤣

**Comment by samuelcolvin** [comment]
Have a look in "pydantic_core._pydantic_core.pyi"

Samuel Colvin

**Comment by quang-megatron** [comment]
Thank @samuelcolvin I saw this function and got all the errors. It seems `pydantic` customize the error message and type before returning too.

I have case like like this:

```
class Validate(BaseModel):
     age = Field(gt=10)

Validate(age=9)
```

As I see, the `pydantic-core` would throw the error with this structure:
```{'example_context': {'gt': 0},
  'example_message': 'Input should be greater than 0',
  'message_template': 'Input should be greater than {gt}'
```
But here is the erro that I receive from `pydantic`
```
type = value_error.number.not_gt
message = ensure this value is greater than 10
```
Can you show me where the pydantic customize it, I can't find it. Also, can I get all the `error-types` that pydantic would return such as: `value_error.missing`, `value_error.number.not_le`, `value_error.any_str.max_length`, ...
Because that is all I want to translate the error message based on type, the `error-types` in `pydantic-core` are not the end of output that I expect. 
Thank @samuelcolvin alo

**Comment by quang-megatron** [comment]
@samuelcolvin it truly helps me man, wow, thank you a lot!
But one more question, I see the `pydantic` library  installed in my loca that has the codes in the 2 links that you embeded and I can't see in the `main` branch that I cloned your repo (The implementation of `PydanticErrorMixin` and the `ErrorWrapper` . I'm wondering how can I find the latest codes of library instead of looking in to the installed one in my local?

**Comment by orsinium** [comment]
I made one step further, and translated pydantic errors into a bunch of languages (with a help of professional translations agency) and packaged it as a plug-and-play Python library:

https://github.com/orsinium-labs/pydantic-translations
