### ISSUE TITLE
pydantic doesn't support inheriting from a type inheriting from TypedDict

### ISSUE THREAD

**Issue by barisione** [pydantic/pydantic#3427]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /usr/local/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 21 2020, 10:42:08)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

`TypedDict` supports inheritance, see https://www.python.org/dev/peps/pep-0589/#toc-entry-6, so I expected this to work:
```py
import pydantic
from typing_extensions import TypedDict


class Base(TypedDict):
    base_field: str


class Deriv(Base):
    deriv_field: str


class Model(pydantic.BaseModel):
    typed_dict: Base


base_dict = Base(base_field="foo")
deriv_dict = Deriv(base_field="hello", deriv_field="world")
for d in base_dict, deriv_dict:
    m = Model(typed_dict=d)
    print(m.typed_dict)
```

But pydantic drops keys not in `Base`:
```
{'base_field': 'foo'}
{'base_field': 'hello'}
```

Replacing the type in the model with `typed_dict: Union[Deriv, Base]` helps:
```
{'base_field': 'foo'}
{'base_field': 'hello', 'deriv_field': 'world'}
```
But this is not scalable if there more types. The order in the `Union` also matters as `Union[Base, Deriv]` doesn't work.

**Comment by Kludex** [comment]
This is the expected behavior. For `TypedDict`'s the concept of inheritance doesn't exist, we want to make sure the fields are the ones defined in the defined type.

**Comment by dmontagu** [comment]
I think the ambiguity about the right thing to do here is an unfortunate consequence of the fact that type checkers seem to treat `TypedDict` differently than a typescript-style interface. In particular, type checkers allow instances of subclasses, but do not allow dicts with undefined fields. I would entertain an argument that pydantic should allow extra fields for TypedDict-annotated fields, but the strongest argument for that would be to get mypy to change its behavior.

In particular, it's still strange to me that even though at runtime there is functionally no difference in the two variants of the final line in the following snippet, but one is acceptable to mypy, and the other raises a type error

```python
from typing_extensions import TypedDict


class BaseDict(TypedDict):
    field1: str


class SubDict(BaseDict):
    field2: str


def f(x: BaseDict):
    print(x['field1'])

f(SubDict(field1='abc', field2='def'))  # no mypy errors
f(dict(field1='abc', field2='def'))  # mypy error: Extra key "field2" for TypedDict "BaseDict"  [typeddict-unknown-key]
```

While I understand where @Kludex is coming from pointing out that this is related to issues with the nature of `TypedDict`, I think that given there is no way to distinguish between these two cases at runtime but one of them is acceptable to mypy,  there is an argument to be made for allowing "extra" (and, in particular, _keeping_ the values around) on typeddicts by default (rather than ignoring/forbidding it by default).

Given that, I'd like to re-open this issue and get @samuelcolvin's input before closing.

(For context, I'm not suggesting we change the default behavior of pydantic_core.typed_dict_schema or whatever; just when we create a core schema for a subclass of `typing.TypedDict` via pydantic, I'm thinking it might make sense for extra='allow' to be the default config setting.)

**Comment by dmontagu** [comment]
Also cc: @adriangb since you have been paying close attention to some of the TypedDict stuff in mypy world, etc.

**Comment by adriangb** [comment]
It's true that inheritance w/ TypedDict has a lot of warts. We fixed some of that in typing-extensions and 3.12, so it might be better going forward.

Generally, I agree with you @dmontagu: I don't think there's any situation in which having extra keys hurts unless you're unpacking the dict into something that expects them. I do think when we serialize we should remove them.

**Comment by dmontagu** [comment]
@adriangb good point about serialization, definitely should not include the extra keys when serializing according to a schema defined using the "subclass". (Basically the same behavior as we would do for subclasses of models now)

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
