### ISSUE TITLE
Field exclude not respected in json dump

### ISSUE THREAD

**Issue by mdgeorge4153** [pydantic/pydantic#3601]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0a2
            pydantic compiled: False
                 install path: /home/mdgeorge/.local/lib/python3.9/site-packages/pydantic
               python version: 3.9.7 (default, Sep 10 2021, 14:59:43)  [GCC 11.2.0]
                     platform: Linux-5.13.0-22-generic-x86_64-with-glibc2.34
     optional deps. installed: ['email-validator', 'typing-extensions']

```
Example:

```py
# Taken from https://pydantic-docs.helpmanual.io/usage/exporting_models/#advanced-include-and-exclude
import pydantic
from pydantic import BaseModel, Field, SecretStr


class User(BaseModel):
    id: int
    username: str
    password: SecretStr = Field(..., exclude=True)


class Transaction(BaseModel):
    id: str
    user: User = Field(..., exclude={'username'})
    value: int

    class Config:
        fields = {'value': {'exclude': True}}


t = Transaction(
    id='1234567890',
    user=User(
        id=42,
        username='JohnDoe',
        password='hashedpassword'
    ),
    value=9876543210,
)

print(t.dict())
#> {'id': '1234567890', 'user': {'id': 42}}

# Print the schema - Note that the excluded fields user and password are here
print(Transaction.schema_json(indent=2,exclude=0-))
```
```json
...
  "title": "Transaction",
  "type": "object",
  "properties": {
    "id": {
      "title": "Id",
      "type": "string"
    },
    "user": {
      "$ref": "#/definitions/User"
    },
    "value": {
      "title": "Value",
      "type": "integer"
    }
  },
  "required": [
    "id",
    "user",
    "value"
  ],
...
```

**Comment by kamilturek** [comment]
@mdgeorge4153 Does it need to be a schema dump? Maybe [model.json()](https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeljson) will do the job.

**Comment by nickderobertis** [comment]
I am also facing this. In my case, I have some types that are not JSON-serializable in my model, and exclude works properly to remove them from `model.json` but not `model.schema_json`. 

Happy to try to hack on this if we agree these fields should be excluded from the schema.

For context, in my case I am using Pydantic to read and write to a config file. I have a settings object with serialization info about what type of config file it should create (JSON/YAML/TOML), but I don't want that info in the config file itself. Exclude works fine to keep it out of the config file. But now I want to upload a JSON schema of the config file structure so that IDEs can auto-complete it. I don't see any way to do this short of temporarily removing the settings object, generating the schema, and adding back.

**Comment by hramezani** [comment]
Based on the documentation, `include` and `exclude` are respected in `json` and `dict` not in `schema_json`

**Comment by dmontagu** [comment]
For what it's worth, this should be improved in v2 (though will depend on some things that haven't been implemented quite yet, so if you install the current pre-release it won't work). In particular, I believe we can add support for reflecting the value of `exclude` in the JSON schema.
