### ISSUE TITLE
Side effect with local variable defined in executed codes in class definition

### ISSUE THREAD

**Issue by FabriceSalvaire** [pydantic/pydantic#3735]
_Sorry if this side effect is already known, but it is hard to google it..._

For this code which is valid Python but a bit unusual...

```
clas Foo(BaseModel):
   _MAP = {}    # not picked up

   # let execute some codes in the class definition...
   for i in range(10):   # define a local in the class scope
       bar = i    # define a local in the class scope
       _ = i       # not picked up
       _MAP{bar} = _
```

The locals `i`and `bar` are picked up as model fields by the internals of pydantic.

I guess it cannot be fixed, thus a hint in the documentation would be helpful.

A workaround is to use an init class method that doesn't spoil the class scope.

**Comment by adriangb** [comment]
That is some really weird code. It's not even valid Python, at the very least you need to use `class` instead of `clas` and `_MAP[...]` instead of `_MAP{bar}`. Please re-open if you have a real world use case with a reproducible self contained example.

**Comment by FabriceSalvaire** [comment]
Sorry It is just two typo in the source code...

**Comment by FabriceSalvaire** [comment]
I cannot reopen.

**Comment by adriangb** [comment]
Okay your example can be simplified down to:

```python
from pydantic import BaseModel

class Foo(BaseModel):
   bar: int = 1

Foo.bar
```

Pydantic purposefully does not keep the class attribute there. We could change that in the future but what we do now is conservative so that any future changes are not a breaking change. In other words, this is by design.

Further, the dynamic stuff you are doing in the class body is not a use case Pydantic has in mind or will make changes to support it. I think you'll find it's poorly supported in general. I have no idea what you are actually trying to achieve, but I'm sure there's a better way.

**Comment by dmontagu** [comment]
@FabriceSalvaire we introspect the namespace of the class to look for fields, which is why this won't work. Also, the only things in the namespace we don't attempt to convert to fields or private attributes are dunder names, or things with type in the `ignored_types` config setting.

Therefore, the closest I think you'll be able to get to your original code would be:
```python
from pydantic import BaseModel
_MAP = {}    # not picked up

# let execute some codes in the class definition...
for i in range(10):   # define a local in the class scope
   bar = i    # define a local in the class scope
   _ = i       # not picked up
   _MAP[bar] = _


class Foo(BaseModel):
    __MAP__ = _MAP


print(Foo.__MAP__)
# {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9}
```
