### ISSUE TITLE
[Pylance] BaseModel is allowing any extra field

### ISSUE THREAD

**Issue by Mokto** [pydantic/pydantic#3862]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

```
class A(BaseModel):
    property1: str

a = A(property1="a")
a.property1 = "b"
a.anything = "shouldfail"
```

Unfortunately the `a.anything = "shouldfail"` line is not triggering a typing issue. And I don't think there is any way to do it.

# Context

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/theo/Library/Caches/pypoetry/virtualenvs/platforms-K7nYilEZ-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.12 (default, Feb 23 2022, 18:58:53)  [Clang 13.0.0 (clang-1300.0.27.3)]
                     platform: macOS-12.2-arm64-arm-64bit
     optional deps. installed: ['typing-extensions'
```

**Comment by tuchandra** [comment]
This is a limitation / feature of the [`dataclass_transform` mechanism](https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md) that pydantic (and other similar libraries) use to allow type checkers to recognize models as dataclass-ish. There's currently no method by which a dataclass can specify that additional fields shouldn't be allowed. 

Because dataclasses themselves don't allow this, I wouldn't expect it to be possible:

```
from dataclasses import dataclass

@dataclass
class MyDataclass:
    a: str

dc = MyModel(a="hello")
dc.b = "does not error either"
```

If you'd like this to exist, I would recommend leaving a message in [the Github discussion in microsoft/pyright where it was originally proposed](https://github.com/microsoft/pyright/discussions/1782).

**Comment by Mokto** [comment]
<img width="851" alt="Screen Shot 2022-03-08 at 08 20 17" src="https://user-images.githubusercontent.com/5103928/157186723-0d87b003-6b79-44fb-91fe-cee7430f1acf.png">

<img width="826" alt="Screen Shot 2022-03-08 at 08 21 38" src="https://user-images.githubusercontent.com/5103928/157186906-f940d389-b724-4035-b1fe-3fc4fa168776.png">

This actually works with dataclasses.

**Comment by tuchandra** [comment]
🤦🏽  My bad - my lower snippet was still using MyModel. That's interesting. I do still think it's as-designed for the dataclass_transform spec, but I can see a compelling reason for it to account for this case.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
