### ISSUE TITLE
Docs should be consistent on whether validation is a primary purpose or not

### ISSUE THREAD

**Issue by smheidrich** [pydantic/pydantic#3884]
An infobox in the [docs on models](https://pydantic-docs.helpmanual.io/usage/models/) points out that (emphasis not mine)
>pydantic is primarily a parsing library, **not a validation library**.

Simultaneously, the *very first* sentences (taglines) of both the README the docs say
>Data validation and settings management [...] Define how data should be in pure, canonical Python 3.7+; validate it with pydantic.

This is confusing and one is tempted to conclude that either those intros or that infobox must be outdated, feel compelled to spend time looking into which one it is, eventually coming across #578 where some comments (https://github.com/samuelcolvin/pydantic/issues/578#issuecomment-533256681, https://github.com/samuelcolvin/pydantic/issues/578#issuecomment-708359477) already pointed out this exact issue.

Something that would, in my opinion, help a bit against this particular kind of confusion would be small additions to the infobox's exact phrasing, e.g. just acknowledging the contradiction:
>Despite its tagline, pydantic is actually primarily a parsing library, not a validation library.

**Comment by Kludex** [comment]
cc @samuelcolvin

**Comment by ariebovenberg** [comment]
Just wanted to chime in that I'm confused by this as well, and it seems to be even worse now. The *first line* in the documentation now says (emphasis mine)

> Pydantic is the most widely used **data validation library** for Python.

while the model docs still say:

> pydantic is primarily a parsing library, **not a validation library.**

**Comment by samuelcolvin** [comment]
Yup, sorry about this.

The fact is that Pydantic is not primarily concerned with validation as per it's definition:

> ### validation
> _noun_
> the action of checking or proving the validity or accuracy of something.

Rather, Pydantic is primarily concerned with guaranteeing that the structure you get after processing (aka validation) exactly matches the type hints you applied.

**However..**

The simple fact is that people use (and will inevitably continue to use) the word "validation" for the thing pydantic does.

Therefore, as explained [here](https://docs.pydantic.dev/latest/blog/pydantic-v2/#im-dropping-the-word-parse-and-just-using-validate) in the blog post about pydantic V2 last year, I decided to stop fighting it and just using the work validation since everyone understands it.

The "pydantic is primarily a parsing library, not a validation library." bit of the docs is outdated.

---

Overall we should:
* remove the "pydantic is primarily a parsing library..." notice from the docs
* add a section/page to the concepts bit of the docs once #7322 is further along explaining what we mean by validation, that it's technically a misnomer, but still the best term for what we do
