### ISSUE TITLE
Validator does not update Optional value

### ISSUE THREAD

**Issue by arturmkr** [pydantic/pydantic#3927]
Having following code:
```
from typing import Optional
from pydantic import BaseModel, validator


class Data(BaseModel):
    score: int
    title: str
    type: str
    created_by: Optional[str]

    @validator("created_by", always=True, pre=True)
    def check_created(cls, value):
        if value is None or value == "":
            return "user"
        else:
            return str(value)


data = Data(score=5, title="my title", type="my type")
print(data)
print(data.json(exclude_unset=True, exclude_none=True))
```
Output would be:
```
score=5 title='my title' type='my type' created_by='user'
{"score": 5, "title": "my title", "type": "my type"}
```

As a result, created_by is set in the model, but not in the json.

**Comment by tweakimp** [comment]
The decorator is called and is definitely updating the model.
The second print does not show the 'created_by' field because you called `.json` with `exclude_unset=True`.
See [here](https://pydantic-docs.helpmanual.io/usage/exporting_models/).

If you remove this keyword argument or set it to `False` you can see the `created_by` field in the second print as well.

**Comment by mangecoeur** [comment]
I think I'm having something similar w.r.t. optional fields: I have a custom Field type that has its own dict() implementation that is seems to only be called on non-optional fields, i.e.
```
class Foo:
    a: CustomField
    b: Optional[CustomField]

f = foo(...args...)

f.dict()

>> a.dict() is called
>> b.dict() is NOT called

```

**Comment by accelleon** [comment]
`exclude_unset=True` explicitly removes items that weren't included in the model's `__init__()` call. It doesn't function on whether the variable is modified or not. Pydantic keeps track of what fields you originally specified when creating the model inside of `__fields_set__` and thats what the exclusion is based on.

If you `print(data.__fields_set__)` in the above you'd get `{'score', 'title', 'type'}` hence why its being excluded.

You could append `'created_by'` to that internal property BUT if you're defaulting an `Optional[str]` to `'user'`. Why not just just `created_by: str = "user"` instead of the extra steps.

**Comment by SebTota** [comment]
Is it possible to update the `__fields_set__` value from the validator? I have a similar use case to this where I update my database keys based on what the user provided, but using the code below I still have to have a manual check in all of my API routes to see if the values have been added and if `__fields_set__` needs to be updated to include the `km` value. 

My use case is along the lines of:
```py
class SomeClass(BaseModel):
    odometer: Union[int, None]
    odometer_measurement: Union[OdometerMeasurementEnum, None]
    km: None

    @validator('km', pre=True, always=True)
    def set_km_value(cls, v, values):
        if 'odometer' in values and values['odometer'] is not None \
                and 'odometer_measurement' in values and values['odometer_measurement'] is not None:
            if values['odometer_measurement'] == OdometerMeasurementEnum.km.value:
                return values['odometer']
            elif values['odometer_measurement'] == OdometerMeasurementEnum.mi.value:
                return miles_to_kilometers(values['odometer'])
```

Running `__fields_set__` on the above would result in `odometer, odometer_measurement` if they are provided or an empty set if not. It would be great if from the validator we could add the `km` value so that later on  the `__fields_set__` value would include `odometer, odometer_measurement, km`

**Comment by samuelcolvin** [comment]
The original issue will be fixed by V2. Also root validators can modify `__fields_set__`.

This is already implemented in pydantic-core, so closing this.
