### ISSUE TITLE
ClassVar is not validated by validate_all

### ISSUE THREAD

**Issue by adivekar-utexas** [pydantic/pydantic#4280]
Output of python -c "import pydantic.utils; print(pydantic.utils.version_info())":

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /Users/adivekar/anaconda3/envs/eps2/lib/python3.7/site-packages/pydantic
               python version: 3.7.10 | packaged by conda-forge | (default, Oct 13 2021, 20:45:05)  [Clang 11.1.0 ]
                     platform: Darwin-21.4.0-x86_64-i386-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

```py
import pydantic
class Example(pydantic.BaseModel):
    MY_CLASS_FIELD: ClassVar[int] = 'abcd'
    class Config:
        validate_all = True

ex = Example()  ## This passes, but should fail.
```

However, validate_all does work when using instance variables:
```py
import pydantic
class Example(pydantic.BaseModel):
    my_instance_field: int = 'abcd'
    class Config:
        validate_all = True

ex = Example()  ## This fails with the following error:
## ValidationError: 1 validation error for Example
## my_instance_field
##  value is not a valid integer (type=type_error.integer)
```

Additionally, care should be taken that this works with #2061 (ClassVar inheritance).

**Comment by danielkatzan** [comment]
ClassVars are explicitly being excluded as attribute from the model, and it is documented [here](https://pydantic-docs.helpmanual.io/usage/models/#automatically-excluded-attributes)

the ClassVars attributes are not considered as part of the model __fields__ and as such are not being validate when creating the model

not sure if not validating those fields default values is a bug or expected behavior?
@samuelcolvin , is this in fact a bug? will be happy to open a PR if it is

I think we can iterate over the model __class_vars__ and validate them if needed after validating all the fields [here](https://github.com/pydantic/pydantic/blob/master/pydantic/main.py#L1041) 

as a side note question, why aren't default values being validated when the model is being defined
shouldn't the following fail even before trying to instantiate `MyModel`?
```
class MyModel(BaseModel):
    my_int: int = "a" 
```

**Comment by samuelcolvin** [comment]
```py
class MyModel(BaseModel):
    my_int: int = "a" 
```

As per [the docs](https://pydantic-docs.helpmanual.io/usage/model_config/) for `validate_all`, we don't validate default values by default, only when `validate_all` is true, this is for performance reasons, but has some other uses.

`ClassVar`s are not included in validation, as you say that's documented and expected behaviour, I definitely don't want to start validating `ClassVar`s the whole point is they're a way to define stuff on models which is completely ignored for validation.
