### ISSUE TITLE
Can I translate the document in Korean?

### ISSUE THREAD

**Issue by 0417taehyun** [pydantic/pydantic#4338]
Hello, I'm a student loving Python and Pydantic from South Korea, and I ask for translating the document in Korean.

We can make the document as FastAPI, which document is translated as many languages, however I think it might be better to create a new repository for translating and share the link here because of the cost to refactor the structure of project directory.

I just want to share this awesome stuff to Korean who are not fluent in English.

If you allow to translate it, I will create a repository and share the URL.

Anyway, thanks for your amazing jobs! I really love Pydantic.

**Comment by samuelcolvin** [comment]
HI @0417taehyun thanks for your suggestion and the offer of help.

One of the big problems with translations is keeping them up-to-date - it would rely on others to both write the docs, then keep them uptodate.

My guess is that most foreign language speaks would prefer to read up to date docs in english (or use google translate) than read wrong or out of date docs in their native language.

Since I (sadly :see_no_evil:) only speak English to a native standard, I can't really help with translations - if someone creates an issue saying "the spanish/korean/etc. docs are wrong here", I have no way to help.

I would therefore suggest you work on Korean pydantic docs and publish them yourself, I would happily link to your site from the pydantic docs. Another advantage of this is that you get credit for your work, you can even improve the docs and use your own style. You're free to reuse the code examples in the docs.

If there's anything technical we can help with - please let us know and we'll do what we can.

**Comment by 0417taehyun** [comment]
Thanks for you reply @samuelcolvin !

I will make a new repository and create a new pull request to add the link to the translated document. I want to keep the format of the origin document, thus I'm gonna use MkDocs as Pydantic did.

Thanks again for your amazing jobs!

**Comment by samuelcolvin** [comment]
Great. Let me know when you have something to show.

And ping me here if you have any questions.

**Comment by hramezani** [comment]
Please let us know when you are ready.
