### ISSUE TITLE
How about adding model tests for all of the json schema tests? 

### ISSUE THREAD

**Issue by spacether** [pydantic/pydantic#4404]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

How about adding model tests for all of the json schema tests?

They are at https://github.com/json-schema-org/JSON-Schema-Test-Suite/tree/main/tests

This will demonstrate the supported feature set

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Sounds for V2.

**Comment by Kludex** [comment]
What do you think @dmontagu ?

**Comment by dmontagu** [comment]
If I'm understanding correctly, these tests seem to be checking whether instances match a specific JSON schema.

However, pydantic doesn't actually do any JSON schema validation, and (purposely) does not provide guarantees that its validation perfectly matches JSON schema, considering JSON schema is much less expressive. That's not a judgement against JSON schema — it's just a reflection of the fact that pydantic was designed to be more powerful — for example, being able to coerce types, transform inputs, apply general purpose logic during validation, etc. The JSON schema we generate is intended to be _useful_ for things like generating API clients, etc., but is not tied to any aspect of runtime data validation in pydantic.

Because of this, I'm not sure this request makes sense — how would we make use of these tests in pydantic? That's not clear to me.

That said, I _would_ like to add an array of tests that:
1. the JSON schemas we produce are valid according to JSON schema
2. data that validates into a BaseModel subclass passes validation against the JSON schema and vice versa
3. instances of a BaseModel subclass serialize into data that passes validation against the JSON schema

However, I've already created a separate issue for this (don't remember the exact title, but it's along the lines of "use jsonschema for testing instances against their model schemas").

**Comment by spacether** [comment]
Do you mean this ticket?
https://github.com/pydantic/pydantic/issues/5164
