### ISSUE TITLE
Validation on resursive models don't raise error even on failing 

### ISSUE THREAD

**Issue by kunalkishore** [pydantic/pydantic#4590]
Output of python -c "import pydantic.utils; print(pydantic.utils.version_info())":

```shell
pydantic version: 1.9.2
pydantic compiled: True
install path: /Users/kunalsingh/anaconda3/envs/midas_pay_allocator/lib/python3.8/site-packages/pydantic
python version: 3.8.13 (default, Mar 28 2022, 06:13:39)  [Clang 12.0.0 ]
platform: macOS-12.3.1-arm64-arm-64bit
optional deps. installed: ['typing-extensions']
```

```python
from __future__ import annotations

from typing import Optional, Union, List

from pydantic import BaseModel, validator


class Condition(BaseModel):
    operation: str
    value: Union[List[Condition], Condition, float, int, list, str]
    attribute_name: Optional[str]

    @validator("operation", pre=True, always=True)
    @classmethod
    def validate_operations(cls, field_value):
        if field_value not in ["and", "or", "equal"]:
            msg = f"Supported operations: [and, or, equal]. Passed operation: {field_value}"
            raise ValueError(msg)
        return field_value


if __name__ == '__main__':
    condition4 = {'operation': 'or', 'value': [
        {'operation': 'equal', 'attribute_name': 'num_pay_txns_month', 'value': 6},
        {'operation': 'incorrect_operation', 'attribute_name': 'num_pay_txns_week', 'value': 3}]}
    print(Condition(**condition4))
```

Actual Output:
`operation='or' value=[{'operation': 'equal', 'attribute_name': 'num_pay_txns_month', 'value': 6}, {'operation': 'incorrect_operation', 'attribute_name': 'num_pay_txns_week', 'value': 3}] attribute_name=None`

Expected output:
`ValueError`

Please bear with me if this is not an issue but an implementation miss from my end.

**Comment by samuelcolvin** [comment]
Looking into it. In future, please use the "bug" template when creating bug issues.

**Comment by samuelcolvin** [comment]
Confirmed, but the problem is more severe, there's no validation whatsoever on the `List[Condition]` branch of the Union.

The following input also passes:

```py
condition4 = {
    'operation': 'or', 'value': [
        {'operation': 'equal', 'attribute_name': 'num_pay_txns_month', 'value': 6},
        {'operation': 'incorrect_operation', 'attribute_name': 'num_pay_txns_week', 'value': 3},
        'foobar'
    ]
}
```

This is not new in v1.10, the same error exists in v1.9.2 at least.

I don't know how difficult a fix will be, we might just need to raise an error if `ForwardRef`s can't be resolved like this.

**Comment by kunalkishore** [comment]
Thank you for looking into this promptly. 
Please correct me if I am wrong but your input is passing because `foobar` falls back to `str` because of this type resolution sequence: `Union[List[Condition], Condition, float, int, list, str]`. Hence, it doesn't go through the validation check of the `Condition` model.


For my original question, the solution that I am going for is raising a generic `Exception` rather than `ValueError` and that's solving my use case. Do you see a problem with that approach?

**Comment by samuelcolvin** [comment]
:facepalm: :facepalm: :facepalm: :facepalm:

Bad new is I'm being very dumb.

The good news (at least from my point of view :smile:) this that this is a mistake in your code, not an issue with pydantic.

Because `value: Union[List[Condition], Condition, float, int, list, str]` includes `list` which is interpreted as `List[Any]` the input to the top level `value` is validated against `List[Any]` and passes.

If you remove `list` from the union, your example behaves as expected.

**Comment by kunalkishore** [comment]
Great, thank you for pointing out my mistake. :)
