### ISSUE TITLE
V2: fix `create_model`

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4674]
Currently, I'm not convinced it's working properly.

Althought it'll be less important in V2, we should keep it.

Can probably be worked on once #4516 is merged.

**Comment by dwreeves** [comment]
You've mentioned on Twitter to me that "In v2, type is never inferred (mostly due to issues with field ordering). create_model needs to be updated to reflect this." ([link](https://twitter.com/samuel_colvin/status/1586473344253272065))

## Breaking API change - type inference

One issue right now with `create_model()` is that it relies on pre-pydantic-core type inference in the `ModelMetaclass` to resolve un-annotated defaults.

The `create_model` test case for `test_json::test_encoding` is the clearest example of this.

```python
@pytest.mark.parametrize(
    'gen_input,output',
    [
        ...
        (lambda: create_model('BarModel', a='b', c='d')(), '{"a": "b", "c": "d"}'),
        ...
    ],
)
def test_encoding(gen_input, output):
    assert output == json.dumps(gen_input(), default=pydantic_encoder)
```

- Pre pydantic-core behavior is that a model would be created with two fields: 'a' and 'c', with the types `str` inferred for both fields. And the test passes.
- Post pydantic-core behavior (i.e. the current `babelfish` branch) is:
    - `BarModel` is created without any annotations.
    - `ModelMetaclass.__new__` does not infer any types. To construct fields, we only rely on `__annotations__` and not `namespace`, meaning un-annotated fields are ignored.
    - `a` and `c` do not have annotations.
    - The new `BarModel` is created without any fields.
    - `pydantic_encoder()` calls `BarModel`'s `dict()` method, which returns an empty `dict` because it does not iterate over any model fields.

## 3 possible solutions

1. remove the old behavior of allowing for un-typed defaults in `create_model()`, and update the documentation + raise a clear error for the user.

2. make it so `create_model()` can infer its own types, prior to calling `ModelMetaclass.__new__`.

3. make it so `ModelMetaclass.__new__` uses the namespace and is able to resolve un-annotated fields.

Solution 3 is what you explicitly said was being removed from Pydantic 2.0, so that's not really a valid solution here that fits with your vision.

Solution 2 seems a little weird? It feels like `create_model()` should not be doing special things that you don't get from defining a model in the normal way.

Solution 1 is the most sensible solution, in my opinion.

---

I don't know that these are _all_ of the problems you are referring to in regards to `create_model()`, but it was the one that stuck out most to me.

**Comment by samuelcolvin** [comment]
> I don't know that these are all of the problems you are referring to in regards to `create_model()`, but it was the one that stuck out most to me.

Short answer is I have no idea, I haven't looked at it yet.

WRT your question, I think your summary is correct, options are either 1. or 2.. I agree 1. is my preference. Hopefully it makes the signature easier too.

Remember, `create_model()` shouldn't be used much in v2, since:
1. We have far more types to use
2. In the end, you can programmatically generate pydantic-core schemas for validation

**Comment by samuelcolvin** [comment]
@hramezani please can you look at this, maybe it can be closed?

**Comment by dmontagu** [comment]
I fixed all the create_model tests, there are currently no xfails. I won't promise that there aren't cases that it doesn't handle 100% properly (for starters, it (purposely) doesn't use the exact same logic as BaseModel for grabbing the parent namespace, so it currently might not handle forward refs as well as BaseModel). But I think it's in good enough state to be worthy of closing this issue. @hramezani if you find anything to indicate the contrary though I'll be happy to help resolve.

**Comment by hramezani** [comment]
Yes, we can close this issue. as @dmontagu mentioned all the `create_model` tests got fixed. I also test the case reported by @dwreeves, it raises a `TypeError` which seems good, and a [test for this case](https://github.com/pydantic/pydantic/blob/6b372cc279db23d85f9cb09db75fefc7512555e3/tests/test_create_model.py#L282) also has been added by @dmontagu
