### ISSUE TITLE
Invalid requirements

### ISSUE THREAD

**Issue by adriangb** [pydantic/pydantic#4745]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

https://github.com/pydantic/pydantic/blob/4d773bb96b0ef23bd5258be22ac37875c48d98d8/requirements/testing.txt#L15
https://github.com/pydantic/pydantic/blob/4d773bb96b0ef23bd5258be22ac37875c48d98d8/requirements/docs.txt#L38

this makes all.txt impossible to instal

options:
- add a layer of indirection and use pip constraints (keeps pip-tools)
- Use a package manager with support for dependency groups and lockfiles

### Example Code

```Python
N/A
```

### Python, Pydantic & OS Version

```Text
N/A
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Confirmed, same as #4742. I'll comment on this PR.

**Comment by samuelcolvin** [comment]
After looking into this, the problem was that the different requirements files were being generated with different python version:*
* `docs.txt` and `linting.txt` were being generated with 3.10 since they required recent flake8 which is not compatible with 3.7
* `testing.txt` and `testing-extra.txt` were being generated with 3.7 so that typed-ast (which is only required <3.8) as pinned - also I thought it more correct to generate those two files using 3.7 since tests are run on 3.7+

The solution proposed in #4748 is simply to generate all files lockfiles using 3.10 and the problems go away, I'm also going to install `all.txt` on when generate tests to double check that `pip install -r requirements/all.txt` is working.
