### ISSUE TITLE
Get rid of mandatory Rust-implemented component

### ISSUE THREAD

**Issue by KOLANICH** [pydantic/pydantic#4790]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

While I can understand that implementing something in Rust can have a benefit of it working faster, but it has grave drawbacks too.

1. If something is implemented in Rust, one needs Rust toolchain to build it from source. And the toolchain is quite large.
2. Native components have to be built for each version of `cpython` currently. When `cpython` is upgraded, they become unusable (well, there may be hacks with renaming of shared libs, I have done so with C libs, but it is not guaranteed to work, and if it works it is nkt guaranted to work stably and securely). Other python implementations usually don't support them, but support `ctypes`.
3. The `cargo`-cult practices in Rust ecosystem have resulted in static linkage of deps (that results in bloat), pinning their exact versions (that causes even more bloat where multiple versions of the same lib are used) and requiring the ones who build software to have the latest Rust toolchain (and even if one's code doesn't require it, some dep in the deps DAG can). Often nightly versions are required. These versions of Rust toolchain usually are not present within packages of sensible distros (where usually only old fossilized shit is present, not "shiny new shit" as they call the latest versions of software), and it is likely that nightly versions will never be present, and the Rust team is not trying to do anything about that. They haven't even set up an own repo with packages, instead the Rust official method of installation is the bullshit one `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`.
4. The whole language seems to be built aroud static linking and is intended to produce bloatware by design, like in the `npm` ecosystem where each project has an own copy of deps.
5. The deps DAG can go large, it is common for a simple package to require about ~90 deps (which makes compilation quite slow and for bigger projects, memory-hungry), some of which are not actually needed, but are still downloaded and compiled. And it is not generally safe to compile Rust crates. Also `cargo` is built around the central registry storing source distributions and such kind of registries are just an invitation to put benign-looking source into VCS, make it at least a bit popular and upload malware behaving stealthy enough into the registries, without touching the source in VCS. Bonus points if the malware leaves no traces but just finds the sensitive files and exfiltrates them via a steganographic channel.
6. `maturin` is an absolutely awful bloatware it takes a lot of time and RAM to build (I had to temporarily reenable overcommit in Linux kernel in order to build it (disabling overcommit allows to keep the system away of "trashing" (the state when only the reset button on the case helps), also known as "bug 12309", but it causes software (that works on Windows machines withnfar less RAM flawlessly) to crash because of `bad alloc`s) ).

These are the reasons to stay away of Rust toolchain.
The reasons to stay away of package registries have already been mentioned.
Since this project is a dependency of other projects, its dependencies, including Rust toolchain, become their dependencies too.

So it is proposed to introduce a policy that
1. the project should be usablemand installable in pure-python mode and fail safely if the native extension is unavailable
2. if a user needs acceleration, he/she can install an additional Rust-powered module and get the acceleration
3. The module should be used through `ctypes`, not through `pyO3`
4. If one wants to build the native component while building a python package, `setuptools_rust` should be used, not `maturin`.
5. it may make sense to get rid of Rust completely innfavour of C and/or C++. The security Rust provides IMHO doesn't outweight the bullshit one has to tolerate when dealing with Rust.

### Affected Components

- [X] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Thanks for your question.

As you might expect I strongly (viscerally) disagree with almost everything you've said.

I'll answer your points, but first a note of condolence: Being a rust hater looks like very hard work, bad luck.

Before I answer your specific points, a bit of clarification

## Pydantic 1, Pydantic 2, pydantic-core and rust

Pydantic <2 (e.g. all pydantic releases up until now) have no rust dependency whatsoever, they're written entirely in python. We compile almost all of that python (everything except `generics.py` I think) with cython to provide a roughly 50% speedup, we upload binaries for most setups to PyPI, if there's no available binary, `pip` will install the pure python wheel.

Pydantic 2 (and probably all future releases) will be a pure python package with a required dependency of `pydantic-core` which is written mostly in rust and available on PyPI as binaries for most OSs (see below).

We can't just release `pydantic-core` as a pure python package because almost all the logic is written in rust.

We could in theory create `pydantic-core-vanilla` - a pure python implementation of `pydantic-core`, here's how I would do it:
* painstaking copy all the logic from rust to python as part of the pydantic-core repo
* add a auto-use, parameterised fixture to pytest to run all tests against both the rust and python implementations

However there are a number of problems with this:
* it would require a massive amount of work to initially implement - I would guess 6 months work
* it would require ongoing  maintenance for the entire life of pydantic, similarly every new feature would need to be implemented twice
* there's currently no way to remove a required dependency with optional-dependency groups in pip/python ([here's](https://discuss.python.org/t/optional-dependency-groups-omitting-package-requirements/20833) a discussion where I asked for the feature, TL;DR it's been discussed for years and won't happen soon)
* some parts of pydantic-core would be very hard or impossible to exactly duplicate in python, e.g. there's no python package to exactly match the behaviour of `rust-url`, similarly python's regexes are somewhat different to rust regexes - e.g. rust regexes don't allow lookaheads and lookbehinds

Overall, I would estimate the 5 year cost of `pydantic-core-vanilla` at >$500,000. No matter how that's paid for, or even whether it's paid monetarily, it's a lot of work. And for what gain?

(Note, there's also the possibility of `pydantic-core-lite` which is compiled from the same source but uses some compile-time switches to create significantly smaller binaries, though `pydantic-core` binaries are already pretty small, so I'm not sure of the point, also it would still suffer from the required dependencies issue)

---

There's a lot of opinions here, and we're all somewhere-on-the-spectrum software developers, so let's leave the realm of opinions for a minute and resort to facts.

Let's look at some recent downloads of `pydantic` and see whether those users would have needed to install the rust-toolchain and compile `pydantic-core` manually if pydantic had had `pydantic-core` as a dependency at the time.

Run the following SQL on the PyPI downloads data (basically download count, python implementation, OS, CPU architecture and `libc` info about all pydantic downloads this year where `details` is not empty):

```sql
SELECT
  COUNT(*) AS num_downloads,
  details.implementation.name AS py_impl,
  details.system.name AS os,
  details.cpu AS cpu,
  details.distro.libc.lib AS libc
FROM
  `bigquery-public-data.pypi.file_downloads`
WHERE
  file.project = 'pydantic'
  -- ignore downloads with no details
  AND details.implementation.name IS NOT NULL
  AND DATE(timestamp) > DATE('2022-01-01')
GROUP BY `py_impl`, `os`, `cpu`, `libc`
ORDER BY num_downloads DESC
```

We get `275,550,643` downloads - a reasonable dataset I hope you'll agree.

There are 258 rows in the resulting data, but let's look just at the first 22 rows since that accounts for `275,546,586` downloads.

Of these:
* Binaries would have been available for 99.9895%
* Binaries would not have been available for 0.0053%
* the remaining few I'm not sure about - e.g. where we just have `CPython,Window` and no CPU or libc info

<details>
<summary>First 22 rows</summary>

|num_downloads|py_impl|os     |cpu    |libc |
|-------------|-------|-------|-------|-----|
|262,767,025  |CPython|Linux  |x86_64 |glibc|
|4,619,937    |CPython|Windows|AMD64  |     |
|2,973,674    |CPython|Linux  |aarch64|glibc|
|2,844,866    |CPython|Linux  |x86_64 |     |
|1,713,246    |CPython|Darwin |x86_64 |     |
|327,510      |CPython|Darwin |arm64  |     |
|119,570      |CPython|Linux  |aarch64|     |
|53,826       |PyPy   |Linux  |x86_64 |glibc|
|32,733       |CPython|Linux  |armv7l |glibc|
|14,371       |CPython|Windows|       |     |
|14,335       |CPython|Linux  |armv7l |     |
|13,514       |CPython|Windows|x86    |     |
|11,515       |PyPy   |Windows|AMD64  |     |
|9,093        |PyPy   |Darwin |x86_64 |     |
|7,051        |CPython|FreeBSD|amd64  |     |
|5,748        |CPython|Linux  |armv8l |     |
|5,244        |CPython|Linux  |i686   |glibc|
|5,008        |CPython|Linux  |ppc64le|glibc|
|4,953        |CPython|Linux  |i686   |     |
|1,777        |CPython|Linux  |s390x  |glibc|
|855          |PyPy   |Linux  |aarch64|glibc|
|735          |CPython|Linux  |armv6l |glibc|

</details>

In summary all 6 of your main points are moot for 99.9895% of those downloads.

---

To answer your points...

> If something is implemented in Rust, one needs Rust toolchain to build it from source. 

Moot point for most as explained above.

I've also found rust-toolchain and related tools very easy to use, definitely massively easier than equivalent tooling (or lack thereof) in C.

> Native components have to be built for each version of cpython currently. When cpython is upgraded, they become unusable

Again, not relevant for 99.99% of downloads. Binaries are already available up to 3.11.

> The `cargo`-cult practices in Rust ecosystem have resulted in static linkage of deps (that results in bloat), ...

Opinion based, I disagree, not relevant for most people.

> The whole language seems to be built aroud static linking and is intended to produce bloatware by design,

Opinion based, I disagree, not relevant for most people.

> The deps DAG can go large, it is common for a simple package to require about ~90 deps

`pydantic-core` doesn't have that many dependencies, I've looked at all of them.

Also I'm not downloading binaries of rust crates, cargo is download source and compiling it.

Again, none of that applies to the vast majority of python users who can just install the binary.

> maturin is an absolutely awful bloatware it takes a lot of time and RAM to build

Opinion based, I disagree, I've never had any trouble with it. Sounds like you're trying to find problems.

Again, not relevant to the vast majority of users who will install pydantic-core from a binary and never need to use maturin directly.

> the project should be usablemand installable in pure-python mode and fail safely if the native extension is unavailable

Not possible as explained above.

> The module should be used through ctypes, not through pyO3

This is a laughable idea.

> If one wants to build the native component while building a python package, setuptools_rust should be used, not maturin.

Again I disagree strongly, maturin has been great to use and it's maintainers have been very helpful.

> it may make sense to get rid of Rust completely innfavour of C and/or C++.

What!? This is for the birds.

**Comment by samuelcolvin** [comment]
But then again this is open source.

You're totally free to build and distribute `pydantic-core-vanilla` yourself, then fork pydantic and switch dependency. If you've built `pydantic-core-vanilla` correctly, that should be the only change you need to make in pydantic.

Let me know how you get on...

**Comment by sscherfke** [comment]
Out of pure curiosity, why did you choose maturin instead of setuptools_rust?

**Comment by samuelcolvin** [comment]
* It supports cross compilation to many different targets without all the mess of QEMU, see [here](https://github.com/pydantic/pydantic-core/blob/94b67f4419a67c7305c789abf723464877e3db45/.github/workflows/ci.yml#L231-L331)
* We use `pyproject.toml` and `setuptools_rust` only supports `setup.py`

**Comment by tiagoefreitas** [comment]
I got a use-case for pure python, I'm trying to run it on iOS using iSH (a 32bit x86 emulator) and rust fails there :)
however it seems with python 3.13 maturin will run on iOS native, so iSH emulation may not be needed anymore, I hope then pydantic can run fully in iOS

**Comment by actionless** [comment]
i'll give another usecase (i don't think the team would consider such rewrite anyway, but hopefully it would emerge at some point as a third-party project, matter of fact if it woudl be enough of community interest for a kickstarter project - i might consider myself working on that 😺):

**static compilation**

when compiling python lib statically with `musl` (for further translating your python app into C and building with `Nuitka`) - there is a problem that you can't load dynamic libs anymore, such `_pydantic-core.so`

**Comment by dwgillies** [comment]
Well, I'm facing a situation right now where I wanted to install fhir.resources, which depends upon pydantic-core==2.27.2.  And this means it cannot be installed on (A) WSL, or (B) Cygwin, only (C) Native Linux, only there, noplace else.  This has greatly limited the reach of your software, if that was your intent, go right ahead ... 

In my opinion, needing a compiler toolchain to install a library from another language is an abomination, but what do I know, I've only been in the SWE business for 48 years.

**Comment by barracuda156** [comment]
It would be not as bad if there was no massive breaking API change, but now we have that either every dependency of pydantic is broken where rust is broken (until it is broken, but that will be the case indefinitely), or an end user of every such platform has to rewrite every desired package back to 1.x-compatible API.
Vastly divergent APIs mean that upstreams are hugely disincentivized to maintain compatibility with 1.x branch, so while pure-Python branch exists, there is a problem that software for it does not.

P. S. I do understand that no one is obliged to do anything for free and “that’s your problem, go fix broken rust” is a valid approach. So this is just a statement of opinion, nothing more.

**Comment by zhangchn** [comment]
Can't build maturin on my android phone. Any possibility to remove this dependency?

**Comment by samuelcolvin** [comment]
no.

**Comment by Viicos** [comment]
> Can't build maturin on my android phone. Any possibility to remove this dependency?

See https://github.com/pydantic/pydantic/issues/12739.
