### ISSUE TITLE
Private fields in python use dunder prefix, not __name__ pattern

### ISSUE THREAD

**Issue by rafalkrupinski** [pydantic/pydantic#4833]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

pydantic.PrivateAttr expects that the field is either prefixed with a single underscore (sunder) or surrounded with double underscores, like \_\_name__.

Following https://peps.python.org/pep-0008/#descriptive-naming-styles
- class-private fields should fallow \_\_name pattern
- and all \_\_names__ are reserved for python magic

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: ~/Library/Caches/pypoetry/virtualenvs/lapidary-6fqZNkrQ-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.7 (main, Oct 30 2022, 01:28:25) [Clang 14.0.0 (clang-1400.0.29.102)]
                     platform: macOS-13.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
m
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @rafalkrupinski for reporting this issue.
So, If I got you correctly, The issue is about does not support `__` for `pydantic.PrivateAttr`. right?

**Comment by rafalkrupinski** [comment]
@hramezani yes, also that it encourages code practice against the standards

**Comment by hramezani** [comment]
Seems a good idea.
what do you think @samuelcolvin ?

**Comment by Bobronium** [comment]
I'd argue, having support for `__dunder__` names in `PrivateAttribute` is a good thing. 

The issue might be lying in naming of `PrivateAttribute`s, giving impression that their only use is for some internal values of the models. However,, they act as a standard mechanism for declaring, setting and storing data on model instances separate from their fields, being an interface to python `__slots__`, dealing with their creation and assignment.


So, it's not clear to me what exactly this issue is suggesting. @rafalkrupinski, do you have preferred outcome and a way of achieving?

I personally think, `PrivateAttribute`s might be better off with a different name, to suggest usages of dunder fields. We probably could drop `Private` part and leave just an `Attribute`?

One thing for sure, though: it's definitelly not a bug, but rather a design choice, and it's stated in docs:

> Private attribute names must start with underscore to prevent conflicts with model fields: both `_attr` and `__attr__` are supported.

**Comment by rafalkrupinski** [comment]
My initial issue was that I wanted to have class like this:
```python
class ImportData(BaseModel)
  __default_version = "1.0"
  version: str = __default_version
  # other data...
```
I guess I've mixed something up, because it works now.

I find the fact that PrivateAttr handles other attributes than private really confusing.

Cheers

**Comment by lig** [comment]
@rafalkrupinski According to [Pydantic v2 docs on private model attributes](https://docs.pydantic.dev/latest/usage/models/#private-model-attributes): "Private attribute names must start with underscore to prevent conflicts with model fields. However, dunder names (such as __attr__) are not supported."

This implies that Pydantic will recognize an attribute with any number of leading underscores as a private one. Indeed, looking in the test in this PR https://github.com/pydantic/pydantic/pull/7265 the behavior of an attribute with double leading underscores is exactly as expected. It behave similarly to an attribute with a single leading underscore and it behaves like a regular Python private attribute to which the name mangling ('m._Model__foo' instead of `m.__foo`) is applied.
