### ISSUE TITLE
V2: Get generic type class

### ISSUE THREAD

**Issue by mkdir700** [pydantic/pydantic#4908]
## Question
In general, I can call `get_args` to get generic class, but when one inherits from the `GenericModel` class, this function becomes invalid.

i'm sorry, I am not a native English speaker, the above description may be ambiguous, but you can check the example below, thank you!!

## Example:
```python
from typing import Generic, TypeVar, get_args

from pydantic import BaseModel
from pydantic.generics import GenericModel

T = TypeVar("T")


class Item(BaseModel):
    a: int


class MyList1(Generic[T]):
    def create_item(self, i: int) -> T:
        return get_args(self.__orig_class__)[0](a=i)  # type: ignore


class MyList2(GenericModel, Generic[T]):
    def create_item(self, i: int) -> T:
        return get_args(self.__orig_class__)[0](a=i)  # type: ignore


if __name__ == "__main__":
    list1 = MyList1[Item]()
    assert list1.create_item(1).a == 1  # ok
    list2 = MyList2[Item]()
    # AttributeError: 'MyList2[Item]' object has no attribute '__orig_class__'
    assert list2.create_item(2).a == 2
```

_Originally posted by @mkdir700 in https://github.com/pydantic/pydantic/discussions/4904_

**Comment by valm2** [comment]
The fact that if you invert the order of the mother classes makes the code work is a bit weird too...:
```python
class MyList2(Generic[T], GenericModel):
    def create_item(self, i: int) -> T:
        return get_args(self.__orig_class__)[0](a=i)  # type: ignore
...

list2 = MyList2[Item]() # Ok, no AttributeError
```
But the Pydantic doc explicitly shows examples with `GenericModel` first and `Generic[T]` as second class. Is it a problem to change the order ?

**Comment by mkdir700** [comment]
Thanks, It is feasible to use the `Generic[T]` as the first parameter.

But, I found a new problem that was to get the fields beyond when I called the `dict` method.

```python
class MyList2(Generic[T], GenericModel):
    item1: T

    def create_item(self, i: int) -> T:
        return get_args(self.__orig_class__)[0](a=i)  # type: ignore

list2 = MyList2[Item](item1=Item(a=1))
assert list2.item1.a == 1  # ok
print(list2.dict())  # {'item1': {'a': 1}, '__orig_class__': __main__.MyList2[__main__.Item]}
```

Of course, I can set the `exclude={"__orig_class__"}` parameter to solve this problem, so I don't know whether there are some hidden problems

**Comment by samuelcolvin** [comment]
@dmontagu might be worth looking at this in relation to #4970.

**Comment by dmontagu** [comment]
This is related to the behavior of `typing.get_args` etc. for things that aren't subclasses of `GenericAlias`. I think we may change the behavior of `BaseModel.__class_getitem__` in the future for improved compatibility, but in the meantime, we have functions `pydantic._internal._generics.get_args` and `pydantic._internal._generics.get_origin` that work for pydantic custom generics.

I wouldn't suggest using those functions directly, as we may remove them (since they are private APIs), but if you look at what they do, you may see how to properly retrieve this information yourself at runtime.

(That said, I'll also warn this may change before final release of v2 and/or in the future.)
