### ISSUE TITLE
Add type annotations for `class Model(BaseModel, extra=...)`

### ISSUE THREAD

**Issue by adriangb** [pydantic/pydantic#5430]
Since we allow `class Model(BaseModel, extra=...)` we should add some sort of typing to that. I believe we can do this via `if TYPE_CHECKING` and `__init_subclass__` (i.e. lie to type checkers and tell them we have an `__init_subclass__`). But there may be a better way to do it.

**Comment by dmontagu** [comment]
One issue with this is that currently we remove the config arguments and they don't actually get passed to `__init_subclass__`. So this would probably end up pretty confusing for users if they implement their own `__init_subclass__` and expect to receive those kwargs — they won't.

To change that and make it work, probably the best way to do it would be to provide an actual runtime implementation of `__init_subclass__` that accepted `**kwargs` since `object.__init_subclass__` doesn't accept any kwargs. For what it's worth, I think if you just add an implementation of `__init_subclass__` that does nothing but has the right signature, it should work if we stop popping the config-related `kwargs` off of what gets  passed into the `super().__new__` call in the metaclass.
