### ISSUE TITLE
Add a dev container configuration

### ISSUE THREAD

**Issue by JamesHutchison** [pydantic/pydantic#5437]
### Description

A developer container allows you to set-up up a reproducible environment for devs. It allows them to, quite literally, jump onto a project and start coding, writing and running tests, linting, and formatting correctly in a couple minutes or less.

If you want to see an example of them working, you can use github codespaces, which is free for a certain number of machine hours. A branch with a configured dev container for `pydantic-extra-types` can be found here: https://github.com/JamesHutchison/pydantic-extra-types/tree/dev-container

That dev container config can likely be used as a template for pydantic.

![codespace-create](https://user-images.githubusercontent.com/122519877/231024296-9adb30ca-c720-4ba5-9141-f404cfe04928.png)

**Comment by dmontagu** [comment]
It's pretty awesome that if you click the "Create a codespace on dev-container" button and wait for it to create the container, you get a vscode view and can immediately run `make test` in the terminal and it just works!

**Comment by yezz123** [comment]
Greetings @dmontagu and @samuelcolvin, I recently experimented with the developer container feature and found it to be an exemplary experience.

The provision of a pre-configured environment not only expedites the contribution process but also facilitates swift modifications.

In effect, this feature serves to streamline the onboarding process, as it eliminates the need to navigate the complexities of environment setup, which could otherwise impede progress.

I love the Experience ❤️ https://github.com/pydantic/pydantic-extra-types/pull/27

**Comment by dmontagu** [comment]
I recently attempted to use it with another project, and while it didn't work for me there due to issues with the configuration (and I won't name names 😄), I agree that the integration with GitHub promised an _extremely_ good experience for one-off contributions — don't have to do anything, and I get a ready-to-go vscode window where I can test out my tweaks all through github. 👍

**Comment by JamesHutchison** [comment]
> it didn't work for me there due to issues with that project's configuration

I've gotten dev containers to work on a variety of projects with different challenges in each. What kind of issues were you encountering?

**Comment by dmontagu** [comment]
The project just hadn’t set it up correctly, that’s all; I’m sure it could be fixed, it just needed some maintenance.

**Comment by Kludex** [comment]
Given the comment on https://github.com/pydantic/pydantic-extra-types/pull/27#issuecomment-1612636966, I'll close this issue for the same reason.
