### ISSUE TITLE
AnalyzedType lacks model_rebuild/update_forward_refs capabilities

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#5453]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

For \_\_root\_\_ models it was possible to `update_forward_refs` - AnalyzedType does not support such late initialization and does not work as replacement for \_\_root\_\_ models in situations where it is required.

### Example Code

```Python
from typing import Union
import json

from pydantic import AnalyzedType, BaseModel

class A(BaseModel):
    data: str

class B(BaseModel):
    file: bytes


classes = tuple([A,"C"])

T = Union[classes]
t = AnalyzedType(T)

# pydantic.errors.PydanticUndefinedAnnotation: Undefined annotation: name 'C' is not defined
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a1
                 install path: ~/venv/openapi3/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
                     platform: Linux-5.19.0-38-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by dmontagu** [comment]
Similar to #5454 I would not consider this a bug, but instead just point out that `AnalyzedType` is meant to be applied to a fully-built type, rather than a not-yet-parameterized type.

I will close this issue for now since it is so closely related to #5454, and note that the real solution to it will be a better way of migrating `__root__` models, which we can discuss in #5454 or elsewhere.
