### ISSUE TITLE
TypeError: Forward references must evaluate to types.

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#5477]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

The namespace used to resolve the models properties types gets contaminated with the models properties FieldInfos.

```
Traceback (most recent call last):
  File "~/.config/JetBrains/PyCharm2023.1/scratches/scratch_31.py", line 8, in <module>
    A_ = types.new_class("A", (BaseModel,), {}, lambda ns: ns.update({
  File "/usr/lib/python3.10/types.py", line 77, in new_class
    return meta(name, resolved_bases, ns, **kwds)
  File "~/venv/pydanticv2/lib/python3.10/site-packages/pydantic/main.py", line 165, in __new__
    _model_construction.set_model_fields(cls, bases, types_namespace)
  File "~/venv/pydanticv2/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 146, in set_model_fields
    fields, class_vars = collect_fields(cls, bases, types_namespace)
  File "~/venv/pydanticv2/lib/python3.10/site-packages/pydantic/_internal/_fields.py", line 139, in collect_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "~/venv/pydanticv2/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 266, in get_cls_type_hints_lenient
    hints[name] = typing._eval_type(value, globalns, localns)  # type: ignore[attr-defined]
  File "/usr/lib/python3.10/typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/lib/python3.10/typing.py", line 693, in _evaluate
    type_ = _type_check(
  File "/usr/lib/python3.10/typing.py", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Forward references must evaluate to types. Got FieldInfo(annotation=NoneType, required=False).
```

### Example Code

```Python
import types
from typing import ForwardRef
from pydantic import BaseModel, Field

A_ = types.new_class("A", (BaseModel,), {}, lambda ns: ns.update({
    "model_config": {"undefined_types_warning": False},
    "B":Field(default=None), "__annotations__":{"B":ForwardRef("B")}}))

print(A_)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a2
        pydantic-core version: 0.23.1 release build profile
                 install path: ~/venv/pydanticv2/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
                     platform: Linux-5.19.0-38-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by commonism** [comment]
https://github.com/pydantic/pydantic/blob/5e92b9bfac0018874d6e74f44b98715c85c88347/pydantic/_internal/_typing_extra.py#L242-L246

maybe:
```python
                except (NameError, TypeError):
                    # the point of this function is to be tolerant to this case
```

**Comment by dmontagu** [comment]
Can you explain what you are trying to do? It seems to me the issue is that you have a type with the same name as a field, as changing to:
```python
import types
from typing import ForwardRef
from pydantic import BaseModel, Field

A_ = types.new_class("A", (BaseModel,), {}, lambda ns: ns.update({
    "model_config": {"undefined_types_warning": False},
    "b":Field(default=None), "__annotations__":{"b":ForwardRef("B")}}))

print(A_)
```
resolves this.

While I think there may be a way to fix this, I'm not convinced that ignoring TypeError is the right answer here.

I also think we might be doing the right thing anyway, as this failure isn't specific to BaseModel:
```python
from typing import ForwardRef, get_type_hints
from pydantic import Field


class A:
    model_config = {"undefined_types_warning": False}
    B: ForwardRef("B") = Field(default=None)


print(get_type_hints(A))
#> TypeError: Forward references must evaluate to types. Got FieldInfo(annotation=NoneType, required=False).
```

**Comment by commonism** [comment]
I work the client side of OpenAPI/Swagger using pydantic to create models from existing description documents, I can't expect the service providers to change their services/description documents to match the name schema I support.

That said, the the example is a reduced excerpt from a description document - Dell Attributes extension to the DMTF Redfish protocol.
I use types.new_class to create models, but of course this can be reproduced using the more common approach as well:

```
from typing import ForwardRef
from pydantic import Field, BaseModel


class A(BaseModel):
    model_config = {"undefined_types_warning": False}
    B: ForwardRef("B") = Field(default=None)

A.model_rebuild()
```

This limitation did not exist in v1.

**Comment by dmontagu** [comment]
@commonism I wasn't able to make that change work with python 3.11 due to something related to how type hints are evaluated.

What I would suggest instead is that you modify your code to "namespace" your type hints in a way that will prevent collisions with things being added to the model namespace. In particular, since fields can't have names with leading underscores, I'm thinking something along the following lines might work for you:

```python

def test_invalid_forward_ref_model():
    class A(BaseModel):
        model_config = {'undefined_types_warning': False}

        B: ForwardRef('__types["B"]') = Field()  # noqa F821

    assert A.model_fields['B'].annotation == ForwardRef('__types["B"]')  # noqa F821
    A.model_rebuild(raise_errors=False)
    assert A.model_fields['B'].annotation == ForwardRef('__types["B"]')  # noqa F821

    class B(BaseModel):
        pass

    class C(BaseModel):
        pass

    assert not A.__pydantic_model_complete__
    types = {'B': B}
    A.model_rebuild(_types_namespace={'__types': types})
    assert A.__pydantic_model_complete__

    assert A(B=B()).B == B()
    with pytest.raises(ValidationError) as exc_info:
        A(B=C())
    assert exc_info.value.errors() == [
        {'input': C(), 'loc': ('B',), 'msg': 'Input should be a valid dictionary', 'type': 'dict_type'}
    ]
```
(This code runs in v1 without issues.) The idea is that you'd create a dictionary of types that would contain everything you'd want to access through a ForwardRef, then pass that as the main thing going into the `_types_namespace` argument to `model_rebuild`.

While I realize this may require you to refactor some of your code, I don't really like the idea of promising not to eagerly evaluate forward refs, as eliminating the need for manually evaluating them provides a significant user experience improvement for normal usage (especially related to generics).

I'm not opposed in principle to a PR that fixes this, but if the above approach addresses your use case I think it might ultimately be safer anyway.

Happy to discuss more if it doesn't work for you, or revisit the approach in #5519/your comments above if necessary, but given the points I just made I'm not sure if that will work out.

**Comment by dmontagu** [comment]
If this approach _does_ work for you, I would suggest we merge a PR which just adds that test in my previous comment to make sure we don't break this in the future.

**Comment by commonism** [comment]
works as expected

**Comment by commonism** [comment]
yes
