### ISSUE TITLE
V2 pydantic dataclass: InitVar and inheritance don't work together

### ISSUE THREAD

**Issue by andriilahuta** [pydantic/pydantic#5496]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

When using `from __future__ import annotations` the code example raises the following error:
``pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for dataclasses.InitVar[int]. Setting `arbitrary_types_allowed=True` in the model_config may prevent this error.``

### Example Code

```Python
from __future__ import annotations
from dataclasses import InitVar
from pydantic.dataclasses import dataclass

@dataclass
class Foo:
    init: InitVar[int]


@dataclass
class Bar(Foo):
    arg: int
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a2
        pydantic-core version: 0.24.0 release build profile
                 install path: C:\Program Files\Python\Lib\site-packages\pydantic
               python version: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by samuelcolvin** [comment]
Thanks for reporting, confirmed.

I get a slightly different error `Forward references must evaluate to types. Got dataclasses.InitVar[int].`, but that might be cause I'm on 3.10.

Still definitely needs to be fixed.

**Comment by dmontagu** [comment]
I did some investigation into this, and part of the problem is that dataclasses doesn't expose via "normal" public APIs whether it has determined if a field is an InitVar or not. (In this case, if you look at what it stores on `.__dataclass_fields__`, it has a ForwardRef as the type annotation, even though internally it did realize it should be an `InitVar` by doing some sort of namespace evaluation.)

However, there _is_ a way to determine if `dataclasses` realized the type should be an `InitVar` using only public APIs — the "field" will not show up in `dataclasses.fields(MyDataclass)`, but _will_ be present in `inspect.signature(MyDataclass)`. The main challenge remaining is that recognizing the field is an `InitVar` doesn't tell you what type it is, so you still need to make sure to evaluate the ForwardRef properly. The most likely way for this to work would be to add `InitVar` to the namespace, but there are various scenarios where this might not work perfectly (e.g., `ForwardRef('dataclasses.InitVar[int]')`, importing `InitVar` under a different name, etc.).

There may be a good way to resolve this, but I haven't discovered it quite yet. PR fixing this welcome, otherwise I'm sure we'll get to it eventually.

**Comment by dmontagu** [comment]
(Oh, and you can address the "ForwardRef must evaluate to types" thing by monkeypatching a `__call__` method onto `InitVar`, but I seem to vaguely recall that that both doesn't actually solve the problem, and there is a more promising path that doesn't require it. I'm dumping my half-baked thoughts on this here so they aren't lost.)

**Comment by dmontagu** [comment]
I think the best way forward here is probably to just check pseudo-private attributes in the `__dataclass_fields__` to check for being an InitVar
