### ISSUE TITLE
Documentation: Add guide/analysis comparing Pydantic + Djang-Rest-Framework.

### ISSUE THREAD

**Issue by ybressler** [pydantic/pydantic#5601]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

[PR #47](https://github.com/pydantic/pydantic/pull/47) is a top result for a google search on "Pydantic + DRF" >> I'd like for some information describing / comparing / analyzing the 2 to appear in Pydantic's documentation, so that curious inquirers don't get discouraged by lack of guidance.

Further, I don't see any benchmarks in this repo (this gives me a 404: https://docs.pydantic.dev/benchmarks/)– it looks like they've moved to pydantic-core? Additionally, I don't see a drf benchmark included there. Is this intentional?

**Related Work:**
- https://github.com/pydantic/pydantic/pull/1119

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by ybressler** [comment]
This SO answer by Sam comes close to a guide: https://stackoverflow.com/a/44860601/10521959

**Comment by ybressler** [comment]
This medium article comes close to being a guide: https://itracer.medium.com/extending-pydantic-use-cases-with-django-filtering-af7fd2bd6600

**Comment by dmontagu** [comment]
This has been discussed extensively in the past, but we probably won't be re-adding benchmarks for various reasons (mostly related to the ensuing flame-wars, but also because it's just hard to produce benchmarks that are indisputably fair and representative of real-world usage).

I think there are similar arguments to be made against providing framework comparisons — in many ways pydantic is clearly biased, and I don't know that we want to get caught up quibbling over what is best for what use cases.

If people want to write articles comparing frameworks I certainly wouldn't discourage them but I'm not sure to what extent it makes sense for us to direct people to the ones that are favorable to pydantic.

Defer to @samuelcolvin on this. (Also would be curious if @tiangolo has any guidance as I'm sure FastAPI has been faced with this to an even greater degree..)
