### ISSUE TITLE
In v2, attributes of nested dataclass instances are not validated

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5621]
If you have a field annotated with a dataclass, and you pass it an _instance_ of a dataclass which is not valid for its annotations, pydantic doesn't raise a ValidationError:

```python
import dataclasses

import pydantic


@dataclasses.dataclass
class MyClass:
    y: int


class Model(pydantic.BaseModel):
    x: MyClass


print(Model(x=MyClass(y='a')))
#> x=MyClass(y='a')

Model(x={'y': 'a'})
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
x.y
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='a', input_type=str]
"""
```

Is this the intended behavior?

If not, and if we change it, we may want to be careful about not re-validating _pydantic_ dataclasses for reasons of both performance and idempotency (this may cause headaches with generics though..)

(Incidentally, I believe this is related to some issues validating generic dataclasses.)

**Comment by dmontagu** [comment]
@samuelcolvin @adriangb keen to get your insights on this

**Comment by adriangb** [comment]
I think this is consistent with the behavior of BaseModel. If you set `revalidate_instances='always'` it gives you an error:

```python
import dataclasses

import pydantic
from pydantic.config import ConfigDict


@dataclasses.dataclass
class MyClass:
    y: int


class Model(pydantic.BaseModel):
    x: MyClass

    model_config = ConfigDict(revalidate_instances='always')


print(Model(x=MyClass(y='a')))
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
x.y
Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='a', input_type=str]
"""
```

The difference between a `BaseModel` and `dataclass` is just that a `dataclass` is easier to instantiate with bad data. I don't think we should special case that. I imagine users using dataclasses are doing so because they know it is valid (otherwise they would have chosen a BaseModel or made it a pydantic dataclass).
