### ISSUE TITLE
Inconsistent behavior of `Field(include=<...>)` between v1 and v2

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5714]
The following code has different behavior in v1 and v2:
```python
from pydantic import BaseModel, Field

class Inner(BaseModel):
    x: int

class Outer(BaseModel):
    inner: Inner = Field(include={})

print(Outer(inner=Inner(x=1)).model_dump_json())
#> v1: {"inner": {}}
#> v2: {"inner":{"x":1}}
```

I haven't checked, but I'm assuming the `exclude` keyword argument to `Field` is also affected. As far as I can tell, this seems to be the primary purpose of the `include`/`exclude` arguments (now that `Config.fields` is gone), so it may be worth removing them if we don't plan to fix this.

**Comment by robertofd1995** [comment]
This relates also the this other bug #6736 

And I can confirm that exclude is also affected as it can be seeing in the other issue.

This not only affects the model_dump_json but also model_json_schema

I think this needs to be fixed and not removed from the library, since pretty much all the types I have work with pydantic I had to exclude some attributes out (either from the public schema or from the output dict). 

Also notice that if the field is mark as private (e.x _inner) in order to exclude it, with callable attribute it adds self as first argument, which makes the function fail since the first expected argument would be always self

**Comment by sydney-runkle** [comment]
This is no longer relevant, as we deprecated the `include` param to the `Field()` constructor. See #6852
