### ISSUE TITLE
Cannot use Literal when I use typing-extension==4.6.0

### ISSUE THREAD

**Issue by choiking10** [pydantic/pydantic#5821]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I update my typing extention 4.6.0, I face this error

```
.venv/lib/python3.9/site-packages/ddtrace/internal/module.py:216: in _exec_module
    self.loader.exec_module(module)
src/entry.py:3: in <module>
    from apis import router as api_router
.venv/lib/python3.9/site-packages/ddtrace/internal/module.py:216: in _exec_module
    self.loader.exec_module(module)
src/apis/__init__.py:5: in <module>
    from .recsys import router as recsys_router
.venv/lib/python3.9/site-packages/ddtrace/internal/module.py:216: in _exec_module
    self.loader.exec_module(module)
src/apis/recsys/__init__.py:3: in <module>
    from .course.endpoints import router as course_router
.venv/lib/python3.9/site-packages/ddtrace/internal/module.py:216: in _exec_module
    self.loader.exec_module(module)
src/apis/recsys/course/__init__.py:1: in <module>
    from . import cell
.venv/lib/python3.9/site-packages/ddtrace/internal/module.py:216: in _exec_module
    self.loader.exec_module(module)
src/apis/recsys/course/cell/__init__.py:1: in <module>
    from . import container
.venv/lib/python3.9/site-packages/ddtrace/internal/module.py:216: in _exec_module
    self.loader.exec_module(module)
src/apis/recsys/course/cell/container.py:4: in <module>
    from core.models.feature_store.cell_dtos import CourseCellDTO
.venv/lib/python3.9/site-packages/ddtrace/internal/module.py:216: in _exec_module
    self.loader.exec_module(module)
src/core/models/feature_store/cell_dtos.py:14: in <module>
    class VocaCellDTO(BaseModel):
pydantic/main.py:197: in pydantic.main.ModelMetaclass.__new__
    ???
pydantic/fields.py:506: in pydantic.fields.ModelField.infer
    ???
pydantic/fields.py:436: in pydantic.fields.ModelField.__init__
    ???
pydantic/fields.py:552: in pydantic.fields.ModelField.prepare
    ???
pydantic/fields.py:668: in pydantic.fields.ModelField._type_analysis
    ???
```

### Example Code

```Python
from enum import Enum
from typing import Literal

from pydantic import BaseModel


class MyEum(str, Enum):
    T1 = "T1"
    T2 = "T2"


class MyType(BaseModel):
    type: Literal[MyEum.T1] = MyEum.T1
    dalc: str
```

then I meet

```Text
Traceback (most recent call last):
  File "/Users/project/test.py", line 12, in <module>
    class MyType(BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/Users/project/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
            pydantic compiled: True
               python version: 3.9.13 (main, Aug 25 2022, 18:24:45)  [Clang 12.0.0 ]
                     platform: macOS-12.6.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by cmditch** [comment]
Just started hitting this as well.

**Comment by mdavis-xyz** [comment]
I'm getting this too. Even on pydantic v2.

As a workaround:

1. upgrade to python 3.10. This issue happens on 3.9 but not 3.10; or
2. change `from typing import Literal` to `from typing_extensions import Literal`

The [docs for pydantic](https://docs.pydantic.dev/latest/usage/types/#literal-type) do say:

> This is a new feature of the Python standard library as of Python 3.8; prior to Python 3.8, it requires the [typing-extensions](https://pypi.org/project/typing-extensions/) package.

But I find that documentation ambiguous. It sounds like the requirement is that typing_extensions merely be installed, and then pydantic will choose it if required. But that doesn't seem to be the case.

So I think we need clearer documentation.

I think the source of the bug is this line:

https://github.com/pydantic/pydantic/blob/bf6b884563e7c635b9d811e97d2fdb51805398b1/pydantic/typing.py#LL412C57-L412C64

```
from typing_extensions import (
...
    Literal,
...
)
...
def is_literal_type(type_: Type[Any]) -> bool:
    return Literal is not None and get_origin(type_) is Literal
```

So I think this is a bug in pydantic. `is_literal_type` is comparing only to `typing_extensions.Literal`, not `typing.Literal`.

I think a patch looks something like:

```
def is_literal_type(type_: Type[Any]) -> bool:
    return Literal is not None and get_origin(type_) in [typing.Literal, typing_extensions.Literal]
```

**Comment by AiyionPrime** [comment]
Can confirm, the bug appears to occur with `typing-extension==4.6.0`.

**Comment by eachimei** [comment]
Minimal steps to reproduce the issue (typing_extensions==4.6.0, pydantic==1.10.7, Python 3.8.10):
```python
from typing import Literal
from pydantic import BaseModel


class MyType(BaseModel):
    literal: Literal["foobar"] = "foobar"

```
raises:
`TypeError: issubclass() arg 1 must be a class`

**Comment by samuelcolvin** [comment]
Thanks for reporting, @hramezani will take a look 🙏.

**Comment by Czaki** [comment]
I could confirm that this bug is caused by this commit https://github.com/python/typing_extensions/commit/fb37b2ee0ab56baf2dfd5df27aec0430435ba17f

**Comment by hramezani** [comment]
@mdavis-xyz thanks for your explanation. seems your suggestion will fix the bug. Do you want to create a patch for fixing? otherwise, I will create a patch.

**Comment by AlexWaygood** [comment]
This has also been reported over at typing_extensions FYI: https://github.com/python/typing_extensions/issues/179.

> I think the source of the bug is this line:
> 
> https://github.com/pydantic/pydantic/blob/bf6b884563e7c635b9d811e97d2fdb51805398b1/pydantic/typing.py#LL412C57-L412C64
> 
> ```
> from typing_extensions import (
> ...
>     Literal,
> ...
> )
> ...
> def is_literal_type(type_: Type[Any]) -> bool:
>     return Literal is not None and get_origin(type_) is Literal
> ```
> 
> So I think this is a bug in pydantic. `is_literal_type` is comparing only to `typing_extensions.Literal`, not `typing.Literal`.
> 
> I think a patch looks something like:
> 
> ```
> def is_literal_type(type_: Type[Any]) -> bool:
>     return Literal is not None and get_origin(type_) in [typing.Literal, typing_extensions.Literal]
> ```

If this analysis is correct (and I haven't checked, but it looks very plausible), you'd probably want to do something like this, in order to retain compatibility with Python 3.7 (where `typing.Literal` isn't a thing yet):

```python
_Literal_types = {typing_extensions.Literal}

if hasattr(typing, "Literal"):
    _Literal_types.add(typing.Literal)

def is_literal_type(type_: Type[Any]) -> bool:
    return Literal is not None and get_origin(type_) in _Literal_types
```

(Not sure under what conditions `Literal` can be `None` btw? Seems like a slight oddity in the code as it's currently written :)

**Comment by JelleZijlstra** [comment]
Just as a suggestion for Pydantic, I would recommend to replace any code like `is typing.X` with something that checks for both `typing` and `typing_extensions`. In pyanalyze I have a helper for that: https://github.com/quora/pyanalyze/blob/master/pyanalyze/safe.py#L148 (used e.g. at https://github.com/quora/pyanalyze/blob/27fbd1831c908477baf4f9988f23a8278ce5f64e/pyanalyze/annotations.py#L783). This would be safer against future typing-extensions changes that might bring additional backports.

**Comment by jessekrubin** [comment]
Thank god I thought to check the pydantic issues after furrowing my brow for 20 mins!

**Comment by dmontagu** [comment]
Hey all, we've just released v1.10.8 to address this. It's going through CI now and should hopefully be available through PyPI shortly. Please let us know if you run into other issues (with `typing_extensions` or otherwise) and we will address them as promptly as we can.

**Comment by jessekrubin** [comment]
@dmontagu @samuelcolvin yall the best!

**Comment by jnawk** [comment]
How about yanking 1.10.7 from pypi?  (as in the footsteps of 1.10.3)

**Comment by dmontagu** [comment]
@jnawk @Czaki the reason that 1.10.3 was yanked was because 1.10.4 updated the minimum-allowed-version of typing_extensions. As a result, it was incompatible to use pydantic 1.10.4 with other libraries that had pinned the version of typing_extensions below 4.2.0.

However, the release of pydantic 1.10.8 did not set any new minimum dependency versions (it just fixed the bug). So unless I'm missing something, I don't think the same reasons for yanking the 1.10.3 pydantic version apply here.

**Comment by RandallPittmanOrSt** [comment]
Just to add info: From my tests, this bug is present for all installs I tried with Python 3.7 as well as any combination of the following:

- **Python** 3.8 and 3.9
- **typing-extensions** >= 4.6
- **Pydantic** 1.8 - 1.10.7

It appears to be not an issue for any version of Pydantic 1.10.8+ **or** Python 3.10+. It also appears to not be a problem for **typing-extensions** 4.4 or 4.5. I did not test Pydantic < 1.8 or typing-extensions < 4.4.
