### ISSUE TITLE
BaseModel.__getattr__ ceased working with private attributes

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#5946]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

BaseModel.\_\_getattr\_\_ is not usable any longer with private attributes - I guess related to #5891 .

https://github.com/pydantic/pydantic/blob/d91c1ee37a10ac4f968b100ec1821786f509e6b4/pydantic/_internal/_model_construction.py#L116-L117

### Example Code

```Python
from pydantic import BaseModel, PrivateAttr


class Target(BaseModel):
    data: str


class Reference(BaseModel):
    model_config = dict(
        extra="ignore"
    )
    _target: object = PrivateAttr()

    def __getattr__(self, item):
        print(f"getattr {item}")
        if item != "_target":
            return getattr(self._target, item)
        else:
            return getattr(self, item)

    def __setattr__(self, item, value):
        print(f"setattr {item}")
        if item != "_target":
            setattr(self._target, item, value)
        else:
            super().__setattr__(item, value)


r = Reference()
r._target = Target(data='test')
assert r._target.data == "test"
assert hasattr(r, "data")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a4
        pydantic-core version: 0.38.0 release build profile
                 install path: ~/workspace/pydantic/pydantic
               python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
                     platform: Linux-5.19.0-42-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by dmontagu** [comment]
Yep, makes sense, we probably need to make it so that if you have defined a custom getattr it gets used properly. I don't see a super obvious way to do this, I'm thinking maybe the way to do it is — we publicly export the `pydantic._internal._model_construction.model_extra_private_getattr` function so it can be used in overrides, and if you define your own `__getattr__` we don't replace it as you noted.

I don't love it, but I think this is a problem since there's no good escape hatch right now.

@samuelcolvin @adriangb would you have a problem with this suggestion, or a better suggested alternative?

**Comment by commonism** [comment]
Using your input for a workaround I can live with:

```python
from pydantic._internal._model_construction import model_extra_private_getattr

class Reference(BaseModel):
    # …
    _target: object = PrivateAttr()

    def l__getattr__(self, item):
        if item != "_target":
            return getattr(self._target, item)
        else:
            return model_extra_private_getattr(self, '_target')
            
Reference.__getattr__ = Reference.l__getattr__
```

**Comment by commonism** [comment]
Works for me.
And I actually prefer it.
