### ISSUE TITLE
Support for Python 3.11 typing.Self type

### ISSUE THREAD

**Issue by meetinger** [pydantic/pydantic#5992]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

A new type Self was introduced in PEP 673, but now Pydantic does not support it.
This can be useful, for example, for tree structures.

The code below causes an error `RuntimeError: error checking inheritance of typing.Self (type: Self)`.

```Python
from typing import Self
from pydantic import BaseModel


class SelfRef(BaseModel):
    idx: int
    children: list[Self, ...] | None


def main():
    children = [SelfRef(idx=1, children=None), SelfRef(idx=1, children=None)]
    instance = SelfRef(idx=0, children=children)


if __name__ == '__main__':
    main()
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Good idea, I'd been keen to support `Self` as a type annotation in V2.

We should support both `typing.Self` and `typing_extensions.Self` - shouldn't be too hard as we already support building a core schema for forward refs to the current model.

**Comment by adriangb** [comment]
I just want to point out that to do this correctly we’ll have to handle subclasses. That is:

```python
class Model(BaseModel):
    x: Self | None = None

class SubModel(Model):
    pass

Model(x=Model())
Model(x=SubModel())
SubModel(x=SubModel())
SubModel(x=Model())  # error
```

**Comment by rishacha** [comment]
I have 2 queries -
1. What's the solution for this if I have a recursive model being used in a project?
1. Can I help/get involved with the implementation in any way?

**Comment by rishacha** [comment]
src\acceleratorkms\model\import_api\document_item_model.py:18: in <module>
    class DocumentItemModel(BaseModel):
.venv\Lib\site-packages\pydantic\_internal\_model_construction.py:178: in __new__
    complete_model_class(
.venv\Lib\site-packages\pydantic\_internal\_model_construction.py:468: in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
.venv\Lib\site-packages\pydantic\main.py:557: in __get_pydantic_core_schema__
    return __handler(__source)
.venv\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py:82: in __call__
    schema = self._handler(__source_type)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:448: in generate_schema
    schema = self._generate_schema(obj)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:689: in _generate_schema
    return self._model_schema(obj)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:519: in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:519: in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:853: in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:905: in _common_field_schema
    schema = self._apply_annotations(
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:1610: in _apply_annotations
    schema = get_inner_schema(source_type)
.venv\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py:82: in __call__
    schema = self._handler(__source_type)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:1574: in inner_handler
    schema = self._generate_schema(obj)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:694: in _generate_schema
    return self.match_type(obj)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:777: in match_type
    return self._match_generic_type(obj, origin)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:801: in _match_generic_type
    return self._union_schema(obj)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:988: in _union_schema
    choices.append(self.generate_schema(arg))
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:440: in generate_schema
    schema = self._generate_schema_from_prepare_annotations(obj)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:553: in _generate_schema_from_prepare_annotations
    return self._apply_annotations(
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:1610: in _apply_annotations
    schema = get_inner_schema(source_type)
.venv\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py:82: in __call__
    schema = self._handler(__source_type)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:1703: in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
.venv\Lib\site-packages\pydantic\_internal\_std_types_schema.py:308: in __get_pydantic_core_schema__
    items_schema = handler.generate_schema(self.item_source_type)
.venv\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py:96: in generate_schema
    return self._generate_schema.generate_schema(__source_type)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:448: in generate_schema
    schema = self._generate_schema(obj)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:694: in _generate_schema
    return self.match_type(obj)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:781: in match_type
    return self._unknown_type_schema(obj)
.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py:377: in _unknown_type_schema
    raise PydanticSchemaGenerationError(
E   pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for typing.Self. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
E  
E   If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
E  
E   For further information visit https://errors.pydantic.dev/2.3/u/schema-for-unknown-type

**Comment by samuelcolvin** [comment]
> But I am trying to investigate why typing.Self fails.

Because no one has done the work to support it yet.

Feel free to submit a PR, but I suspect it's not that easy.
