### ISSUE TITLE
Pyright (VS code) chokes on typing_extensions.TypeAlias

### ISSUE THREAD

**Issue by RS-Credentive** [pydantic/pydantic#6449]
https://github.com/pydantic/pydantic/blob/ac61c071822d7418f1bab2450e8b2ab0438b2f84/pydantic/main.py#L50

I am overriding default model_dump_json in a custom model class to include indentation, exclude null values, and always use alias.

```
    def model_dump_json(
        self,
        *,
        indent: int | None = 4,
        include: IncEx = None,
        exclude: IncEx = None,
        by_alias: bool = True,
        exclude_unset: bool = False,
        exclude_defaults: bool = False,
        exclude_none: bool = True,
        round_trip: bool = False,
        warnings: bool = True,
    ) -> str:
        return super().model_dump_json(
            indent=indent,
            include=include,
            exclude=exclude,
            by_alias=by_alias,
            exclude_unset=exclude_unset,
            exclude_defaults=exclude_defaults,
            exclude_none=exclude_none,
            round_trip=round_trip,
            warnings=warnings,
        )
```

As is, I get the following warning from VS code: 

"IncEx" is not definedPylance[reportUndefinedVariable](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUndefinedVariable)
(function) IncEx: Unknown

The code executes normally when run by the interpreter - it's just an IDE issue.

I can get rid of this warning by adding the following code at the top of my file:

```
import typing

IncEx: typing.TypeAlias = (
    "set[int] | set[str] | dict[int, IncEx] | dict[str, IncEx] | None"
)
```

I've noticed that the existing code uses "typing_extensions" rather than "typing" for this alias, even though it uses "typing" for everything else in the block. I'm not sure if this is intentional, or an error. 

Selected Assignee: @adriangb

**Comment by Viicos** [comment]
Pylance can't know about the `IncEx` type if it is not imported and thus not present in your current module.

Unfortunately, `IncEx` is defined in a `if TYPE_CHECKING` block, meaning everything enclosed in this block will not be available at runtime. So to be able to import it and make it available to the type checker/IDE:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pydantic.main import IncEx


class YourModel(BaseModel):
    def model_dump_json(
        self,
        *,
        indent: int | None = 4,
        include: IncEx = None,
        exclude: IncEx = None,
        ...
```

More info is available here: https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING

Regarding [`typing_extensions`](https://github.com/python/typing_extensions), it is a module which contains backports of the new typing related Python features, so that they can be used in older versions of the language (e.g. [`TypeAlias`](https://docs.python.org/3/library/typing.html#typing.TypeAlias) was introduced in 3.10).

So using `typing_extensions` or `typing` is equivalent (except in some edge cases).

**Comment by adriangb** [comment]
> Unfortunately, IncEx is defined in a if TYPE_CHECKING block, meaning everything enclosed in this block will not be available at runtime. So to be able to import it and make it available to the type checker/IDE:

This is right, thank you for looking into this @Viicos. I don't know that I'd call it "unfortunate": the rationale for doing this is that these types aren't needed at runtime, so we can put them in a `TYPE_CHECKING` block to avoid executing them when the module is imported, reducing import time and consequently startup time for a FastAPI app, etc.

@RS-Credentive if this solved your problem please go ahead and close this issue

**Comment by Viicos** [comment]
> I don't know that I'd call it "unfortunate"
I wouldn't either, started my sentence thinking there was no way at all to import `IncEx`, but then remembered you could still enclose the `import` statement in a `if TYPE_CHECKING` block as well 😅

**Comment by RS-Credentive** [comment]
Thanks for the informative response. This has addressed my issue.
