### ISSUE TITLE
datetime field with different coercion in Pydantic v2

### ISSUE THREAD

**Issue by leandrodamascena** [pydantic/pydantic#6518]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

First, thank you so much for working so hard on this update, the Pydantic project is fantastic.

I'm working on migrating (https://github.com/aws-powertools/powertools-lambda-python/issues/2672) Pydantic models from v1 to v2 and I've noticed that `datetime` field is coercing unix timestamp/epoch values to a different format than v1. In v1 it adds the offset, which is UTC by default, but in v2 it doesn't add and it's breaking my tests.

Not sure if this behavior is expected in v2 or if it's a bug. Reading the [UnixTime](https://en.wikipedia.org/wiki/Unix_time) definition it looks like it should add the +00:00 offset since it's UTC by default.

Below I have the execution in Pydantic v1 and v2 to see the different behaviors.

### Example Code

**CODE**
```Python
from datetime import datetime

from pydantic import BaseModel
import pydantic


class Model(BaseModel):
    datefield: datetime

epoch_time = 1688683243050

m = Model(
    datefield=epoch_time
)

print(f"Pydantic version -> {pydantic.__version__}")
print(f"Raw epoch time -> {epoch_time}")
print(f"Raw pydantic field -> {m.datefield}")
print(f"Pydantic converted epoch time -> {int(round(m.datefield.timestamp() * 1000))}")
```

**V1 OUTPUT**
```sh
❯ python pydantic_example.py 
Pydantic version -> 1.10.11
Raw epoch time -> 1688683243050
Raw pydantic field -> 2023-07-06 22:40:43.050000+00:00
Pydantic converted epoch time -> 1688683243050
```

**V2 OUTPUT**
```sh
❯ python pydantic_example.py
Pydantic version -> 2.0.2
Raw epoch time -> 1688683243050
Raw pydantic field -> 2023-07-06 22:40:43.050000
Pydantic converted epoch time -> 1688679643050
```
```


### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"

             pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /home/leandro/.local/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
                     platform: Linux-5.14.10-300.fc35.x86_64-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by samuelcolvin** [comment]
Humm I can see it both ways - there's no explicit timezone with a unix time stamp, hence I changed it to be timezone naive.

Then again, I agree looking at the Wikipedia link that it should be UTC+0.

I think I also made it this way to match `datetime.utcfromtimestamp`.

I'm not sure about reverting the change since technically it would be a breaking change.

We can probably add a way to add an annotation to set the timezone.

**Comment by leandrodamascena** [comment]
Hei @samuelcolvin! Thank you for the reply and explanation. 

>I'm not sure about reverting the change since technically it would be a breaking change.

Yeah, I agree with that and I think you should not break things in v2.

> We can probably add a way to add an annotation to set the timezone.

That would be a big help, man! This would reduce the boilerplate code by adding a way to set the timezone in the `datetime` field and the same behavior as Pydantic V1.

For now, I've solved this problem by doing the following:
https://github.com/aws-powertools/powertools-lambda-python/blob/poc/pydanticv2/aws_lambda_powertools/utilities/parser/models/apigwv2.py#L59

```python
# validator to normalize timestamp
@validator("timeEpoch", pre=True)
def normalize_timestamp(cls, value):
    date_utc = datetime.fromtimestamp(int(value) / 1000, tz=timezone.utc)
    return date_utc
```

**Comment by zyv** [comment]
So we have exactly the same problem here. We use YouTrack API, which transports `datetime`s as Unix timestamps and just at the AWS people, they assume that Unix time by definition is Zulu time.

In Pydantic V1 the conversion was working correctly (in a sense that it returned aware timestamps with UTC timezone), but in Pydantic V2 we get naive `datetime`s.

> I'm not sure about reverting the change since technically it would be a breaking change.

Well, was it a conscious documented decision to handle Unix timestamps differently (as naive) in Pydantic V2? Otherwise I would argue that it's actually a bugfix.

At least I can't find anything here:

https://docs.pydantic.dev/latest/usage/types/datetime/#validation-of-datetime-types

... or in the migration guide / changelog.

Of course, adding a way to annotate would solve the problem, but forcing everybody to annotate when it seems that the commonly accepted and used interpretation of Unix timestamp in the most popular APIs is UTC feels like creating a burden for the users, where a different default behaviour actually makes more sense.

Are there any other major APIs that mean local time with Unix time?

**Comment by samuelcolvin** [comment]
Okay, thanks everyone. Decision made - let's call the current behaviour a bug and revert V1 behaviour that unix timestamps get converted to a `datetime` with a UTC timezone.

**Comment by leandrodamascena** [comment]
Good to hear that @samuelcolvin! Do you have an expected release date for the new version with this fix?

**Comment by samuelcolvin** [comment]
Hopefully this week.

**Comment by samuelcolvin** [comment]
requires https://github.com/pydantic/speedate/issues/41

**Comment by samuelcolvin** [comment]
@adriangb can you fix as you're familiar with speedate.

**Comment by adriangb** [comment]
Sure will work on this

**Comment by zyv** [comment]
Is it a way for us know whether this made it in v2.0.3? Thanks!

**Comment by adriangb** [comment]
It did!

**Comment by YraganTron** [comment]
I keep experiencing the same problem in version 2.5.2. Have you decided not to correct this behavior? Or should I track this issue elsewhere?

**Comment by SuperThinking** [comment]
To be backwards compatible, I am doing this for now
```python
from datetime import datetime
from pydantic import BaseModel


class LegacyDateTimeEncoder:
    def encode_datetime(self, dt: datetime) -> str:
        if dt.tzinfo is not None:
            # Convert 'Z' back to '+00:00' for UTC
            dt_str = dt.isoformat()
            if dt_str.endswith('Z'):
                return dt_str[:-1] + '+00:00'
        return dt.isoformat()


# Base model that maintains Pydantic v1 datetime serialization format
# Pydantic v2 changed UTC timezone serialization from '+00:00' to 'Z'
# This class ensures backward compatibility with existing clients and services
# that expect the v1 format
class ModelWithLegacyDateTime(BaseModel):
    class Config:
        json_encoders = {datetime: LegacyDateTimeEncoder().encode_datetime}
```

then in my pydantic schemas (which are impacted) instead of inheriting BaseModel, I am doing

```python
class X(ModelWithLegacyDateTime):
    a: datetime
```
New ones will be using the new datetime format, old ones will keep working.
