### ISSUE TITLE
ImportError: cannot import name 'MultiHostDsn' from 'pydantic.networks'

### ISSUE THREAD

**Issue by KyriakiGeorgiou** [pydantic/pydantic#6578]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am using gradio to dispaly my NLP model. On Friday it was working perfectly, but after the new release (gradio v3.36.1 and pydantic v2.02 or any other I use) whenever I run any code with the gradio import I get the following error: "[/usr/local/lib/python3.10/dist-packages/fastapi/_compat.py](https://localhost:8080/#) in <module>
    295         UndefinedType as UndefinedType,  # noqa: F401
    296     )
--> 297     from pydantic.networks import (  # type: ignore[no-redef]
    298         MultiHostDsn as MultiHostUrl,  # noqa: F401
    299     )

ImportError: cannot import name 'MultiHostDsn' from 'pydantic.networks' (/usr/local/lib/python3.10/dist-packages/pydantic/networks.cpython-310-x86_64-linux-gnu.so)". Even when I run the code with a simple example like the following and no extra imports I still get the same error.

### Example Code

```Python
import pydantic
import gradio as gr
def sketch_recognition(img):
    pass# Implement your sketch recognition model here...

gr.Interface(fn=sketch_recognition, inputs="sketchpad", outputs="label").launch()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /usr/local/lib/python3.10/dist-packages/pydantic
               python version: 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]
                     platform: Linux-5.15.107+-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by lig** [comment]
@KyriakiGeorgiou Hello! What version of `gradio` are you using? As far as I can see, [Gradio v3.36.1](https://github.com/gradio-app/gradio/releases/tag/v3.36.1) should have Pydantic V2 supported.

If the error persist after upgrading to the latest `gradio` version, please report it to the [Gradio Bug Tracker](https://github.com/gradio-app/gradio/issues).

**Comment by KyriakiGeorgiou** [comment]
Hello! I am using v3.36.1 and the error persists. I will report it to Gradio as well. Thank you!

**Comment by hellc** [comment]
Force typing_extensions==4.5.0 to lower version

**Comment by KyriakiGeorgiou** [comment]
It is still causing the same error after forcing typing_extensions from 4.7.1 to 4.5.0.

**Comment by lig** [comment]
@KyriakiGeorgiou Have you reported the issue to `gradio`?

**Comment by lig** [comment]
Also, see https://github.com/tiangolo/fastapi/pull/9852

**Comment by amir32** [comment]
Sure, here's a comment that addresses the issue and also includes a link to your website:

---

Hi @KyriakiGeorgiou,

I noticed that you're encountering an issue related to an ImportError with Pydantic in your Gradio project. Based on the error message you provided, it seems to be related to the recent releases of Gradio (v3.36.1) and Pydantic (v2.0.2). 

I have a suggestion that might help you resolve this problem. It appears that the 'MultiHostDsn' import from 'pydantic.networks' is causing the issue. You mentioned that you are using Pydantic V2. Starting from Pydantic 2.0.0, some imports and structures have been reorganized, and this could be the cause of the problem.

You might want to try updating your import statement to match the changes in Pydantic 2.0.0 and later versions. Here's how you can modify your code:

```python
import pydantic
from pydantic.networks import MultiHostUrl  # Update the import statement
import gradio as gr

def sketch_recognition(img):
    pass  # Implement your sketch recognition model here...

gr.Interface(fn=sketch_recognition, inputs="sketchpad", outputs="label").launch()
```

This change should help you resolve the ImportError related to 'MultiHostDsn'. Make sure to check if any other parts of your code need adjustments due to Pydantic's updates.

Additionally, I noticed that your website, FusionCalculator (https://fusioncalculator.com), is related to Pokémon fusion. If you have any Pokémon fusion-related questions or need assistance with your fusion calculator, feel free to reach out. Your website sounds interesting, and I'd be happy to check it out for further assistance.

I hope this helps you get back on track with your project! If you have any more questions or need further assistance, please let me know.
[Your Website: FusionCalculator](https://fusioncalculator.com)
