### ISSUE TITLE
class level private attribute no more working.

### ISSUE THREAD

**Issue by lmignon** [pydantic/pydantic#6594]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In python, if you define a class as:

```python
class BoolPrivateAttr:
    _private: bool = False
    name: str

```
The assertion `assert BoolPrivateAttr._private is False` is True

If you do the same with the new version of pydantic with a class inheriting from BaseModel, the assertion is now False

```python

class BoolPrivateModelAttr(BaseModel):
    _private: bool = False
    name: str

```

### Example Code

```Python
from pydantic import BaseModel

class BoolPrivateAttr:
    _private: bool = False
    name: str

class BoolPrivateModelAttr(BaseModel):
    _private: bool = False
    name: str

assert BoolPrivateAttr._private is False
assert BoolPrivateModelAttr._private is False
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /home/lmi/.virtualenvs/extendable-pydantic/lib/python3.8/site-packages/pydantic
               python version: 3.8.17 (default, Jun  6 2023, 20:10:50)  [GCC 11.3.0]
                     platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by Viicos** [comment]
As `BaseModel` uses a metaclass behind the scenes, attributes (such as `_private` and `name` in your example) aren't really set on the class object. You will in fact get an `AttributeError` if you try accessing `BoolPrivateModelAttr.name`. When using Pydantic models on the class level, it's better to use the provided attributes such as `model_fields`, `__private_attributes__`

Then why does accessing a private attribute does not raise an `AttributeError`? The metaclass defines the following `__getattr__` method:

https://github.com/pydantic/pydantic/blob/a2f266a9539abc2611f3958f145af9b51a62de30/pydantic/_internal/_model_construction.py#L188-L199

As you can see trying to access a private attribute such as `_private` works thanks to this method, but it does not evaluate to `False` anymore (because the metaclass did some work to wrap the attribute in a `ModelPrivateAttr`).

I don't know the reason to only support private attribute access through this method, but you can check the [related issues](https://github.com/pydantic/pydantic/issues?q=__getattr__)

**Comment by lmignon** [comment]
But this code code was working well in pydantic V1 and I don't want to have to take care that my class is a subclass of BaseModel of a simple class to know how to access my class level attributes :worried:

**Comment by Viicos** [comment]
Well in fact in V1 `_private` isn't even a private attribute (as `Config.underscore_attrs_are_private = False` by default). It is in fact ignored by Pydantic completely:

```python
class BoolPrivateModelAttr(BaseModel):
    _private: bool = False
    name: str

inst = BoolPrivateModelAttr(_private=True, name="foo")
inst.__fields__  # {'name': ModelField(name='name', type=str, required=True)}
inst.__private_attributes__  # {}
inst._private  # False <-- value set on instantiation ignored!
```

**Comment by Viicos** [comment]
https://docs.pydantic.dev/latest/usage/errors/#model-field-missing-annotation might help

**Comment by dmontagu** [comment]
@lmignon just annotate as a classvar and it will keep working:

```python
from typing import ClassVar
class BoolPrivateAttr:
    _private: ClassVar[bool] = False
    name: str
```

**Comment by lmignon** [comment]
@dmontagu Thank you for the proposal. I find a way to get rid of this specific behavior.

**Comment by Jylpah** [comment]
@lmignon would you mind to share your solution? I stumbled upon the same issue.

**Comment by lmignon** [comment]
@Jylpah I changed my code... but no more remember exactly the change I made since it was one of a lot when migrating from v1 to V2.. Sorry to not be able to help you with more details.
