### ISSUE TITLE
`arbitrary_types_allowed` no longer works with root models in V2

### ISSUE THREAD

**Issue by MarkusSintonen** [pydantic/pydantic#6710]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In V2 root models `arbitrary_types_allowed` no longer works. In V1 it used to work. Is it intended not to work anymore? Example below showing an use case that used to work in V1. I guess the issue is somehow related to generic models handling in V2.

### Example Code

```Python
import numpy

from pydantic import BaseModel

try:
    from pydantic import ConfigDict, RootModel
    PYDANTIC_VERSION = "v2"
except ImportError:
    PYDANTIC_VERSION = "v1"


def test_arbitrary_root():
    if PYDANTIC_VERSION == 'v2':
        # Now it raises suggesting using arbitrary_types_allowed. But it is set!
        # Exception:
        # pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'numpy.ndarray'>.
        # Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
        class MyNdarray(RootModel[numpy.ndarray]):
            model_config = ConfigDict(arbitrary_types_allowed=True)
            # defines deserialization of list to ndarray etc...
    else:
        # In v1 it works fine.
        class MyNdarray(BaseModel):
            __root__: numpy.ndarray

            class Config:
                arbitrary_types_allowed = True

            # defines deserialization of list to ndarray etc...
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /Users/markussintonen/Library/Caches/pypoetry/virtualenvs/leak-test-VvUvdXxD-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun 20 2023, 17:00:24) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by dmontagu** [comment]
@MarkusSintonen while I think ideally this wouldn't error, I think it might be hard to get it to work properly, since it's erroring while trying to create `RootModel[np.ndarray]`, which you are inheriting from. Instead, you can do:
```python
from typing import Any

import numpy

from pydantic import ConfigDict, RootModel


class MyNdarray(RootModel[Any]):
    root: numpy.ndarray
    model_config = ConfigDict(arbitrary_types_allowed=True)
    # defines deserialization of list to ndarray etc...
```

I was worried this might not give the right mypy behavior, but I wasn't able to produce any typing issues using the above.

I'd be open to PRs fixing it for `RootModel` but I don't think the right answer is to make `arbitrary_types_allowed=True` for `RootModel` by default, and I don't see another good way to achieve this.

Open to debate/other ideas

**Comment by lig** [comment]
@dmontagu I think that both forms should work identical in general despite what type is being used for `RootModel`.

```py
class MyNdarray(RootModel[numpy.ndarray]):
    model_config = ConfigDict(arbitrary_types_allowed=True)
```

and

```py
class MyNdarray(RootModel):
    root = numpy.ndarray
    model_config = ConfigDict(arbitrary_types_allowed=True)
```

I agree that `arbitrary_types_allowed` shouldn't be `True` by default.

I will focus in this issue just on making `arbitrary_types_allowed=True` work as expected.

**Comment by lig** [comment]
After thorough review of this issue I'm tempting to call this known behavior and add a note regarding this to the docs.

The issue here is that `RootModel[numpy.ndarray]` creates a specialized subclass of `RootModel` that could be used as a full functional model already. Two code examples below produce mostly identical results.

```py
class Model(RootModel):
    root: numpy.ndarray 
```
and 

```py
Model = RootModel[numpy.ndarray]
```

When creating a `RootModel` subclass explicitly we can set `model_config` for it and when creating using an implicit subclass as in `RootModel[numpy.ndarray]` we cannot.

This means that in the code below we attempt creating a `RootModel` subclass without `model_config` defined before setting `model_config` for `MyNdarray`.

```py
class MyNdarray(RootModel[numpy.ndarray]):
    model_config = ConfigDict(arbitrary_types_allowed=True)
```
