### ISSUE TITLE
Use name instead of alias when populate_by_name=True in GenerateJsonSchema

### ISSUE THREAD

**Issue by rbuffat** [pydantic/pydantic#6782]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm not sure if this is a bug or a feature request.  I'm using pydantic together with fastapi.  With the following model

```
class MyData(BaseModel):
    """Model representing data sent by an update from an Torqeedo Bluetooth App"""

    model_config = ConfigDict(alias_generator=lambda x: f"prefix_{x}", populate_by_name=True)

    data1: float | None = None
    data2: float | None = None
```
Fastapi generates a schema resulting in `prefix_data1` and `prefix_data2` using the `GenerateJsonSchema` class of pydantic.  However, as as `populate_by_name=True` was set,  I expected the schema to contain `data1` and `data2`.  

[Pydantic's JSON generator supports the by_alias option](https://github.com/pydantic/pydantic/blob/ff1e58064aa14af411defb3611352bc481307e0b/pydantic/json_schema.py#L207-L238).   Would it make sense to add an additional option, such as `respect_populate_by_name` that when a model has `populate_by_name=True`  configured will use the name instead of the alias for this model?

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /home/worker/.local/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jul  4 2023, 05:51:40) [GCC 10.2.1 20210110]
                     platform: Linux-6.4.3-arch1-2-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by dmontagu** [comment]
In the absence of significant interest, I would be somewhat opposed to adding another flag to JSON schema generation like this, just because historically every additional option has added a significant maintenance burden.

That said, I think there are some things we could do to make it easier for users to accomplish this.

I think to support this, you'd need to implement the same config-stack thing I suggested in https://github.com/pydantic/pydantic/issues/6775#issuecomment-1649898963. I suspect this will get implemented at some point soon just because it's been relevant to multiple issues now.

Once you have that, you could just override `pydantic.json_schema.GenerateJsonSchema._named_required_fields_schema` to change this logic:
```python
            if self.by_alias:
                name = self._get_alias_name(field, name)
```
to something like:
```python
            if self.by_alias and not self.config_stack[-1].populate_by_name:
                name = self._get_alias_name(field, name)
```
This method is currently private, but that won't stop you from overriding it (just means that we don't promise not to tweak it in the future). But we currently have no intent to change things.

**Comment by sydney-runkle** [comment]
Closing this under the umbrella of https://github.com/pydantic/pydantic/issues/8379, which will be addressed with V3 👍
