### ISSUE TITLE
Unexpected change in the behavior of BaseModel.__dict__?

### ISSUE THREAD

**Issue by noddycode** [pydantic/pydantic#6914]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I was scratching my head over this one for a while today after updating from v1.5.x to v2.1.0. I was previously using `BaseModel.__dict__` to iterate through the fields of a model and ran into an issue where extra fields were not showing up in the output as expected (simplified example below).

I'm not sure that `__dict__` was ever really a covered/official way to iterate over model data compared to `dict()`, but I was wondering if it was worth noting in the breaking changes/migration guide in the docs?

### Example Code

```Python
from pydantic import BaseModel, ConfigDict

class MyModel(BaseModel):
    model_config = ConfigDict(extra='allow')

    str_field: str = "Hello!"

model = MyModel(str_field="Hey there", extra_field="I'm extra!")
model.another_extra_field = "I'm extra, too!"

print(model.model_dump())
# {'str_field': 'Hey there', 'extra_field': "I'm extra!", 'another_extra_field': "I'm extra, too!"}
print(dict(model))
# {'str_field': 'Hey there', 'extra_field': "I'm extra!", 'another_extra_field': "I'm extra, too!"}
print(model.dict())
# {'str_field': 'Hey there', 'extra_field': "I'm extra!", 'another_extra_field': "I'm extra, too!"}
print(model.__dict__)
# {'str_field': 'Hey there'}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
pydantic-core version: 2.4.0
pydantic-core build: profile=release pgo=false      mimalloc=true
install path: <LOCAL_VENV>
python version: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
platform: Windows-10-10.0.19044-SP0
optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by dmontagu** [comment]
This was an intentional change, as we now store extra fields in `__pydantic_extra__` (and private attributes in `__pydantic_private__`) — I can't remember why this was necessary, but I suspect it was tied into subtleties of validation/serialization performance for models without extra, since being able to assume that all field values are stored in `__dict__` lets you do certain things faster.

PR welcome to update the migration guide / docs about this, in general though I would probably try to avoid depending on the contents of the model's `__dict__` attribute if possible, I'm not sure I'd consider that part of the public API of BaseModel.

**Comment by noddycode** [comment]
Yeah, I'm using `model.model_dump` now to achieve the desired affect, I'm not sure there was a particular reason I was using `__dict__` instead of `.dict()` in the first place. I'll try to make up a PR this weekend to update the docs if I have time.
