### ISSUE TITLE
No module named 'pydantic_core._pydantic_core' using AWS Lambdas 3.11

### ISSUE THREAD

**Issue by jordancparker** [pydantic/pydantic#6990]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi,

Upgrading to fastapi ==0.100.1,

Using Pipenv:

fastapi ==0.100.1,
pydantic ==2.1.1,
pydantic-core ==2.4.0
AWS Lambda Python 3.11 x86_64.

Error Messsage:
errorMessage": "Unable to import module 'main': No module named 'pydantic_core._pydantic_core'"

Reverting back to 0.99.1 resolves the issues, so its not an architecture type miss match.

Could it be Mac OS binary vs Linux Binary. But its strange that the 0.99.1 package does not work the same way as the 0.100.1 package with the core change being pydantic V2. 

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
pydantic-core version: 2.4.0
pydantic-core build: profile=release pgo=false mimalloc=true
platform: x86_64-i386-64bit
```

Selected Assignee: @adriangb

**Comment by adriangb** [comment]
We can't offer support for cloud provider-specific issues, CI misconfiguration, etc. I'm guessing the dependency is missing because the python version or architecture you used to build your lambda image / zip file doesn't match your runtime environment but beyond that you'll have to ask AWS or some other avenue for support.

**Comment by samuelcolvin** [comment]
Duplicate of #6557.
