### ISSUE TITLE
Recursion error when attempting to build a model with a recursive TypedDict as a field

### ISSUE THREAD

**Issue by lukaskiss222** [pydantic/pydantic#7016]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Hi, I was using normally pydantic with web3 (6.5) type ABI, until they updated implementation of **ABIFunctionComponents** **components** as recursive **Sequence** in (web3 6.7).

We can replicate the issue without their library, with just simple **TypedDict**.

### Example Code

```Python
import pydandic as py

from typing import TypedDict, Sequence

class ABIFunctionComponents(TypedDict, total=False):
    components: Sequence["ABIFunctionComponents"]

# pydantic class
class EnvConfig(py.BaseModel, frozen=True, extra=py.Extra.allow):
    test: ABIFunctionComponents

# RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.12
            pydantic compiled: True
                 install path: /Users/lukas/Library/Caches/pypoetry/virtualenvs/market-service-tZ_a9jQS-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 20 2023, 16:59:59) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @dmontagu

**Comment by dmontagu** [comment]
I believe this is an issue with all recursive `dataclass` and `TypedDict` classes in pydantic v1.

I think this is likely to be a won't-fix in v1 given how involved I think the solution would need to be — since we build basemodels to validate these types in v1, we would need to significantly change/complexify the way that works to be compatible with recursive types.

However, I will note that this is already fixed in v2 and behaves correctly there.

I would be happy to review a PR if someone puts in the effort to fix this, but because recursive types that aren't BaseModel's don't work properly at all in v1 (as far as I can tell anyway; happy to be corrected on that if I'm wrong), I think this qualifies more as a feature request than a bugfix.

That said, I'd be amenable to working on an update to pydantic v1 to give a better error message for such recursive types if there is enough interest.

**Comment by adriangb** [comment]
Agreed with what David said. I'm closing this issue to keep our backlog tidy but if someone wants to work on this for v1 please comment here and we can re-open.
