### ISSUE TITLE
mypy v1.5 raises error when calling `dataclasses.replace` on Pydantic dataclass

### ISSUE THREAD

**Issue by sisp** [pydantic/pydantic#7075]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Running the sample code below with mypy 1.5 yields an error

```
test.py:13: error: Argument 1 to "replace" has incompatible type "A"; expected a dataclass  [misc]
Found 1 error in 1 file (checked 1 source file)
```

while mypy <1.5 (e.g. 1.4.1) is happy:

```
Success: no issues found in 1 source file
```

I'm not 100% sure whether this is a Pydantic or mypy issue. See [mypy's changelog for the 1.5 release](https://mypy-lang.blogspot.com/2023/08/mypy-15-released.html), in particular the section "Improvements to Dataclasses" and the first list item which seems to be the one that introduced the change in behavior. Perhaps Pydantic needs to make its own dataclass look more like a vanilla dataclass? :shrug:

### Example Code

```Python
from dataclasses import replace

from pydantic.dataclasses import dataclass


@dataclass
class A:
    x: int


a1 = A(x=1)
a2 = replace(a1, x=2)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: .../.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 (main, Sep  2 2022, 22:36:50)  [GCC 9.4.0]
                     platform: Linux-5.13.0-48-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
Thansk @sisp for reporting this 🙏 

I can confirm the problem. 

@dmontagu Do you have any idea here?

**Comment by dmontagu** [comment]
I was able to trace down the current logic in the mypy dataclasses plugin, and it looks like the _only_ way to get a type that can be used as the first argument to the `dataclasses.replace` function is to use the `dataclasses.dataclass` decorator. My evidence of that:
* This is where the mypy error is emitted: https://github.com/python/mypy/blob/11a94be6f408d5bce391a1ec3931ce7197ca207b/mypy/plugins/dataclasses.py#L975 (in `_fail_not_dataclass`)
* To hit that error, that function will be called here: https://github.com/python/mypy/blob/11a94be6f408d5bce391a1ec3931ce7197ca207b/mypy/plugins/dataclasses.py#L1015, and this call happens if and only if `typ.type.get_method(_INTERNAL_REPLACE_SYM_NAME)` returns `None`.
* The only place where `_INTERNAL_REPLACE_SYM_NAME` is used is in [`mypy.plugins.dataclasses.DataclassTransformer._add_internal_replace_method`](https://github.com/python/mypy/blob/11a94be6f408d5bce391a1ec3931ce7197ca207b/mypy/plugins/dataclasses.py#L391), which happens only if [`self._spec is _TRANSFORM_SPEC_FOR_DATACLASSES`](https://github.com/python/mypy/blob/11a94be6f408d5bce391a1ec3931ce7197ca207b/mypy/plugins/dataclasses.py#L379).
* The only way to get `_TRANSFORM_SPEC_FOR_DATACLASSES` is to use precisely the dataclass decorator, as you can see looking [here](https://github.com/python/mypy/blob/11a94be6f408d5bce391a1ec3931ce7197ca207b/mypy/plugins/dataclasses.py#L943-L944), [here](https://github.com/python/mypy/blob/11a94be6f408d5bce391a1ec3931ce7197ca207b/mypy/plugins/dataclasses.py#L958), and [here](https://github.com/python/mypy/blob/11a94be6f408d5bce391a1ec3931ce7197ca207b/mypy/plugins/dataclasses.py#L77).

I think it would be nice if mypy provided some way for other decorators to indicate that they return dataclasses compatible with `replace`, or at least to provide a suggestion for how to achieve compatibility when using custom decorators that do return actual dataclasses.

It might be nice if any class decorated with a `@dataclass_transform` decorator could be passed as an input to the `dataclasses.replace` function, but I do see arguments against that (as not every class decorated with that decorator will necessarily be compatible with `dataclasses.replace`, just, I think there's an argument to be made that it's more helpful than not). I'm definitely open to alternatives though if they exist.

I think the next step is to create an issue on the mypy repo asking for advice (and possibly linking this comment, which I hope clearly explains the issue).

----

Given that mypy is explicitly checking for usage of the `@dataclasses.dataclass`, the only real workaround I can imagine is to lie to mypy about where the decorator came from using `typing.TYPE_CHECKING`:

```python
from dataclasses import replace

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass


@dataclass
class A:
    x: int


a1 = A(x=1)
a2 = replace(a1, x=2)
```
Even if you want to use a specific pydantic config for the pydantic dataclasses, you could potentially do something like:
```python
from dataclasses import replace

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass as pydantic_dataclass
    dataclass = pydantic_dataclass(config={<...>})


@dataclass
class A:
    x: int


a1 = A(x=1)
a2 = replace(a1, x=2)
```

Sadly this will mean that you won't get type-checking of the config in the `if not TYPE_CHECKING:` branch, but you could maybe do something like this to still get most of the benefits:
```python
from pydantic import ConfigDict
pydantic_dataclass_config = ConfigDict(<...>)  # this will ensure the config is type-checked

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass as pydantic_dataclass
    dataclass = pydantic_dataclass(config=pydantic_dataclass_config)
```

**Comment by sisp** [comment]
Great analysis, @dmontagu! :pray:

Pydantic could offer its own `replace` function which would merely be an alias of the original function with a modified type signature to accept Pydantic's dataclass instance. But I'd also prefer using the original `replace` function as before.

**Comment by dmontagu** [comment]
@sisp while it's true we could offer our own replace function, you'd _have_ to use the pydantic mypy plugin to have it work (and we'd have to make sure that was handled in the pydantic mypy plugin, though I think that wouldn't be super hard, more time consuming than hard).

That said, I'd rather hear what mypy has to say about it before implementing anything, since if they are willing to modify the way the `dataclasses.replace` function type checks the first argument, it will work for everyone (even those not using the pydantic plugin) without any pydantic-specific implementation work.

**Comment by yajo** [comment]
> I'd rather hear what mypy has to say about it before implementing anything in pydantic

Where's the issue for mypy then?

**Comment by Viicos** [comment]
Currently works as expected on the latest version of mypy.
