### ISSUE TITLE
Support new union syntax for python versions older than 3.10

### ISSUE THREAD

**Issue by kraktus** [pydantic/pydantic#7109]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

The following snippet raises an exception on python versions 3.7, 3.8 and 3.9, despite being the versions being supported by pydantic, because of using the new union syntax for type hint.

```py3
from __future__ import annotations

from pydantic import TypeAdapter

class Obj(TypedDict):
    id: str | int
    
def validate(t, value):
    return TypeAdapter(t).validate_python(value, strict=True)

validate(Obj, {"id": 3})
```

I'd have expected pydantic to convert the type to `Union[str, int]` before evaluating the type field.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [x] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @dmontagu

**Comment by dmontagu** [comment]
I don't see a good way to address this because pydantic needs to analyze the type hint in order to generate a validator.

Even though it has `from __future__ import annotations`, you should consider annotations to be code that needs to be able to be evaluated at runtime if you are using it as the annotation of a pydantic field, as that's ultimately a requirement for pydantic to determine what the validation logic should be for the field.

If you want your code to be compatible with older versions of python, you should just use `typing.Union` rather than the `|` operator between types.

I'm going to close this as won't-fix, as I don't think we are going to backport logic to handle the `|` operator in older versions of python, but would be open to non-invasive PRs that could fix this, I just suspect it won't be easy/possible to do.
