### ISSUE TITLE
Unable to use Field discriminator with ClassVar fields

### ISSUE THREAD

**Issue by Rubikoid** [pydantic/pydantic#7179]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Unable to use as discriminator for discriminated union field, described with ClassVar

### Example Code

```Python
from typing import Annotated, ClassVar, Literal
from pydantic import BaseModel, Field

class Base(BaseModel):
    classtype: ClassVar[Literal["base"]] = "base"

class Cat(Base):
    classtype: ClassVar[Literal["cat"]] = "cat"

class Dog(Base):
    classtype: ClassVar[Literal["dog"]] = "dog"

class Human(BaseModel):
    pet: Annotated[Cat | Dog, Field(discriminator="classtype")]

# pydantic.errors.PydanticUserError: Model 'Cat' needs a discriminator field for key 'classtype'
```

### Python, Pydantic & OS Version

```Text
                pydantic version: 2.2.1
        pydantic-core version: 2.6.1
          pydantic-core build: profile=release pgo=false
                 install path: .\.venv\Lib\site-packages\pydantic
               python version: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by dmontagu** [comment]
Can you describe more how you are trying to use this? Because classvars are not validated for instances, I'm not sure how you'd use it for the sake of discriminating during validation.

**Comment by Rubikoid** [comment]
> Because classvars are not validated for instances

Sounds logically, sounds like this is my fault.

Initially, I want to do something like
```Python
def get_pet_classtype(pet_type: type[Base]) -> str:
    return pet_type.classtype
```

but because `classtype` was not `ClassVar`, I'm unable to access it from class object.

**Comment by dmontagu** [comment]
Does this work for you?
```python
from typing import Annotated, ClassVar, Literal
from pydantic import BaseModel, Field

class Base(BaseModel):
    classtype: Literal["base"] = "base"

class Cat(Base):
    classtype: Literal["cat"] = "cat"

class Dog(Base):
    classtype: Literal["dog"] = "dog"

class Human(BaseModel):
    pet: Annotated[Cat | Dog, Field(discriminator="classtype")]


def get_pet_classtype(pet_type: type[Base]) -> str:
    return pet_type.model_fields['classtype'].default

print(get_pet_classtype(Base))
#> base
print(get_pet_classtype(Cat))
#> cat
print(get_pet_classtype(Dog))
#> dog
```

**Comment by Rubikoid** [comment]
Yes, everything good, thanks!

**Comment by glopesdev** [comment]
@Viicos @dmontagu although the proposed solution resolved the specific problem of @Rubikoid, I don't think it resolved the ask as it was framed, as we still cannot use `ClassVar` as a discriminator field.

There are a number of advantages of using `ClassVar[str] = "cat"` over `Literal["cat"] = "cat"`, including:
  - not having to type the actual constant twice
  - no need to be constrained to literal-types
  - working nicer with different type hinting checkers (some versions of particular checkers have been reported to complain that you cannot override `Literal["base"]` with `Literal["cat"]`, as the type hint will be considered different

Because of this I still think having the ability to use a `ClassVar` field as a discriminator would be preferrable. Can we reopen this issue, or shall I start a new one?

**Comment by Viicos** [comment]
@glopesdev Pydantic needs the discriminator value to be provided during validation to be able to know which model it corresponds to.

With the following:

```python
class Cat(Base):
    classtype: ClassVar[Literal["cat"]] = "cat"
    age: int

class Dog(Base):
    classtype: ClassVar[Literal["dog"]] = "dog"
    age: int

class Human(BaseModel):
    pet: Annotated[Cat | Dog, Field(discriminator="classtype")]
```

How do you expect validation to work?:

```python
Human.model_validate({'pet': {'age': 1}})
Human.pet  # Cat? Dog?
```

**Comment by glopesdev** [comment]
@Viicos You are right, `ClassVar` does not make it at all into the schema, I must have fumbled my tests somewhere with a previous cache.

The issues with using `Literal[T]` remain, though: there is still no way to use non-literal types, and in many type checkers you get a mismatch between base classes and derived classes during type checking, forcing you to either declare `Any` or ignore.

It would be great to have an annotation essentially equivalent to `ClassVar[str] = "cat"` which would not be mapped to a `Literal` but instead would map to the equivalent pydantic v1 constant fields, e.g. `Constant[str] = "cat"` would be the same as `str = Field(const=True, default="cat")` so we could have:
  - no duplication of constants
  - consistent type hinting
  - work with non-literal types

If there is no existing alternative to obtain this, I might open a new issue to propose it.

**Comment by Viicos** [comment]
> and in many type checkers you get a mismatch between base classes and derived classes during type checking, forcing you to either declare `Any` or ignore.

Do you have a specific example showing the type checker error? I'm not sure I get what you mean.

**Comment by glopesdev** [comment]
@Viicos the example provided in https://github.com/pydantic/pydantic/issues/7179#issuecomment-1684482245 will fail in many type checkers, since strictly speaking you are changing the type annotation of `classtype`.

The main issue is that the string literal itself is embedded into the type annotation.

There seems to be a tension here between using discriminators to represent polymorphic types (discriminator field needs to change by definition to indicate the type) and subclass types hinting where fields should only be overridden by fields of the same type.

Of course, we know these are all strings, so it just feels more correct to say that `classtype` is a field of type `str` that happens to be defined in each subtype as a constant immutable value.

**Comment by Viicos** [comment]
> There seems to be a tension here between using discriminators to represent polymorphic types (discriminator field needs to change by definition to indicate the type) and subclass types hinting where fields should only be overridden by fields of the same type.

Is `Base` meant to be a concrete class? There are a couple options available here:

- `Base` is abstract, in which case there's no need to actually annotate a `classtype` on it.
- `Base` is a concrete class, in which case a workaround would be to split up the inheritance:

    ```python
    class CommonFields(BaseModel):  # Presumably an ABC
        common_field: int


    class Base(CommonFields):
        classtype: Literal["base"] = "base"


    class Cat(CommonFields):
        classtype: Literal["cat"] = "cat"
    ```

Am I missing anything?
