### ISSUE TITLE
model serialization / validation schemas leaking into schema

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#7209]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

As already discussed in https://github.com/tiangolo/fastapi/discussions/10019#discussioncomment-6737227 current pydantic defines different models in the schema when using both modes (validation/serialization) on a model - "{}Input" & "{}Output".
FastAPI started using mode=serialization for response models in 0.101 - bringing this issue up https://github.com/tiangolo/fastapi/discussions/10039 https://github.com/tiangolo/fastapi/discussions/10041.

This breaks all existing clients and invalidates every client code written due to changing the class name.
Current pydantic choose to change the name of the models again - adding a "-" before the Input/Output.

I understand there is a requirement to have different personalities, but the schema should be limited to a single personality - validation.

### Example Code

```Python
import io

import yaml

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema


class Pet(BaseModel):
    name: str
    weight: int | None
    color: str | None = None

data = models_json_schema([(Pet,"serialization"),(Pet,"validation")])
f = io.StringIO()
for d in data:
    for k,v in d.items():
        print(yaml.dump(v, f, indent=4))
f.seek(0)
print(f.read())
```

```yaml
$ref: '#/$defs/PetOutput'
$ref: '#/$defs/PetInput'
PetInput:
    properties:
        color:
            anyOf:
            -   type: string
            -   type: 'null'
            default: null
            title: Color
        name:
            title: Name
            type: string
        weight:
            anyOf:
            -   type: integer
            -   type: 'null'
            title: Weight
    required:
    - name
    - weight
    title: Pet
    type: object
PetOutput:
    properties:
        color:
            anyOf:
            -   type: string
            -   type: 'null'
            default: null
            title: Color
        name:
            title: Name
            type: string
        weight:
            anyOf:
            -   type: integer
            -   type: 'null'
            title: Weight
    required:
    - name
    - weight
    - color
    title: Pet
    type: object
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.2.1
        pydantic-core version: 2.6.1
          pydantic-core build: profile=release pgo=true
                 install path: ~/venv/openapi3/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
                     platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @adriangb

**Comment by samuelcolvin** [comment]
Would it be sufficient to add `input_suffix: str = 'Input', output_suffix: str = 'Output'`, you could then set them both to an empty string?

**Comment by dmontagu** [comment]
@commonism I understand this is frustrating, but when the types are just incompatible for validation and serialization, it may be important to get different behavior. Also, to be clear, pydantic just exposes the ability to specify whether you want to use the output schema or the input schema, and provides automatic conflict resolution.

I'm not convinced that never using the output schema is the best behavior; e.g., for a model with a field of type `Json[dict[str, int]]`, it seems to me unfortunate that if that was in a response field but we generated the JSON schema for validation, you'd get a type error in the generated client.

That said, I think there are a few things we can do to improve this:
* Add a model config setting for whether fields with defaults are required in the output schema, and default this to false. This would be the same as the validation behavior, and I believe this is currently the source of the majority of issues where the validation and serialization schemas differ. There is also a reasonable argument to make that you should be able to opt out of having fields with defaults required due to things like `exclude_unset` when serializing. And I'm suggesting we default this to False because this is a such a common source of issues with FastAPI, and so it won't require any changes.
* Add a model config setting that lets you override the schema generation mode even when mode='serialization' or mode='validation' is requested. That would give you the ability to ensure that, if you really want it, the generated schema will always be the 'validation' mode schema. However, I do _not_ think we should do this by default as I think it is better to properly support the case that the input and output schemas are different, and like I said above, I think that changing the default requiredness behavior will eliminate most collisions
* I think we can also add the ability to override the input/output suffixes, as Samuel has suggested, but do note that this won't resolve the issues brought up here because you'll just end up with collisions between the two different schemas. While we could perhaps add the ability to have a preferred resolution when there is a conflict, I think it's probably better to just rely on a mode override to prevent that.

So, basically, I'm proposing we add the following settings to the `ConfigDict`:
```
json_schema_serialization_defaults_required: bool = False
json_schema_mode_override: Literal['validation', 'serialization', None] = None
json_schema_validation_suffix: str = '-Input'
json_schema_serialization_suffix: str = '-Output'
```

and @commonism I think the only thing you'd need to change in your models is adding `json_schema_mode_override='validation'` if you really want to ensure that there is never a discrepancy even for non-idempotent types. (Another option might be to just use `json_schema_validation_suffix=''`, which would at least ensure that if there was a difference, the validation version of the model didn't get renamed.)
```

If this is an acceptable solution, I don't think it will be very hard to implement.

**Comment by commonism** [comment]
I'm not frustrated about this, it's more like … surprised about the lack of re/action for ~3 weeks.
It's breaking the whole code stack your loyal fans and customers rely on. 
No communication up-front about this breaking change and basically silence afterwards, not even acknowledging the issue.

I know - FastAPI is not your liability, but you've been more concerned/communicative about this.

Another option is - have the  model names static suffixed, using "…Ser" and "…Val", even if they match or serialization is not used, one could $ref the other. 
Arguments would always be "…Val", results "…Ser".
Would be easier to work with than having to guess the model name depending on model internals.

Aside - currently the difference in models is having non required fields in validation which are required in serialization?
To clients - this should not matter, as the serialization **validation schema** will always be a superset of the validation **validation schema**?

**Comment by commonism** [comment]
I'm trying to figure a scenario where is there is a requirement to the consumers of the description document to distinguish in serialization and validation for the same model due to optional/nullable properties.

Pet.color - from above - nullable, optional - not required.
If server-side pydantic chooses to serialize (PetOutput schema) Pet.color as None if unset - what does it matter to the validation of the model in a client?

I'd expect the serialization of nullable&optional fields to None (instead of excluding/skipping) to create a superset of the model which is always valid according to the validation schema.

Which would make publishing the serialization schema to the consumers not required?

**Comment by dmontagu** [comment]
> If server-side pydantic chooses to serialize (PetOutput schema) Pet.color as None if unset - what does it matter to the validation of the model in a client?

Let me try to demonstrate why it can be nice to distinguish between the case where a field is required or not based on the input/output mode in an OpenAPI schema.

Let's say I have an endpoint that looks like this:
```python
class MyModel(BaseModel):
    x: int = 1

@app.post('/')
def increment_my_model(model: MyModel) -> MyModel:
    return MyModel(x=model.x + 1)
```

Let's say I generate a typescript client based on this schema. We'll get interfaces that look like these:
```typescript
interface MyModelInput {
    x?: number
}

interface MyModelOutput {
    x: number
}
```

and some API client method will be generated that will look something like:
```
function incrementMyModel(input: MyModelInput): MyModelOutput {
  ...
}
```
In particular, I'd be able to do:
```typescript
const doubleIncrementedValue = incrementMyModel({}).x + 1
```
without any type errors, correctly reflecting the actual API.

However, if I use the validation schema for serialization, the code snippet above will result in a type error saying that I can't add a number and `undefined`, since `MyModel.x` might be undefined.

More generally, in my experience it can be kind of a hassle if you have to check if a field is undefined everywhere you make an API call just because it has a default value in the server-side model; ultimately I end up just not using default values even if it makes sense because of this.

------

At any rate, it does sound to me like the suggestion I made above would mostly address your issues. I'll try to open a PR for it  today and if you still have issues we can look into them more thoroughly?

**Comment by dmontagu** [comment]
@commonism
This is the generated schema:
```
from pydantic import BaseModel

class Model(BaseModel):
    x: int = 1

print(Model.model_json_schema(mode='validation'))
#> {'properties': {'x': {'default': 1, 'title': 'X', 'type': 'integer'}}, 'title': 'Model', 'type': 'object'}
```

The value `{}` is valid for that schema, but will never be the result of serialization, and thinking it may be will require you to do additional checks that the value is present if you make no assumption about the JSON schema.

The new behavior ensures that you don't have to do this by default, and behaves properly when used with `openapi-generator` (which I would argue is one of the most important uses of pydantic's generated JSON schemas). I understand if you disagree with this, but I think that using `openapi-generator` is probably the most common way to generate API clients and, at least in my opinion, this improves the behavior of that generator (and more strictly reflects the generated JSON schema).

At any rate, my proposal here will give the option to control this behavior, and will even have it disabled by default; does that leave you with objections?

> Now - take my example of using the Output model as input for e.g. PATCH.
> Different classes, this is unsolved.

While this is true, I would argue that when the input and output schemas are different in a way that is incompatible, it probably makes sense to just manually convert data between them if necessary; anything more than that likely requires assumptions that are not strictly guaranteed by the semantics of JSON/OpenAPI schemas. (Again, I am happy to provide features that make it easier for you to work with though.)

**Comment by commonism** [comment]
{} can be the result of serialization - when excluding default value.
Model({}).x == 1

The limitation in your example is related to the use of typescript interfaces where default values are not possible at compile time. Easy fix, generate code which makes use of default values.

There is code generators which do not understand default values, but I do not see this can/should be resolved _here_, at least not as a default.
Providing standard workarounds for them keeps them alive & relevant instead of pushing the required changes.

As this degrades the quality of the description document I'd see this as opt-in instead of opt-out, creating awareness of the standards-compatibility issues for those who need it, and not making things worse for those who can do default values properly.
And, of course, having the possibility to change the settings does not help if you do not control the server-side of things.

**Comment by dmontagu** [comment]
>{} can be the result of serialization - when excluding default value.

I agree, and that's why I think it's reasonable to have it as a configurable option even if you (or others) _did_ agree with my original opinion that it should be the default.

> The limitation in your example is related to the use of typescript interfaces where default values are not possible at compile time. Easy fix, generate code which makes use of default values.

This "easy fix" only works if I rework my client to generate types with accessor methods for fields with defaults. While it's admittedly been a while since I looked, I have not seen anyone use this pattern instead of using interfaces and objects, and I'm not aware of tooling (i.e., openapi generator templates) that would do this. (Not to mention the performance consequences.)

If I do want to use interfaces, and I want to make use of the generated interface itself in other parts of my code and still want it type-checked properly, this just fundamentally requires different types to encode guarantees about the presence of the field value.

> There is code generators which do not understand default values, but I do not see this can/should be resolved here, at least not as a default.
> Providing standard workarounds for them keeps them alive & relevant instead of pushing the required changes.

I am willing to concede that the current default behavior is less practical in some cases and introduces backwards compatibility pain for many, which is why I plan to change it so that fields with default values are not treated as required by default.

> ... I'd see this as opt-in instead of opt-out

It sounds like we are in agreement. I'll open a PR for this shortly.

That said, I will note that I still believe that when the validation and serialization versions of models have more fundamentally different structure than just default values being present or not (e.g., models with `@computed_field`s), the two schemas should involve the use of different types. (And would require explicitly opting out if you want it to _always_ use the validation schema.)

**Comment by commonism** [comment]
> This "easy fix" only works if I rework my client to generate types with accessor methods for fields with defaults.

Even when using the spread operator to apply default values?

**Comment by Ark-kun** [comment]
Why does Pydantic generate exact duplicate Input/Output schemas? I'd understand if they were different. But they are identical.

```py
class Foo(pydantic.BaseModel):
    foo: "Foo | str"
json_schema.models_json_schema([(Foo,"serialization"),(Foo,"validation")])
```

```
({(__main__.Foo, 'serialization'): {'$ref': '#/$defs/Foo-Output'},
  (__main__.Foo, 'validation'): {'$ref': '#/$defs/Foo-Input'}},
 {
  "$defs": {
    "Foo-Input": {
      "title": "Foo",
      "type": "object",
      "properties": {
        "foo": {
          "title": "Foo",
          "anyOf": [
            {"$ref": "#/$defs/Foo-Input"},
            {"type": "string"}
          ]
        }
      },
      "required": ["foo"]
    },
    "Foo-Output": {
      "title": "Foo",
      "type": "object",
      "properties": {
        "foo": {
          "title": "Foo",
          "anyOf": [
            {"$ref": "#/$defs/Foo-Output"},
            {"type": "string"}
          ]
        }
      },
      "required": ["foo"]
    }
  }
}
)
```
