### ISSUE TITLE
Duplicate names in/of Fields and Models causes strange behavior and exceptions

### ISSUE THREAD

**Issue by jnj16180340** [pydantic/pydantic#7453]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When a Model and Field both used in the definition of another Model share the same name, the definition appears to succeed but use of the model exhibits strange behavior (Examples in code snippet).                                 

I don't necessarily think supporting name reuse between models and fields is worth any effort as a goal in itself, but it could be helpful to explicitly forbid this kind of thing by raising exceptions at model definition time, or at least noting it in documentation -- Experience suggests less senior developers could spend hours trying to debug this.

### Example Code

```Python
## SETUP
from pydantic import BaseModel
from typing import Optional

class Doc(BaseModel):
    ContentVersioned: bool
    DocID: str

## TEST: WEIRD BEHAVIOR 1 - default values
class Acaml(BaseModel):
    xmlns: str
    xmlns_xsi: str
    Doc: Optional[Doc] = None

# OK
Acaml(xmlns='a',xmlns_xsi='b')
Acaml(xmlns='a', xmlns_xsi='b', Doc=None)

# EXCEPTION: ValidationError "Input should be None"
Acaml(xmlns='a',xmlns_xsi='b', Doc=Doc(ContentVersioned=True,DocID='piff'))


## TEST: WEIRD BEHAVIOR 2 - optional type syntax
class Acaml(BaseModel):
    xmlns: str
    xmlns_xsi: str
    Doc: Doc | None = None

# EXCEPTION: TypeError: unsupported operand type(s) for |: 'NoneType' and 'NoneType'

## TEST: OK after renaming the `Doc` field to `Docc`
class Acaml(BaseModel):
    xmlns: str
    xmlns_xsi: str
    Docc: Doc | None = None

# ALL OK
Acaml(xmlns='a',xmlns_xsi='b', Docc= Doc(ContentVersioned=True,DocID='piff'))
Acaml(xmlns='a',xmlns_xsi='b', Docc= None)
Acaml(xmlns='a',xmlns_xsi='b')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/nate/.pyenv/versions/3.11.1/lib/python3.11/site-packages/pydantic
               python version: 3.11.1 (main, Dec 13 2022, 10:43:53) [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.4-arm64-arm-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```
```

**Comment by sydney-runkle** [comment]
Hi @jnj16180340,

Thanks for your question! The [PEP](https://peps.python.org/pep-0008/#class-names) specifies that class names in Python should use `CapWords` convention (also called CamelCase), whereas class attributes should use `snake_case`. There are some exceptions with regards to what style class attributes can use, but they're never supposed to use `CapWords` convention.

Thus, if you're adhering to best practice as outlined in PEP 8, you shouldn't run into any issues with this.

You're experiencing these errors because the `FieldInfo` generated for the `Doc` attribute of `Acaml` is created as `FieldInfo(annotation=NoneType, required=False)`. Really, what you want it to be is `FieldInfo(annotation=Union[Doc, NoneType], required=False)`. Here's a code snippet you could use to achieve that:

```py
from typing import Optional

from pydantic import BaseModel


class Doc(BaseModel):
    content_versioned: bool
    doc_id: str


class Acaml(BaseModel):
    xmlns: str
    xmlns_xsi: str
    doc: Optional[Doc] = None


# all ok :)
Acaml(xmlns='a',xmlns_xsi='b')
Acaml(xmlns='a', xmlns_xsi='b', doc=None)
Acaml(xmlns='a',xmlns_xsi='b', doc=Doc(content_versioned=True,doc_id='piff'))
```

Let me know if you have any follow up questions - happy to help 😄.
