### ISSUE TITLE
model_validator(mode='wrap') has no access to input values anymore when triggered by validate_assignment

### ISSUE THREAD

**Issue by Magnati** [pydantic/pydantic#7454]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

A `model_validator('wrap')` when called on `__init__` gets the `input_data_dict` just as a `model_validator('before')` would do.
But if the model is using `'validate_assignment' = True` and the `model_validator('wrap')` is called again during assignment, it has not anymore access to the dict representation but the passed element is of the very datatype.

That seems additonally odd, because calling the handler within the `model_validator('wrap')` again calls the `model_validator('before')` which has still access to the dict representation.

Note: I am not entirely sure if this is a bug, but I was able to achieve this with the deprecated root_validator and its modes, so I assume it is one.
If not, I am sorry. Maybe the documentation on the wrap mode can be improved instead, then.

### Example Code

```Python
from pydantic import BaseModel, model_validator
from pydantic_core.core_schema import ValidatorFunctionWrapHandler


class A(BaseModel):
    name: str
    interesting_field: list

    model_config = {
        'validate_assignment': True
    }

    @model_validator(mode='before')
    @classmethod
    def validate_name(cls, values: dict):
        # input values is a dict with all values that are provided including those which are not defined in the model
        print(f"model_validator_before: values is a {type(values)}")
        return values

    @model_validator(mode='wrap')
    @classmethod
    def look_for_interesting_field_even_if_not_needed_by_model(cls, values, handler: ValidatorFunctionWrapHandler):
        # from __init__, values is a dict, from 'validate_assignment' it is an 'A'-instance
        print(f"model_validator_wrap: values is a {type(values)}")
        validated_model = handler(values)
        # do something with values after model is created, becomes complicated or even impossible if already an object
        return validated_model


test_dict = {
    "name": "example",
    "interesting_field": ["stuff", 2, "do stuff"]
}

test = A(**test_dict)
test.name = "trigger validation"
# Output:
# model_validator_wrap: values is a <class 'dict'>
# model_validator_before: values is a <class 'dict'>
# model_validator_wrap: values is a <class '__main__.A'>
# model_validator_before: values is a <class 'dict'>
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/***/Git/***/***/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.16 (default, Dec  7 2022, 01:39:17)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.5.2-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @Magnati,

Thanks for your question. Working with `mode='wrap'` validators can be a bit confusing, so hopefully this will help resolve some of the confusion.

According to the [Usage/Validators](https://docs.pydantic.dev/latest/usage/validators/#model-validators) section of the docs explains that while `mode='after'` validators always receive an instance of the model as the first argument, and are thus easier to implement.  On the other hand, according to the same docs, `mode='before'` and `mode='wrap'` validators 
> are passed the raw input which is often a dict[str, Any] but could also be an instance of the model itself (e.g. if UserModel.model_validate(UserModel.construct(...)) is called) or anything else since you can pass arbitrary objects into model_validate.

So, what you're seeing in your example is that when you initialize your `test_dict` instance, you pass in raw input, hence the first line in your output (`# model_validator_wrap: values is a <class 'dict'>`). Then,  `validated_model = handler(values)` is called within your wrap validator, which triggers a call of the before validator, which is passed the same dict, hence the second line in your output (`# model_validator_before: values is a <class 'dict'>`). You then return data of type `dict` from the before validator. The handler proceeds to construct an instance of the model, which you store as `validated_model` in your wrap validator. This is then returned.

The second case is the one where you're reassigning a model attribute. When an attribute is set on an instance, the `validate_assignment` [call is made](https://github.com/pydantic/pydantic/blob/97350c4ae9bfba3a4bada007383a750476df6b69/pydantic/main.py#L771) with the instance of the model is passed as the first argument. This gets passed downstream into the wrap validator, hence the third line of output (`# model_validator_wrap: values is a <class '__main__.A'>`). Finally, when the `handler` is called from the wrap validator, even though the input to this handler call is of type `A`, the data is cast into a dictionary for the before validator call. That's why you're seeing the 4th line of output (`model_validator_before: values is a <class 'dict'>`).

In sum, this is the expected behavior. Validators with mode `before` and `wrap` are incredibly versatile and powerful, but they're also more error prone given that the input data can be of a dict type or of model instance type.

Let me know if you have any more questions. Happy to help 😄!

**Comment by sydney-runkle** [comment]
For reference, we see similar behavior when validating an existing instance of a class:

```py
from pydantic import BaseModel, ConfigDict, model_validator
from pydantic_core.core_schema import ValidatorFunctionWrapHandler

class A(BaseModel):
    model_config: ConfigDict = ConfigDict(revalidate_instances="always")
    
    name: str
    
    @model_validator(mode='before')
    @classmethod
    def before_validator(cls, values: dict):
        print(f"model_validator_before: values is a {type(values)}")
        return values

    @model_validator(mode='wrap')
    @classmethod
    def wrap_validator(cls, values, handler: ValidatorFunctionWrapHandler):
        print(f"model_validator_wrap: values is a {type(values)}")
        validated_model = handler(values)
        return validated_model

a_one = A(name="example")
print("\n")
a_two = A.model_validate(a_one)

#> model_validator_wrap: values is a <class 'dict'>
#> model_validator_before: values is a <class 'dict'>

#> model_validator_wrap: values is a <class '__main__.A'>
#> model_validator_before: values is a <class 'dict'>
```

**Comment by Magnati** [comment]
Thanks for the answer, @sydney-runkle.
 
So, the easiest solution even if doubled would be just to call `model_dump()` in case the input to the wrap validator is already an instance, right?
Probably what is done in between wrap- and before-validator anyway.

**Comment by sydney-runkle** [comment]
Hi @Magnati,

Sure thing. Yep, that's one option! 

To clarify, the wrap model validator still has access to the input values, you'd just have to access them on the instance instead of from the dict if you pass in an instance. But, if you pass in a dict to `model_validate`, you can always access said values from the dict input.
