### ISSUE TITLE
Computed_fields outputs a property object instead of the value

### ISSUE THREAD

**Issue by Galsor** [pydantic/pydantic#7458]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello, 

When a model inherits from another model, overriding one of its fields with a `computed_field`, the overridden computed field returns a property object instead of the value produced by the function.

```python
# This works fine
class Plane(BaseModel):
 
@computed_field
def name(self) -> str:
   return 'A310'

Plane().name
>>> 'A310' 

# This doesn't
class Aircraft(BaseModel):
   name: str

class Plane(Aircraft):
   category: str = 'A'
   code: str = '310'

   @computed_field
   def name(self) -> str:
      return self.category + self.code

Plane().name
>>> '<property object at 0x7ff1ed10b8d0>'
```

I am running pydantic==2.3.0 (pydantic_core==2.6.3)

### Example Code

```Python
from pydantic import BaseModel, computed_field

class Aircraft(BaseModel):
   name: str

class Plane(Aircraft):
   category: str = 'A'
   code: str = '310'

   @computed_field
   def name(self) -> str:
      return self.category + self.code
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /workspaces/project/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Aug 19 2023, 00:31:12) [GCC 9.4.0]
                     platform: Linux-5.15.0-1041-azure-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi,

Thanks for your question. We recently addressed this issue in [this PR](https://github.com/pydantic/pydantic/pull/7346), and these changes should get released with the next version. The changes make it such that an error is raised when a `computed_field` is defined in a subclass such that it overrides a field from a superclass.

We decided to raise an error here because this behavior is both prohibited by dataclasses and discouraged by `mypy`. 

If you're looking for a workaround, using a model validator with `mode="after"` as shown in [this example](https://github.com/pydantic/pydantic/issues/7382#issuecomment-1716756806) could help.

Let me know if you have any more questions! 😄

**Comment by Galsor** [comment]
Ok...
I am interested to understand this choice of forbidding this behavior. Is there any discussion or resources somewhere to justify this choice?

**Comment by sydney-runkle** [comment]
Sure thing - we've been discussing this decision in #7250.

**Comment by sydney-runkle** [comment]
Closing in favor of continuing discussion on #7250.
