### ISSUE TITLE
pydantic can't create schema correctly with dataclass + generics

### ISSUE THREAD

**Issue by E5presso** [pydantic/pydantic#7479]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm using pydantic in FastAPI, and use dataclass decorator in stdlib (not in pydantic.dataclasses)

I want to use generic abstract class which has basic template for return schema (like list query results, they have row count, and actual data rows)

But, pydantic v2 seems not supporting generic abstract class with std dataclass.

I wanted to implement classes like this.

QModel(ABC)                ----->             PQModel(Generic[TQModel], ABC)
TQModel(QModel)             ----->         TPQModel(PQModel[TQModel])

With that relations, Pydantic doesn't recognize schemas of TQModel 
but only schemas in QModel.

### Example Code

```Python
@dataclass
class QueryModel(ABC):
    id: UUID


TQueryModel = TypeVar("TQueryModel", bound=QueryModel)


@dataclass
class PagableQueryModel(Generic[TQueryModel], ABC):
    count: int
    rows: list[TQueryModel]


@dataclass
class TestQueryModel(QueryModel):
    name: str
    age: int


@dataclass
class TestPagableQueryModel(PagableQueryModel[TestQueryModel]):
    ...
```

### Python, Pydantic & OS Version

```Text
python version: 3.11.3
pydantic version: 2.3.0
os version: macos Ventura 13.5.2
```

**Comment by sydney-runkle** [comment]
Hi @E5presso,

Thanks for your question. If you could include imports in your code snippet next time that'd be helpful for us in terms of reproducing the issue.

Could you also include an `assert` statement or something similar so that we can see where the schema generation is differing from the result you expect? That'll help us to figure out what's going wrong as well.

Looking forward to helping you solve this 😄

**Comment by sydney-runkle** [comment]
@E5presso, do you still need help with this issue?
