### ISSUE TITLE
Weird behavior of issubclass(BaseModel, MyClass)

### ISSUE THREAD

**Issue by ziyuang** [pydantic/pydantic#7486]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Here is the code to reproduce. The goal is to find out the concrete type of a generic type in the subclass.

```
from __future__ import annotations

import abc
import types
import typing
from typing import ClassVar, Generic, Type, TypeVar

from pydantic import BaseModel

ParamT = TypeVar("ParamT", bound=BaseModel)


class Abstract(Generic[ParamT], abc.ABC):
    param_type: ClassVar[Type[BaseModel]]

    def __init_subclass__(cls: Type[Abstract], *args, **kwargs):
        super().__init_subclass__(*args, **kwargs)
        param_type = Abstract._extract_param_type(cls)
        cls.param_type = param_type

    @staticmethod
    def _extract_param_type(cls: Type[Abstract]) -> Type[BaseModel]:
        assert hasattr(cls, "__orig_bases__")
        for base_index, base in enumerate(cls.__orig_bases__):
            if isinstance(base, (types.GenericAlias, typing._GenericAlias)):
                base = typing.get_origin(base)
            # issubclass(BaseModel, Abstract)  # <----- mind this
            # print(base, issubclass(base, Abstract))
            if issubclass(base, Abstract):
                break
        else:
            raise RuntimeError(f"{cls.__name__} must be a subclass of Abstract")

        input_type = typing.get_args(cls.__orig_bases__[base_index])[0]
        return input_type
```

This works fine when we subclass `Abstract` in the following way, with `BaseModel` as one of the base classes:
```
class ExampleInput(BaseModel):
    pass


class NormalInheritance(Abstract[ExampleInput], BaseModel):
    pass

assert NormalInheritance.param_type == ExampleInput
```

However, it doesn't work when we have the inheritance order:
```
class OutOfOrderInheritance(BaseModel, Abstract[ExampleInput]):
    pass
```
It fails at `input_type = typing.get_args(cls.__orig_bases__[base_index])[0]`. If we uncomment the printing line, we can see `base` is `pydantic.main.BaseModel` but `issubclass(base, Abstract)` strangely returns `True`. Further, if we also uncomment the line above (the `issubclass` test), which should have no actual effect, while `base` is still `pydantic.main.BaseModel`, `issubclass(base, Abstract)` returns `False` as it should.

### Example Code

As above.

### Python, Pydantic & OS Version

```Text
        pydantic version: 1.10.12
       pydantic compiled: True
            install path: ~/workspace/main/.venv/lib/python3.10/site-packages/pydantic
          python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
                platform: Linux-6.2.0-32-generic-x86_64-with-glibc2.35
optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by grafsw** [comment]
This behavior was very strange, but I was able to see how it works.
`BaseModel` is not a subclass of Abstract, but `issubclass(base(=BaseModel), Abstract)`  is return to True. Why?

First, I checked the code how `issubclass` works.
`issubclass` method calls `__subclasscheck__(cls, subclass)`. [__subclasscheck__ source](https://github.com/python/cpython/blob/main/Lib/_py_abc.py)
Looking at this code, you can see that the cache is used to if it is a subclass.
And when you call `issubclass`, the cache will be registered.

At `pydantic.BaseModel`, the cache is registered by When inheriting BaseModel.
[ModelMetaClass._collect_bases_data: Line237](https://github.com/pydantic/pydantic/blob/main/pydantic/_internal/_model_construction.py)
[lenient_issubclass: Line75](https://github.com/pydantic/pydantic/blob/main/pydantic/_internal/_util.py)

This cache can be checked by calling `_dump_registry()`
```
from abstract import Abstract
from pydantic import BaseModel

class ExampleInput(BaseModel):
    pass

print(BaseModel._dump_registry())

class NormalInheritance(Abstract[ExampleInput], BaseModel):
    pass
```
```
>>Class: pydantic.main.BaseModel
>>Inv. counter: 45
>>_abc_registry: set()
>>_abc_cache: {<weakref at 0x7fcf4e1258f0; to 'ModelMetaclass' at 0x560895530610 (ExampleInput)>, <weakref at 0x7fcf4ea8de40; to 'ModelMetaclass' at 0x560895541460 (BaseModel)>}
>>_abc_negative_cache: set()
>>_abc_negative_cache_version: 33
>>None
```
``
`pydantic` called `issubclass(BaseModel, BaseModel)` ans `issubclass(ExampleInput, BaseModel)`. And subclass list is registered in `_abc_cache`.


Let's take a look at the cache at the problem location.
```
# abstract.Abstract._extract_param_type

    @staticmethod
    def _extract_param_type(cls: Type[Abstract]) -> Type[BaseModel]:
        assert hasattr(cls, "__orig_bases__")
        
        for base_index, base in enumerate(cls.__orig_bases__):
            if isinstance(base, (types.GenericAlias, typing._GenericAlias)):
                base = typing.get_origin(base)

            # issubclass(BaseModel, Abstract)  # <----- mind this
            # print(base, issubclass(base, Abstract))
            print(Abstract._dump_registry)
            
            if issubclass(base, Abstract):
                break
        else:
            raise RuntimeError(f"{cls.__name__} must be a subclass of Abstract")

        input_type = typing.get_args(cls.__orig_bases__[base_index])[0]
        return input_type
```
```
>>Class: abstract.Abstract
>>Inv. counter: 45
>>_abc_registry: set()
>>_abc_cache: set()
>>_abc_negative_cache: set()
>>_abc_negative_cache_version: 33
>>None
>>Class: abstract.Abstract
>>Inv. counter: 45
>>_abc_registry: set()
>>_abc_cache: {<weakref at 0x7efc40864b80; to 'ABCMeta' at 0x55e416a0f420 (Abstract)>}
>>_abc_negative_cache: set()
>>_abc_negative_cache_version: 45
>>None
```

There seems to be no problem. (The first is the output of `NormalInheritance` and the second is the output of `OutOfOrderInheritance`.)
Let's take a closer look at issubclass. `issubclass` calles `__subclasscheck__` in the metaclass.
[__subclasscheck__](https://github.com/python/cpython/blob/main/Lib/_py_abc.py) is calling issubclass on both the subclass of the superclass and the superclass.
The subclasses of `Abstract` are `NormalInheritance` and `OutOfOrderInheritance`, so let's check  `issubclass(BaseModel, NormalInheritance)` and `issubclass(BaseModel, OutOfOrderInheritance)`.

```
# abstract.Abstract._extract_param_type
    @staticmethod
    def _extract_param_type(cls: Type[Abstract]) -> Type[BaseModel]:
        assert hasattr(cls, "__orig_bases__")

        for base_index, base in enumerate(cls.__orig_bases__):
            if isinstance(base, (types.GenericAlias, typing._GenericAlias)):
                base = typing.get_origin(base)
            
            if (cls.__name__=='OutOfOrderInheritance'):
                for scls in Abstract.__subclasses__():
                    print(scls, issubclass(BaseModel, scls))
            
            if issubclass(base, Abstract):
                break
        else:
            raise RuntimeError(f"{cls.__name__} must be a subclass of Abstract")

        input_type = typing.get_args(cls.__orig_bases__[base_index])[0]
        return input_type
```
```
>><class '__main__.NormalInheritance'> False
>><class '__main__.OutOfOrderInheritance'> True
```
Woh, True has appeared. This is the cause.
Let's find out the cause.
```
# abstract.Abstract._extract_param_type
    @staticmethod
    def _extract_param_type(cls: Type[Abstract]) -> Type[BaseModel]:
        assert hasattr(cls, "__orig_bases__")

        for base_index, base in enumerate(cls.__orig_bases__):
            if isinstance(base, (types.GenericAlias, typing._GenericAlias)):
                base = typing.get_origin(base)
            
            if (cls.__name__=='OutOfOrderInheritance'):
                print(cls._dump_registry())
            
            if issubclass(base, Abstract):
                break
        else:
            raise RuntimeError(f"{cls.__name__} must be a subclass of Abstract")

        input_type = typing.get_args(cls.__orig_bases__[base_index])[0]
        return input_type
```
```
>>Class: __main__.OutOfOrderInheritance
>>Inv. counter: 45
>>_abc_registry: set()
>>_abc_cache: {<weakref at 0x7f7b28f10a90; to 'ModelMetaclass' at 0x555c257c6e00 (NormalInheritance)>, <weakref at 0x7f7b29115c60; to 'ModelMetaclass' at 0x555c2570b110 (ExampleInput)>, <weakref at 0x7f7b29115990; to 'ModelMetaclass' at 0x555c256ff430 (BaseModel)>}
>>_abc_negative_cache: {<weakref at 0x7f7b28f10720; to 'ABCMeta' at 0x555c2570ad50 (Abstract)>}
>>_abc_negative_cache_version: 45
>>None
```
`_abc_cache(allowed)` contains the `BaseModel`. Therefore, `Basemodel` is treated as a subclass of `Abstract`.

When was BaseModel registered in the cache? That means `issubclass(BaseModel, OutOfOrderInheritance)` has been called.
However, this kind of thing is not called.

Examining further behavior.
```
# abstract.Abstract.__init_subclass__
    def __init_subclass__(cls: Type[Abstract], *args, **kwargs):
        print(cls._dump_registry())
        super().__init_subclass__(*args, **kwargs)
        param_type = Abstract._extract_param_type(cls)
        cls.param_type = param_type
```
```
>>Class: __main__.NormalInheritance
>>Inv. counter: 45
>>_abc_registry: set()
>>_abc_cache: set()
>>_abc_negative_cache: set()
>>_abc_negative_cache_version: 33
>>None
>>Class: __main__.OutOfOrderInheritance
>>Inv. counter: 45
>>_abc_registry: set()
>>_abc_cache: {<weakref at 0x7f8a68bcda80; to 'ModelMetaclass' at 0x556b749ec130 (ExampleInput)>, <weakref at 0x7f8a68a2cd10; to 'ModelMetaclass' at 0x556b74a3a000 (NormalInheritance)>, <weakref at 0x7f8a68bcd7b0; to 'ModelMetaclass' at 0x556b749dfcb0 (BaseModel)>}
>>_abc_negative_cache: {<weakref at 0x7f8a68a2c7c0; to 'ABCMeta' at 0x556b749ebd70 (Abstract)>}
>>_abc_negative_cache_version: 45
>>None
```
Looking at this, you can see that `OutOfOrderInheritance` has inherited the BaseModel cache.
Since it is not inherited by `NormalInheritance`, it seems that in case of multiple inheritance, the left cache is inherited.


So why didn't an error occur when I called  `# issubclass(BaseModel, Abstract)  # <----- mind this?`
```
from abstract import Abstract
from pydantic import BaseModel

class ExampleInput(BaseModel):
    pass

class NormalInheritance(Abstract[ExampleInput], BaseModel):
    pass

issubclass(BaseModel, Abstract)
print(Abstract._dump_registry())

class OutOfOrderInheritance(BaseModel, Abstract[ExampleInput]):
    pass
```
```
>>Class: abstract.Abstract
>>Inv. counter: 45
>>_abc_registry: set()
>>_abc_cache: {<weakref at 0x7f68882bcc20; to 'ABCMeta' at 0x561cefb11080 (Abstract)>}
>>_abc_negative_cache: {<weakref at 0x7f68882bcea0; to 'ModelMetaclass' at 0x561cefb0ba00 (BaseModel)>}
>>_abc_negative_cache_version: 45
>>None
```
It was registered in `_abc_negative_cache(denied)` by calling `issubclass(BaseModel, Abstract)`.
Evaluation of subclass comes after evaluation of `_abc_negative_cache`. issubclass(BaseModel, Abstract) will be False.

It's a complicated, but did you understand?

Users should be aware of this behavior when using metaclasses and multiple inheritance.
This is a problem with the python metaclass specifications. I don't think it's pydantic's responsibility.

I think the proper solution to this problem is to clear the cache.
```
# abstract.Abstract.__init_subclass__

    def __init_subclass__(cls: Type[Abstract], *args, **kwargs):
        cls._abc_caches_clear()
        super().__init_subclass__(*args, **kwargs)
        param_type = Abstract._extract_param_type(cls)
        cls.param_type = param_type
```

However, pydantics should also be considered.
We recommend reversing the order of the parts below.
[ModelMetaClass._collect_bases_data: Line237](https://github.com/pydantic/pydantic/blob/main/pydantic/_internal/_model_construction.py)
```
# now
if issubclass(base, BaseModel) and base is not BaseModel:
# desirable
if base is not BaseModel and issubclass(base, BaseModel) :
```
Since pydantic is module, it should have as little impact on the outside world as possible.
This fix also resolves this issue.

**Comment by grafsw** [comment]
Sorry, I answered based on condition V2.

There is not much difference in case V1. The solution remains the same.
In the V1 case, the part where pydantic calls `issubclass` is different.
[BaseModel:Line137](https://github.com/pydantic/pydantic/blob/main/pydantic/v1/main.py) 

The correction points in this case are as follows.
```
# now
if _is_base_model_class_defined and issubclass(base, BaseModel) and base != BaseModel:
# desirable
if _is_base_model_class_defined and base != BaseModel and issubclass(base, BaseModel):
```
