### ISSUE TITLE
model_copy extra="forbid" not applied correctly

### ISSUE THREAD

**Issue by joamatab** [pydantic/pydantic#7581]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

```
from pydantic import BaseModel


class Person(BaseModel):
    name: str
    age: int
    model_config = dict(frozen=True, extra="forbid")


# expected to fail but doesn't
p1 = Person(name="John", age=20)
p2 = p1.model_copy(update={"DoesNotExist": "should_fail"})

# fails as expected
p3_settings = dict(p1)
p3_settings.update({"DoesNotExist": "should_fail"})
p3 = Person(**p3_settings)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
pydantic-core version: 2.6.3
pydantic-core build: profile=release pgo=true
install path: /home/j/mambaforge/lib/python3.11/site-packages/pydantic
python version: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
                     platform: Linux-6.1.51-1-MANJARO-x86_64-with-glibc2.38
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @joamatab,

Thanks for your question! Our [documentation](https://docs.pydantic.dev/latest/api/base_model/#pydantic.main.BaseModel.model_copy) on the `model_copy()` function has a note about this kind of behavior regarding the `update` parameter:
> Values to change/add in the new model. Note: the data is not validated before creating the new model. You should trust this data.

So, I think based on our current documentation, the behavior you've displayed is correct. Let me know what you think!

**Comment by joamatab** [comment]
I see, i was expecting that the data would be validated, 

how about adding a flag for validating the data?

**Comment by dmontagu** [comment]
Hi @joamatab I hope you are doing well.

I think given the `model_copy` with update is intended to be "trusted data", and doing validation on it would add some overhead that could otherwise be dropped, it probably doesn't make sense for us to change the behavior of this function. (I am open to being convinced otherwise.)

However, you can implement a very similar function with just a bit of additional overhead that I think achieves what you want:

```python
from typing import Any
from typing_extensions import Self

from pydantic import BaseModel


class MyModel(BaseModel):
    def model_copy_untrusted_update(self, *, update: dict[str, Any] | None = None, deep: bool = False) -> Self:
        copied = self.__deepcopy__() if deep else self.__copy__()
        extra_behavior = self.model_config.get('extra', 'ignore')
        if update:
            for k, v in update.items():
                if k in self.model_fields:
                    copied.__dict__[k] = v
                elif extra_behavior == 'allow':
                    if copied.__pydantic_extra__ is None:
                        copied.__pydantic_extra__ = {}
                    copied.__pydantic_extra__[k] = v
                elif extra_behavior == 'forbid':
                    raise ValueError(f'Extra field not permitted: {k}')
            copied.__dict__.update(update)
            copied.__pydantic_fields_set__.update(update.keys())
        return copied
```
(It would probably work to just override `model_copy` with this, I just gave it a new name for clarity.)

Note that this also has the improved behavior that if you pass unrecognized attributes in an update to a model with `extra='ignore'`, it will behave correctly (whereas if you do that with the existing `model_copy` function, you'll probably get misbehavior when doing `model_dump` or anything else that accesses the `__dict__`; again, the `update` should be a "trusted" value, though we could probably better-document this requirement, especially that it only contain field values when using models with `extra='ignore'`).

Let us know if this suggestion doesn't work for your use case or you prefer a different solution.

**Comment by dmontagu** [comment]
Note also that this suggestion will not actually perform validation of the values provided as part of the update. If you want _that_, I think the best route would be to either use your approach of dumping and revalidating, or using the `validate_assignment` config setting. It's mostly hard to do that because pydantic-core validates the model as a whole, rather than individual fields.

That said, we've had other requests recently related to validating individual fields of a model, so it's possible we could come up with an improved API for this that handles multiple use cases.

**Comment by joamatab** [comment]
Thank you David

i ended up using a simpler version

```
def copy(self, **kwargs):
        for kwarg in kwargs:
            if kwarg not in dict(self):
                raise ValueError(f"{kwarg!r} not in Model")
        return self.model_copy(update=kwargs)

```
