### ISSUE TITLE
Generators raise `ValidationError` for list fields in v2.4

### ISSUE THREAD

**Issue by PoByBolek** [pydantic/pydantic#7613]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic 2.4 seems to require a maximum length for list fields that are filled by generator objects. This wasn't there in Pydantic 2.3.

```
Traceback (most recent call last):
  File "/home/bug/pydantic-bug/bug.py", line 18, in <module>
    Bug.model_validate({'values': count(20)})
  File "/home/bug/pydantic-bug/venv/lib/python3.10/site-packages/pydantic/main.py", line 503, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for Bug
values
  List should have at most 10 items after validation, not 11 [type=too_long, input_value=<generator object count at 0x7f0bb48963b0>, input_type=generator]
    For further information visit https://errors.pydantic.dev/2.4/v/too_long
```

### Example Code

```Python
from pydantic import BaseModel


class Bug(BaseModel):
    values: list[int]


def count(N):
    yield from range(N)


Bug.model_validate({'values': list(count(20))})
# works

Bug.model_validate({'values': range(20)})
# works

Bug.model_validate({'values': count(20)})
# ValidationError: List should have at most 10 items after validation, not 11 [type=too_long, input_value=<generator object count at 0x7f0bb48963b0>, input_type=generator]
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.4.0
        pydantic-core version: 2.10.0
          pydantic-core build: profile=release pgo=true
                 install path: /home/bug/pydantic-bug/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
                     platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
@PoByBolek,

Thanks for reporting this - we're investigating and will get a fix up ASAP.

**Comment by davidhewitt** [comment]
It looks like this was caused by https://github.com/pydantic/pydantic-core/pull/902 - specifically this part of the diff: https://github.com/pydantic/pydantic-core/pull/902/files#diff-87ca89d3d189f41f793fe9233562932476786d0140b8e001f3694fb90624b0a6R145-R155

From reading the PR it looks like that was introduced as a defense against infinite generators (as we can't know their length), but it seems clear enough to me that a hard limit of 10 seems way too low if such a defense is really necessary. I suggest we just revert that bit for now as it wasn't really related to the original motivation of the PR.

cc @adriangb looks like you identified this during review in https://github.com/pydantic/pydantic-core/pull/902#discussion_r1300433499

**Comment by davidhewitt** [comment]
`list(itertools.repeat(None))` will blow up a process with OOM so I have the stance that if you're using an infinite generator you're already well prepared for likely failures, and we have no business terminating a generator early on an unbounded `list` validation. (If you want to avoid infinite generation, add a `max_length`.)
