### ISSUE TITLE
Different behavior than V1 for `Union[bool, str]` or `Union[int, str]`

### ISSUE THREAD

**Issue by URenko** [pydantic/pydantic#7762]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Use `Union[bool, str]` or `Union[int, str]` can directly parse value like `False` in V1, but not in V2.
I'm not sure if this is a bug or an expected difference.
If this is an expected difference, is there an elegant way to achieve V1-like behavior.

### Example Code

```Python
import os
from typing import Union
# from pydantic import BaseSettings  # V1
from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    testA: bool = True
    testB: Union[bool, str] = True

os.environ['testA'] = 'False'
os.environ['testB'] = 'False'
print(repr(Settings().testA), repr(Settings().testB))
# False 'False'  <--- V2
# False False    <--- V1
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: <omitted>/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
                     platform: Linux-6.1.0-12-amd64-x86_64-with-glibc2.36
             related packages: typing_extensions-4.8.0 fastapi-0.103.2 pydantic-settings-2.0.3
```

**Comment by sydney-runkle** [comment]
Hi @URenko,

Thanks for your question. Yep - we're stricter with validation in V2, so this is expected behavior. We've also changed the way that unions work. You can check out the migration guide [here](https://docs.pydantic.dev/latest/migration/#unions) regarding those union changes.

```py
import os
from typing import Union

from pydantic import Field
from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    testA: bool = True
    testB: Union[bool, str] = Field(default=True, union_mode='left_to_right')

os.environ['testA'] = 'False'
os.environ['testB'] = 'False'
print(repr(Settings().testA), repr(Settings().testB))
#> False False
```

If you use union mode of [`left_to_right`](https://docs.pydantic.dev/latest/api/standard_library_types/#union),  you should get the expected behavior that you're looking for.

Hope this helps 😄. Let me know if you have any other questions!

**Comment by URenko** [comment]
Thank you for your timely answer!

**Comment by sydney-runkle** [comment]
Sure thing! Glad I could be of help 👍
