### ISSUE TITLE
`from_attributes=True` is ignored when validating a standard library datclass against a Pydantic dataclass

### ISSUE THREAD

**Issue by Hellzed** [pydantic/pydantic#7805]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using a Pydantic dataclass with `TypeAdapter`, calling `validate_python(...)` on an arbitrary standard library dataclass instance raises a `pydantic_core._pydantic_core.ValidationError`, whether or not `from_attributes=True` is present.

The message is the same: `Input should be a dictionary or an instance of ...`.

Because:
- this works with Pydantic models inheriting from `BaseModel`;
- expecting only a dictionary or an instance of the validation dataclass more or less defeats the purpose of `from_attributes=True`;
- iirc this did not affect Pydantic v1 ORM mode;

I assume this is a bug.

### Example Code

```Python
import dataclasses

import pydantic
from pydantic import TypeAdapter, BaseModel


class ValidationModel(BaseModel):
    message: str


@pydantic.dataclasses.dataclass
class ValidationDataclass:
    message: str


@dataclasses.dataclass
class Data:
    message: str


model_validator = TypeAdapter(ValidationModel)
print(model_validator.validate_python(
    Data(message="hello BaseModel!"), from_attributes=True)
)

dataclass_validator = TypeAdapter(ValidationDataclass)
print(dataclass_validator.validate_python(
    Data(message="hello dataclass!"), from_attributes=True)
)
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/loris/.cache/pypoetry/virtualenvs/fastapi-pydantic-v2-QLAxixyf-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  9 2023, 07:59:55) [GCC 12.3.0]
                     platform: Linux-6.2.0-33-generic-x86_64-with-glibc2.37
             related packages: fastapi-0.103.2 typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @Hellzed,

Thanks for reporting this 😄. We actually don't currently support `from_attributes` specification when using `TypeAdapter` with a `pydantic` dataclass. This is part of the reason why (pydantic) dataclass validation is actually faster than BaseModel validation. Thus, this actually isn't a bug, but more of a feature request, and one that isn't currently on our roadmap.

That being said, I do think that this is certainly under-documented, so I'll plan to add a docs update to reflect this more clearly in order to address this issue 👍.
