### ISSUE TITLE
Field not excluded when using `exclude_unset`

### ISSUE THREAD

**Issue by vigneshmanick** [pydantic/pydantic#7811]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am trying to replicate a behaviour that we have in our v1 model in v2 without success .

A field that is `None` is set a value via a model_validator and i would like this field to be excluded from output. This works in V1 but not in V2. 

Any pointers on how to replicate this behaviour in v2?

See the example code below,  `pet_name` should be excluded from output when `exclude_unset` is set and if it was `None` since the value is determined and set by the validator.

### Example Code

```Python
# Test_v1.py

from pydantic.v1 import BaseModel, root_validator
from typing import Optional


class TestModel(BaseModel):
    pet: str
    pet_name: Optional[str]

    @root_validator(pre=False)
    def set_control(cls, values):
        if values["pet_name"] is None:
            values["pet_name"] = values["pet"]
        return values


model = TestModel(**{"pet": "muffin"})
print(model.__fields__)


print(
    model.dict(
        exclude_unset=True,
    )
)

# {'pet': ModelField(name='pet', type=str, required=True), 'pet_name': ModelField(name='pet_name', type=Optional[str], required=False, default=None)}
# Note that here the `pet_name` has a default=None
# {'pet': 'muffin'}


# Test_v2.py
from typing import Optional

from pydantic import BaseModel, Field, model_validator


class TestModel(BaseModel):
    pet: str
    pet_name: Optional[str] = Field(None)

    @model_validator(mode="after")
    def set_control(self):
        if self.pet_name is None:
            self.pet_name = self.pet
        return self


model = TestModel(**{"pet": "muffin"})
print(model.model_fields)

print(
    model.model_dump(
        exclude_unset=True,
    )
)

# {'pet': FieldInfo(annotation=str, required=True), 'pet_name': FieldInfo(annotation=Union[str, NoneType], required=False)}
# Note that here the `pet_name` has no default
# {'pet': 'muffin', 'pet_name': 'muffin'}  `pet_name` is present in the output
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
pydantic-core version: 2.10.1
pydantic-core build: profile=release pgo=false
install path: /scratch/miniconda3/envs/pydantic-v2/lib/python3.11/site-packages/pydantic
python version: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
platform: Linux-3.10.0-1160.45.1.el7.x86_64-x86_64-with-glibc2.17
related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @vigneshmanick,

So the docs say that the collection of `model_fields_set` comes from 

Thanks for reporting this. However, the observed behavior that you're seeing comes from these lines in the `__setattr__` function attached to a `BaseModel` instance:

https://github.com/pydantic/pydantic/blob/2ace8cba52abe37e1d567dc010fc51f9556fbff2/pydantic/main.py#L800-L802

As you can see, whenever an attribute is set that is one of the fields of the model, we add that to `self.__pydantic_fields_set__`, thus the reason why any such field is included in the `model_dump`, even when `exclude_unset=True` is set.

So one major issue here is the inconsistencies in the docs. For example, we specify that `model_fields_set`
> Returns the set of fields that have been set on this model instance

which I think is a good description such that you'd expect the behavior you're seeing above. That being said, we also define `__pydantic_fields_set__` as
> An instance attribute with the names of fields explicitly specified during validation

Which I understand is quite misleading for your use case.

I think the right path forward here is to update the docs to consistently reflect the first definition. I'll also note that the behavior for `__setattr__` was the same in v1, it's just that said function wasn't called due to the setup of your `set_control` root validator.

Regarding your question about replicating such behavior, you could do the following:
```py
from pydantic import BaseModel, Field, ValidationInfo, field_validator
from typing import Optional


class TestModel(BaseModel):
    pet: str
    pet_name: Optional[str] = Field(default=None)

    @field_validator('pet_name')
    @classmethod
    def set_control(cls, v: str, info: ValidationInfo) -> str:
        return v or info.get('pet')


model = TestModel(**{"pet": "muffin"})
print(model.model_fields)
#> {'pet': FieldInfo(annotation=str, required=True), 'pet_name': FieldInfo(annotation=Union[str, NoneType], required=False)}


print(model.model_dump(exclude_unset=True))
#> {'pet': 'muffin'}

print(model.model_dump())
#> {'pet': 'muffin', 'pet_name': None}
```

**Comment by dmontagu** [comment]
@vigneshmanick you can also just manually control the fields set to reflect that you really do want it to be treated as unset, it's just a one line change to your code:
```python
        if self.pet_name is None:
            self.pet_name = self.pet
            self.model_fields_set.discard('pet_name')  # <---- add this
```

as in:
```python
from typing import Optional

from pydantic import BaseModel, Field, model_validator


class TestModel(BaseModel):
    pet: str
    pet_name: Optional[str] = Field(None)

    @model_validator(mode="after")
    def set_control(self):
        if self.pet_name is None:
            self.pet_name = self.pet
            self.model_fields_set.discard('pet_name')
        return self


model = TestModel(**{"pet": "muffin"})
print(
    model.model_dump(
        exclude_unset=True,
    )
)
#> {'pet': 'muffin'}
```

**Comment by vigneshmanick** [comment]
Thanks for the explanation was very helpful in understanding.
