### ISSUE TITLE
AttributeError: __pydantic_private__

### ISSUE THREAD

**Issue by blacktoby** [pydantic/pydantic#7855]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hey everyone,
I stumbled upon this issue when building classes, with BaseModel and another class as parents, after upgrading to pydantic v2.
In my case:
```python
class MyClass(BaseModel, tf.keras.layers.Layer):
    ...
```
When the non-pydantic base class wants to set a private variable in its `__new__` function, it will raise this error:
```python
  File "pydantic/main.py", line 768, in __setattr__
    if self.__pydantic_private__ is None or name not in self.__private_attributes__:
  File "pydantic/main.py", line 756, in __getattr__
    return super().__getattribute__(item)  # Raises AttributeError if appropriate
```

Since I am not able to change anything on the implementation of the `tf.keras.layers.Layer` class, this is a critical problem for me.
For a minimal, reproducible example, see the example code below.

Is there any way to fix this?

### Example Code

```Python
from typing import Any
from pydantic import BaseModel


class SomeParent:

    def __new__(cls, *args, **kwargs):
        instance = super(SomeParent, cls).__new__(cls, *args, **kwargs)
        instance._random_variable = 123
        return instance


class MyModelChild(BaseModel, SomeParent):

    def __init__(self, **data: Any):
        super().__init__(**data)


if __name__ == "__main__":
    MyModelChild()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /path/to/python3.8/site-packages/pydantic
               python version: 3.8.18 (default, Sep 11 2023, 13:40:15)  [GCC 11.2.0]
                     platform: Linux-5.4.0-131-generic-x86_64-with-glibc2.17
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @blacktoby,

Thanks for reporting this. This issue is stemming from the fact that you're attempting to set a private attribute on an instance of `BaseModel` before `__init__` is called. `__init__` is where the setup of `__pydantic_private__` occurs for `BaseModel` instances, hence the issue here.

If it's possible, I'd recommend that you refactor such that you don't have a class inheriting from both `BaseModel` and `tf.keras.layers.Layer`. Perhaps you could store `Layer` information in a field on your BaseModel and access methods + features of said attribute from there.

If you really need to maintain the structure of your code, I think you'd have to override the `__setattr__` method on your child class in order to get this to work, but I'd warn that you risk compromising the integrity of much of the `BaseModel` logic by doing this.

Hope this helps. Happy to answer any questions you might have!

**Comment by sydney-runkle** [comment]
Hey @blacktoby,

Closing this for now. I hope our suggestions were helpful - let me know if you have any follow up questions. Happy to reopen / consider a PR if you have any suggestions as to how the behavior on the `pydantic` end could change in a non-breaking fashion!
