### ISSUE TITLE
Set arbitrary_types_allowed to True by default

### ISSUE THREAD

**Issue by timonbimon** [pydantic/pydantic#809]
# Feature Request

Since the behavior if `arbitary_types_allowed` is set to `True` seems quite natural to me, I'd like to suggest setting it to True by default for the upcoming 1.0 release of Pydantic.

Happy to hear your thoughts. :)

**Comment by samuelcolvin** [comment]
Sorry for the slow response.

I can see the argument, but I don't have a strong opinion.

My initial concern was that this could lead to untrusted data making it through validation, and also that user's may not notice that types are missing the `__get_validators__` classmethod etc. but almost all types' validation methods allow instances of themselves with no further validation.

Does anyone else have a strong opinion?

**Comment by retnikt** [comment]
I would argue that this should remain False by default, but we should have the option to validate specific classes in Config, e.g.

```py
class CustomType:
    ...

class Model(pydantic.BaseModel):
    a: int
    b: CustomType
    class Config(pydantic.BaseConfig):
        custom_types = [CustomType]
```
(though that would be a full feature request, not just a change and might be unrealistic for v1.0)

**Comment by samuelcolvin** [comment]
Validating specific class is done by implementing the `__get_validators__` class method.

I think I should have changed this in v1, let's change it in v2.

**Comment by lig** [comment]
As of today the change looks too big for v2. There is a lot in that pile already.

Such a drastic change in behavior will break a lot of code while everyone who needs this has `arbitary_types_allowed: True` set explicitly already anyway.

Closing as `won't fix`.

**Comment by dmontagu** [comment]
I think it's a good idea to keep this flag `False` by default as it ensures you must acknowledge that you are using a type that won't get proper validation.

However, one thing I think might make sense is to deprecate this config setting and introduce an annotation that results in the same behavior (i.e., validating instances). So instead of:
```python
class MyModel:
    x: MyArbitraryType
    model_config = dict(arbitrary_types_allowed=True)
```
you'd do:
```
class MyModel:
    x: Annotated[MyArbitraryType, pydantic.ValidateInstances]
```
or similar (maybe we could find a pithier name for this `ValidateInstances` thing).

One significant upshot of this approach would be that you'd know _precisely_ which types it is applying to, rather than potentially applying to any field, also it ensures you wouldn't miss the inheritance of the `arbitrary_types_allowed` config setting from parent classes.
