### ISSUE TITLE
Optional + default value not compatible with annotated fields

### ISSUE THREAD

**Issue by kevhill** [pydantic/pydantic#8118]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In following the [notes ](https://docs.pydantic.dev/latest/concepts/fields/#numeric-constraints)on how to best include compound types and constraints, I ran into an issue where pydantic kept insisting that a field was required when I thought I had properly allowed it to be `None`. In investigating the issue I think I have a good simply summary of it:

The ability to have an optional value with a default value is not compatible with defining the default value through an annotated field.

### Example Code

```Python
from typing import Optional
from typing_extensions import Annotated
from pydantic import BaseModel, Field

class OptionalFieldsTest(BaseModel):
    w1: Optional[str] = None
    w2: Optional[str] = Field(default=None)
    w3: Optional[Annotated[str, Field(description='this works!')]] = None
    w4: Annotated[str, Field(default=None)]
    e1: Optional[Annotated[str, Field(default=None)]]


# all the w fields are proper ways of defining defaults
OptionalFieldsTest.model_validate({'e1': 'required'})

# returns error that e1 is missing
OptionalFieldsTest.model_validate({})
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.0
        pydantic-core version: 2.14.1
          pydantic-core build: profile=release pgo=true
                 install path: /usr/local/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun  7 2023, 19:32:10) [GCC 10.2.1 20210110]
                     platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
             related packages: typing_extensions-4.8.0
```

**Comment by kevhill** [comment]
Interestingly, this seems to be at least a partially known issue in v1.X, as this gives an error `ValueError: `Field` default cannot be set in `Annotated` for 'w4'` in v1.10.13. But that default does in fact work for non-optional fields now in V2, so maybe this has a similar root cause?

**Comment by Viicos** [comment]
`e1` is equivalent to `Annotated[str, Field(default=None)] | None`, which feels a bit weird: the default value only applies to `str`, and not to the complete type, so Pydantic probably infers it as a required value in the end.

It doesn't really make sense to use `Annotated` this way though, `Annotated[str | None, Field(default=None)]` should be better (or even `str | None = None` if you don't need to specify anything else in `Field`).

One of `Annotated`'s goals is to be more intuitive about default values.
- Without `Annotated`, we would use `my_field: int = Field(description=...)`, which is counterintuitive as it makes people think `my_field` is not required because it has a _defaut value_ (in Python terms, not Pydantic!)
- With `Annotated`, we would use `my_field: Annotated[int, Field(description=...)]` (and specify a default with ` = ...`, not `Field(default=...)`).

---

The only case where we would apply `Optional[...]` or similar on top of `Annotated` is for constraints on compound types as mentioned in the linked docs, but `Field` arguments should only be related to the type it directy applies to:

`my_field: Annotated[Annotated[int, Field(ge=0)] | None, Field(description=...)]` (although a bit ugly)

**Comment by sydney-runkle** [comment]
I agree with @Viicos here.

This line especially explains why `e1` isn't behaving as you'd expect:
> e1 is equivalent to Annotated[str, Field(default=None)] | None, which feels a bit weird: the default value only applies to str, and not to the complete type, so Pydantic probably infers it as a required value in the end.

Given that, I don't think it makes sense to support the syntax you've used for `e1`.

**Comment by kevhill** [comment]
Yeah, I think that makese sense, though it would be nice to have a bit more consistency to lessen the learning curve. To me, it almost looks like you are suggesting that `default` should just be deprecated from `Field()`. Eg, the example

```Annotated[str, Field(description='foo', default=None)]```

is nearly identical to the error case, except for the `Optional[]` but works just fine. It seems like the preferred syntax for that would be

```w4: Annotatted[str | None, Field(description='foo')]```

I completely agree with taking a stance on that proper formatting, and that the proposed format seems sensible, but it would be great if the documentation and API were consistently aligned with that intent.

**Comment by sydney-runkle** [comment]
@kevhill,

Any interest in opening a PR with updates to the docs to reflect that logic more consistently?
