### ISSUE TITLE
Enums are not converted with extra="allow"

### ISSUE THREAD

**Issue by mr-yurii** [pydantic/pydantic#8143]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

If you set `use_enum_values=True, extra="allow"` in model config and then try to create a class with extra fields that are enum instances, you expect all enums should be converted to their values, but in fact they are not converted. I tried to provide good example so you can execute it in python console and see what happens.

### Example Code

```Python
from enum import IntEnum
from pydantic import BaseModel, ConfigDict


class MyEnum(IntEnum):
    one = 1
    two = 2


class MyEnum2(IntEnum):
    three = 3
    four = 4


class A(BaseModel):
    my_enum: MyEnum = MyEnum.one

    model_config: ConfigDict = ConfigDict(validate_default=True, use_enum_values=True, extra="allow")


input_date = {"second_enum": MyEnum2.three}

item = A.model_validate(input_date)  # A(my_enum=1, second_enum=<MyEnum2.three: 3>)

item.model_dump()  # {'my_enum': 1, 'second_enum': <MyEnum2.three: 3>}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.0
        pydantic-core version: 2.14.1
          pydantic-core build: profile=release pgo=false
                 install path: ***
               python version: 3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.6.1-x86_64-i386-64bit
             related packages: fastapi-0.103.1 typing_extensions-4.8.0 email-validator-2.1.0.post1
```

**Comment by sydney-runkle** [comment]
@mr-yurii,

Thanks for reporting this. This is similar to other issues reported regarding `use_enum_values`, such as this one: https://github.com/pydantic/pydantic/issues/7757.

The explanation for this behavior is that the choice to store an `Enum` value as its value occurs during validation for each field. Thus, this logic isn't applied to `extra` fields. That's why you get the result that you're seeing when you call `model_dump`, as this transformation isn't done during serialization, which is a common misconception.

I can see an argument for adding a `use_enum_values` flag to `model_dump` and friends, but currently, this is the expected behavior. Let me know if you have any follow up questions!
