### ISSUE TITLE
Better support for JSON schema for `Callable` validators

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#8208]
This isn't a high priority, but I think we could add better default support for `Callable` type validator JSON schemas, as well as changing the docs to reflect how to change the default schema in these cases.

See more info here: https://github.com/pydantic/pydantic/issues/7957

**Comment by Viicos** [comment]
Was hit by this, and here is a use case that could be interesting and would avoid some boilerplate:

```python
from typing import Annotated, Any

from pydantic import BaseModel, BeforeValidator

def _from_string(value: Any):
    if isinstance(value, string):
        return value.split(".")
    return value


class Model(BaseModel):
    screen_position: Annotated[tuple[int, int], BeforeValidator(_from_string)]
```

Ideally for `BeforeValidator`, the JSON schema should be updated (in `validation` mode only) if the callable allow different types (in this case `string`).

Currently, `WithJsonSchema` can be used, but really verbose: 

```python
class Model(BaseModel):
    screen_position: Annotated[tuple[int, int], BeforeValidator(_from_string), WithJsonSchema({'anyOf': [{'maxItems': 2, 'minItems': 2, 'prefixItems': [{'type': 'integer'}, {'type': 'integer'}], 'type': 'array'}, {'type': 'string'}]})]
```

Two solutions I've been thinking about:
- Infer the JSON schema from the type hint of the provided callable to `BeforeValidator`:
```python
def _from_string(value: tuple[int, int] | str):  # Infer JSON schema from this type
    ...
```
Could be confusing, because in theory before validator can take any type. Plus, how to handle untyped callables?
- Add an extra argument to `BeforeValidator`/`field_validator` (when `mode='before'`): `BeforeValidator(_from_string, new_type=tuple[int, int] | str)`

**Comment by sydney-runkle** [comment]
Also relevant for `PlainSerializer` annotations: https://github.com/pydantic/pydantic/issues/8548 (comes as a surprise to some users)

**Comment by sydney-runkle** [comment]
This would be great, but isn't super high priority right now.

**Comment by Viicos** [comment]
I'd like to pick this one up at some point as it would help unblock one issue I had
