### ISSUE TITLE
Union uses field `default` value instead of raising a ValidationError

### ISSUE THREAD

**Issue by nlsfnr** [pydantic/pydantic#8210]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using a `default` value or `default_factory` for a field that is a union between two (or more) Pydantic models, `model_validate` does not raise a `ValidationError` when all members of the union fail to match the data. Instead, it populates the field with its default value, silently dropping the data that was passed in and passing validation. Please see the example below.

The expected behaviour would be for `model_validate` to raise a ValidationError if none of the members match the data.

Adding the `strict=True` flag to `model_validate` does nothing.

### Example Code

```Python
import pydantic

class A(pydantic.BaseModel):
    a: str = 'a'

class B(pydantic.BaseModel):
    b: int = 1

class C(pydantic.BaseModel):
    u: A | B = A()

print(C.model_validate({'u': {'a': 'valid'}}))      # gives u=A(a='valid'), as expected
print(C.model_validate({'u': {'b': 'invalid'}}))    # gives u=A(a='a'), expected ValidationError

try:
    print(C(u=B.model_validate({'b': 'invalid'})))  # ValidationError, as expected
except pydantic.ValidationError as e:
    print(e)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: /home/nf/.local/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
                     platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.31
             related packages: mypy-1.4.1 typing_extensions-4.7.1
```

EDIT:

After some playing around, providing a default on the union (i.e. `C`'s `u` field) is not the cause of the behaviour. If no default is provided, Pydantic simply choses the first member of the union, provided it has defaults, as in the example. Removing the defaults from the union member types (i.e. `A` and `B` in the example) results in a ValidationError, as expected.

**Comment by dmontagu** [comment]
This is intended behavior — A allows extra data so it does pass validation and just grabs the default value.

If you want to disallow extra fields, you can put `extra='forbid'` in the model config and you'll get the error I think you are expecting:

```python
import pydantic

class A(pydantic.BaseModel, extra='forbid'):
    a: str = 'a'

class B(pydantic.BaseModel):
    b: int = 1

class C(pydantic.BaseModel):
    u: A | B = A()

print(C.model_validate({'u': {'b': 'invalid'}}))
"""
pydantic_core._pydantic_core.ValidationError: 2 validation errors for C
u.A.b
  Extra inputs are not permitted [type=extra_forbidden, input_value='invalid', input_type=str]
    For further information visit https://errors.pydantic.dev/2.4/v/extra_forbidden
u.B.b
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='invalid', input_type=str]
    For further information visit https://errors.pydantic.dev/2.4/v/int_parsing
"""
```

This isn't an issue due to the use of Union — the crux of the issue is that the following works because extra inputs are ignored by default:
```python
import pydantic

class A(pydantic.BaseModel):
    a: str = 'a'

print(A.model_validate({'b': 'invalid'}))
#> a='a'
```

There is no way to _automatically_ say "if I'm using a union and I get a field that matches one of the cases, only check against that case, not the others that might be ignoring it". But I'll note that you could implement something more careful along these lines using a [callable discriminator](https://docs.pydantic.dev/latest/concepts/unions/#discriminated-unions-with-callable-discriminator).

Of course you can also just forbid extra inputs if that works for your use case; if you want to do that for all models you can just create a common base class:
```python
from pydantic import BaseModel


class MyBaseModel(BaseModel):
    model_config = {'extra': 'forbid'}
```
and then inherit from `MyBaseModel` with all your custom models.

**Comment by samuelcolvin** [comment]
Great answer, thank you @dmontagu.

**Comment by nlsfnr** [comment]
Thank you very much @dmontagu ! I now see where that behaviour comes from. Obvious in hindsight, thanks to a good explanation :)
