### ISSUE TITLE
It is possible to instantiate model with `model_config` field without exceptions

### ISSUE THREAD

**Issue by tribunsky-kir** [pydantic/pydantic#8469]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello!

I am aware that `model_config` should be `ConfigDict()` and this is class/instance attribute as written in documentation.

I was trying to fix this behavior for my local very specific case (sometimes I run into ML code, so `model_config` in class definition is pretty common field to have) with one more indirection and manual creation of models, BUT I've found something surprising and odd (cases are below).

The most confusing thing is that usually pydantic just fails **before** execution of `if __name__ == '__main__':` block with `PydanticUserError`, but doesn't do it, if user may define his own models in a strange way.

### Case 1: `model_config` presents in `__annotations__`, is absent in `model_fields` and does nothing silently

Expected behavior: 

- PydanticUserError: message that "model_config" shouldn't be overridden.
- (OR at least) UserWarning: Field "model_config" has conflict with protected namespace "model_".

```python
from pydantic import BaseModel


class MyModel(BaseModel):
    model_config: str


if __name__ == '__main__':
    m = MyModel(model_config='Test')
    print(m.model_config)
    """
    {}
    """
```

### Case 2: `model_config` is set, deprecated `class Config` is used and the field is properly set!

Expected behavior: `pydantic.errors.PydanticUserError: "Config" and "model_config" cannot be used together` before execution of `if __name__ == '__main__':` block

```
from pydantic import BaseModel


class MyModel(BaseModel):
    model_config: str

    class Config:
        extra = 'allow'
        protected_namespaces = ()


if __name__ == '__main__':
    # Expected behavior: `pydantic.errors.PydanticUserError: "Config" and "model_config" cannot be used together` before execution of `if __name__ == '__main__':` block
    print(MyModel(model_config='Test'))
    """
    model_config='Test'
    """
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /Users/username/local/venvs/311/projectname/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 mypy-1.8.0 pydantic-settings-2.1.0
```

**Comment by sydney-runkle** [comment]
@tribunsky-kir,

I'd agree that the error messages (or warning messages) could be improved in the above cases. I'll leave this issue open as an opportunity to improve those.

There is not currently support for having a field named `model_config`, and I don't think that is something we're likely to support in the near future.

**Comment by alexeyt101** [comment]
Hey there!
I'd like to work on this. Is it possible?

**Comment by sydney-runkle** [comment]
@alexeyt101,

Sure thing! Go for it!

**Comment by alexeyt101** [comment]
Hello, guys, sorry for the late response
I've checked the docs for contributors and the code.
I'd like to discuss the changes a little bit.

In total we have only one case (in this issue and in [#8840](https://github.com/pydantic/pydantic/issues/8840)): when `model_config` is used as a property. The case 2 from the @tribunsky-kir message is the same because if you use `model_config` and class-based Config in a correct way but together you'll get `pydantic.errors.PydanticUserError: "Config" and "model_config" cannot be used together` (check the conforming test [here](https://github.com/pydantic/pydantic/blob/main/tests/test_config.py#L84))

So, I think we should only react to the case when `model_config` is used as a property. 
We can split in into two cases:
1. when model_config is used **without** default value
```python
class MyModel(BaseModel):
	model_config: str
```
In this case we can raise `PydanticUserError` because this way leads to wrong behavior.

2. when model_config is used **with** default value which is not `ConfigDict`
```python
class MyModel(BaseModel):
	model_config: dict = {'foo': 'foo'}
```
Here we can use a warning message with recommendations of ConfigDict usage instead of `PydanticUserError` to avoid problems in existed applications using Pydantic

@sydney-runkle 
I'm not sure about the above offers
Can you help to decide what option will be better for the project?

**Comment by sydney-runkle** [comment]
@alexeyt101,

Thanks for following up! We're excited to have you contribute.

Agreed, we need to address the case where `model_config` is defined as a property. I agree with your first thought, that we should emit a more helpful warning when `model_config` is used as a property with no default.

For the second case, we actually do allow users to specify `model_config` as a dictionary (not a `ConfigDict` instance), so I don't think we should emit the warning in this case.

Hope that helps - let me know if you have any more questions + ping me when you'd like a PR review :).

**Comment by alexeyt101** [comment]
@sydney-runkle, hello!
Please, check the PR when it'll be possible :)
