### ISSUE TITLE
Support for "const" in JSON Schema broke Swagger / OpenAPI Spec 3 

### ISSUE THREAD

**Issue by mtasic85** [pydantic/pydantic#8565]
In OpenAPI Spec 3, "const" is not valid attribute of type.

https://github.com/pydantic/pydantic/blame/5de67f7c4f775b5319af9be157f9c7b68995eb1e/pydantic/json_schema.py#L735-L736

**Comment by sydney-runkle** [comment]
https://github.com/OAI/OpenAPI-Specification/issues/1666#issuecomment-533759198

Hmm, seems to be supported in OpenAPI 3.1 as a JSON schema keyword, and has been since the `2019-09` draft. Closing for now, as I don't think we need to make a change on the `pydantic` end.

Lmk if there's something I'm missing here!

If you need to use a much older version of OpenAPI, you could use a custom JSON schema generator.
