### ISSUE TITLE
Json field type hinting issues

### ISSUE THREAD

**Issue by stopdropandrew** [pydantic/pydantic#8616]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using `Json` wrapped types, I've noticed that VSCode (and mypy) treat the field as the wrapped type. This is great for interacting with the model instance, but during model creation it's still expected that the value comes in as a `str`.

In my example below, I believe the ctor should have the type:
```python
class Foo(
    *,
    bar: str
)
```

Thanks for the help, love this project!

### Example Code

```Python
from pydantic import BaseModel, Json

class Foo(BaseModel):
    bar: Json[dict[str, str]]


# Argument of type "Literal['{"abc": "def"}']" cannot be assigned to parameter "bar" of type "Json[dict[str, str]]" in function "__init__"
#   "Literal['{"abc": "def"}']" is incompatible with "Json[dict[str, str]]"PylancereportGeneralTypeIssues
# Argument "bar" to "Foo" has incompatible type "str"; expected "dict[str, str]"Mypyarg-type
Foo(bar='{"abc": "def"}')

# No errors
Foo(bar={"abc": "def"})
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /Users/agrim/Library/Caches/pypoetry/virtualenvs/creator-conv-ai-platform-E3Bq-xxG-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Jul 28 2023, 12:58:31) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.3-arm64-arm-64bit
             related packages: email-validator-2.0.0.post2 fastapi-0.100.1 pyright-1.1.336 typing_extensions-4.8.0 mypy-1.7.1 pydantic-settings-2.1.0
```

**Comment by Viicos** [comment]
This is a more general limitation with [`dataclass_transform`](https://docs.python.org/3/library/typing.html#typing.dataclass_transform), which cannot take into account the type conversion. This example will also fail:

```python
from pydantic import BaseModel

class Foo(BaseModel):
    bar: int

Foo(bar="1")
```

You can make use of the [`mypy` plugin](https://docs.pydantic.dev/dev/integrations/mypy/), however I'm not sure if it covers the `Json` type yet, to be tested.

**Comment by sydney-runkle** [comment]
Similar issue: https://github.com/pydantic/pydantic/issues/8591

**Comment by dmontagu** [comment]
So, this is in principle something we could handle better in the mypy plugin but I wouldn't be excited about maintaining it.

@Viicos is right that it is a fundamental limitation of dataclass_transform that it can't give a different type hint in the `__init__` signature than for the field itself. (At least not yet? I'm not sure if anything is in the works to change that but I would be surprised.) This is more generally the case any time you have a non-idempotent type annotation, specifically where the type required for input to validation is different than the output of validation.

I think the primary use case for the `Json[T]` type is scenarios where you aren't instantiating the type directly but relying on calls to `model_validate` or similar where you don't need to worry about the types in the `__init__` signature.

You could get the `__init__` signature to allow `str` by just doing `Json[T] | str` or `Json[T] | Annotated[str, AfterValidator(always_raise_an_error)]` to prevent it from allowing non-JSON strings, but then access to the attribute will be incorrect.

If there is significant community interest in augmenting the mypy plugin with support for this I think it would be possible, but hard to justify otherwise. But if someone else wants to implement it I suppose I would be happy to review a PR adding the support. (Specifically, making the type hint in `__init__` be `str` but not changing the type of the attribute on the actual class or `model_construct`.) Note that even if we did add support for this, it would not affect pyright or IDEs.

**Comment by sydney-runkle** [comment]
Thanks @dmontagu for a great explanation.

So this issue is quite similar in general to this issue: https://github.com/pydantic/pydantic/issues/8336.

I'm going to close this as a duplicate, though this issue will be linked to that one, so if we decide to do anything, we'll be addressing questions from both of these + be able to reference thoughts on both 👍.

As a side note - I wonder if it's worth adding an update to the `mypy` plugin docs re non-idempotent types.
