### ISSUE TITLE
Datetime validation works incorrectly after Pydantic 2.6 with range parametrized APIs in FastAPI

### ISSUE THREAD

**Issue by MarkusSintonen** [pydantic/pydantic#8736]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We are using FastAPI with various APIs using datetime ranges in URL path parameters. After trying 2.6 we get large amount of test failures due to Pydantic 2.6 incorrectly allowing dates in datetime range URL params. Now suddenly this is allowed: `some/path/2024-01-01/2024-01-04`. Previously it was blocked as path params are datetime validated. Now the dates magically coerce incorrectly to midnights where range suddenly gets to `[2024-01-01T00:00:00, 2024-01-04T00:00:00]`. But obviously this is unexpected and incorrect as the range-end is at midnight.

How do we block this bad behaviour in all our APIs (in context of range usage) with Pydantic 2.6? This seems to be no FastAPI issue as only change we did was trying out Pydantic 2.6.

### Example Code

```Python
async def test_pydantic_breakage():
    @dataclass
    class SharedTimeRangeParams:
        start_time: datetime = Path(..., description="Query timerange start UTC date-time", examples=["2017-07-21T17:32:28Z"])
        end_time: datetime = Path(..., description="Query timerange end UTC date-time", examples=["2017-07-21T17:32:28Z"])

    app = FastAPI()

    @app.get("/some/path/{start_time}/{end_time}")
    async def handler(time_range: SharedTimeRangeParams = Depends()):
        return {"start": time_range.start_time, "end": time_range.end_time}

    client = TestClient(app)
    # Ok
    res = await client.get("/some/path/2024-01-01T00:00:00Z/2024-01-02T23:59:59.999Z")
    assert res.json() == {"start": "2024-01-01T00:00:00+00:00", "end": "2024-01-02T23:59:59.999000+00:00"}

    # Broken in 2.6
    res = await client.get("/some/path/2024-01-01/2024-01-02")
    # In 2.6 end is at midnight which doesn't make sense for API usage in the range param
    # assert res.json() == {"start": "2024-01-01T00:00:00+00:00", "end": "2024-01-02T00:00:00+00:00"}

    # This doesn't work in 2.6 anymore
    assert "Input should be a valid datetime" in res.json()["detail"][0]["msg"]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=false
                 install path: {omitted}/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 (main, Dec  7 2023, 20:45:44) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-14.3-x86_64-i386-64bit
             related packages: typing_extensions-4.9.0 fastapi-0.109.0 mypy-1.4.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@MarkusSintonen,

You should be able to use `strict` mode on your `datetime` types to disallow this behavior. See this example:
https://github.com/pydantic/pydantic/issues/8363#issuecomment-1921604135.

You can also use something like:
```py
dt: datetime = Field(..., strict=True)
```

I'm going to leave this issue open as a docs issue - this question has come up 2x already since the 2.6 release, so I think it'd be helpful for us to more publicly document this behavior :).

Let me know if you have any follow up questions :).

**Comment by miikka** [comment]
For context, Markus is my colleague so there's only one team having this problem 🙂 

If you enable strict mode, the `# Ok` case will not work anymore. I believe this is because FastAPI uses `TypeAdapter.validate_python` to coerce path parameters from strings and if strict mode is enabled, it will only accept datetimes, not strings.

**Comment by miikka** [comment]
I'm thinking of working around the issue by setting the type to `start_time: Annotated[datetime, PlainValidator(...)]` etc. and writing my own datetime validator.

**Comment by davidhewitt** [comment]
We have implemented [`TypeAdapter.validate_strings`](https://docs.pydantic.dev/latest/api/type_adapter/#pydantic.type_adapter.TypeAdapter.validate_strings) which we believe is the correct solution for FastAPI to adopt in this case. I don't think anyone has found time to try to get this adopted downstream, however.

(IIRC, `validate_strings` is designed to accept the Ok case in strict mode.)

**Comment by Kxnr** [comment]
We have independently encountered this issue, though we're not using fastapi. In our case, we're using an `AfterValidator` to require that all values are given timezones by the user. While we can use strict mode in our case (or otherwise work around this change), it is surprising to have an inferred timezone.

**Comment by davidhewitt** [comment]
@Kxnr inference of timezone is a separate question to coercion of date strings to midnight datetimes. However, I can reproduce and agree that's a bug. I'll open a separate issue.

**Comment by davidhewitt** [comment]
For what it's worth, @Kxnr you can use `pydantic.AwareDatetime` to require a timezone instead of your own `AfterValidator`, might be a touch more efficient.

And @MarkusSintonen @miikka maybe this also hints at a workaround for you too: if we fix the datetime bug then you could use `AwareDatetime` on this field. It would force your users to add timezone information, but it would also avoid this coercion.

> But obviously this is unexpected and incorrect as the range-end is at midnight.

This is an interesting point, as a more helpful coercion for you would have been to be `23:59:59` on the second parameter. I guess you could take `date | datetime` union yourself to intercept & override this coercion. Maybe it could also be an option on `Field` to ban this coercion, but it's already so overloaded...

**Comment by sydney-runkle** [comment]
Putting this here as a reference for others in the future:

```py
from datetime import datetime

from pydantic import TypeAdapter, ValidationError

ta = TypeAdapter(datetime)
print(ta.validate_strings('2024-01-01', strict=False))
#> 2024-01-01 00:00:00

try:
    print(ta.validate_strings('2024-01-01', strict=True))
except ValidationError as e:
    print(e)
    """
    1 validation error for datetime
    Input should be a valid datetime, invalid datetime separator, expected `T`, `t`, `_` or space [type=datetime_parsing, input_value='2024-01-01', input_type=str]
        For further information visit https://errors.pydantic.dev/2.7/v/datetime_parsing
    """
```
