### ISSUE TITLE
Mypy pydantic plugin comparaison no error

### ISSUE THREAD

**Issue by tyki6** [pydantic/pydantic#8773]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

With mpy pydantic plugin enable when i enable strict equality pydantic comparaison not generate error when i write mistake error

### Example Code

```Python
[tool.mypy]
plugins = "pydantic.mypy"
ignore_missing_imports = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
follow_imports = "normal"
show_column_numbers = true
strict_optional = true
warn_redundant_casts = true
pretty = false
strict = true
warn_unused_ignores = true
check_untyped_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_untyped_decorators = false
strict_equality = true
[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true


```python
from pydantic import BaseModel
class User(BaseModel):
    username: str
user = User(username="test")
print(user == "test") # no error
print(user.username == [1,2,3]) # no error
print(user.username == "test") 
```
```bash
mypy .
```
I got:
```bash
Success: no issues found
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=trueC
               python version: 3.12.1 (main, Dec  7 2023, 20:45:44) [GCC 11.4.0]
                     platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: pydantic-settings-2.1.0 mypy-1.8.0 fastapi-0.109.0 typing_extensions-4.9.0 email-validator-2.1.0.post1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@dmontagu,

Could you please take a look at this! Thanks :).

**Comment by dmontagu** [comment]
@tyki6 what version of mypy are you using?

I checked both mypy v1.8.0 and v1.1.1 in both, I get:
```
/Users/davidmontague/Library/Application Support/JetBrains/PyCharm2023.3/scratches/scratch.py:14:7: error: Non-overlapping equality check (left operand type: "str", right operand type: "list[int]")  [comparison-overlap]
```
on the line with `user.username == [1,2,3]`, which you seemed to mark as `# no error`. That said, I also get an error on the previous line if I change it to a dataclass, but not with BaseModel.

I suspect the reason for this is that we have defined `__eq__` method on BaseModel with other as `Any`. If we hide that `__eq__` from the type-checker using `if not typing.TYPE_CHECKING`, the issue goes away, so that may be the best fix, I'll run that by the other maintainers and if they agree we can merge it. (Another alternative may be to change the type hint on the `other` argument to `__eq__` but I'm more concerned that changing that may affect other users.
