### ISSUE TITLE
Type `IPv4Address` not parsed

### ISSUE THREAD

**Issue by Kyomotoi** [pydantic/pydantic#8942]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Running example code, get:
```
PydanticJsonSchemaWarning: Default value 127.0.0.1 is not JSON serializable; excluding default from JSON schema [non-serializable-default]
  warnings.warn(message, PydanticJsonSchemaWarning)
```
It seems that pydantic v2 not parsing the type `IPv4Address`

### Example Code

```Python
from ipaddress import IPv4Address

from pydantic import BaseModel
from pydantic.networks import IPvAnyAddress


class IpModel(BaseModel):
    ip: IPvAnyAddress = IPv4Address("127.0.0.1")  # type: ignore


print(IpModel.model_json_schema())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.2
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /Users/kyomotoi/Library/Caches/pypoetry/virtualenvs/nbtest-d74D2RO--py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.3-arm64-arm-64bit
             related packages: fastapi-0.110.0 typing_extensions-4.10.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@Kyomotoi,

Thanks for the report. This should be relatively easy to fix. I'll note - this can't be solved with `validate_default=True`.

**Comment by NeevCohen** [comment]
@sydney-runkle I'd like to work on this if it's still available 😄

**Comment by NeevCohen** [comment]
I started looking into this a little bit and it seems the issue is with the serialization of `IPv4Address` and `IPv6Address` in pydantic-core ( or rather any type that is not implemented in [`ObType`](https://github.com/pydantic/pydantic-core/blob/71d54a243f52550847716cb4208944667ebc16ee/src/serializers/ob_type.rs#L383)

I wrote the following test

```python
@pytest.mark.parametrize('ip_address', (IPv4Address('127.0.0.1'), (IPv6Address('::1'))))
def test_ipv4_address_parsing(ip_address):
    class IpModel(BaseModel):
        ip: IPvAnyAddress = ip_address

    print(IpModel.model_json_schema())
```

This eventually calls [`to_jsonable_python`](https://github.com/pydantic/pydantic/blob/18d39febf00cb07954e19ebbdbd8168ef20e3df1/pydantic/json_schema.py#L1997) in pydantic-core which throws a `PydanticSerializationError`. I looked a little at the code in pydantic-core and `to_jsonable_python` accepts a `serialize_unknown` parameter which as far as I understand, if it is True, will stringify the `IPv4Address` object. If I change [`encode_default`](https://github.com/pydantic/pydantic/blob/18d39febf00cb07954e19ebbdbd8168ef20e3df1/pydantic/json_schema.py#L1985) to
 
```python
    def encode_default(self, dft: Any) -> Any:
        """Encode a default value to a JSON-serializable value.

        This is used to encode default values for fields in the generated JSON schema.

        Args:
            dft: The default value to encode.

        Returns:
            The encoded default value.
        """
        config = self._config
        return pydantic_core.to_jsonable_python(
            dft,
            timedelta_mode=config.ser_json_timedelta,
            bytes_mode=config.ser_json_bytes,
            serialize_unknown=True
        )
```

The test I wrote passes.

So as I see it there are 2 ways to handle this. We can add a parameter to the `BaseModel.model_json_schema` method and pass it down to the `to_jsonable_python` function.

On the other hand, we could add a support specifically for `IPv4Address` and `IPv6Address` in the [`infer_serialize_known`](https://github.com/pydantic/pydantic-core/blob/4a533aa93da212e959572e28866afe551f811fa2/src/serializers/infer.rs#L331) function.

I think the first solution is better since it allows pydantic to optionally serialize any type which defines a `__str__` method.

Example usage 

```python
class Person:
    def __init__(self, name: str):
        self.name = name
    
    def __str__():
        return self.name

class MyModel(BaseModel):
    person: Any = Person('Steve')

print(MyModel.model_json_schema(serialize_unknown=True))  # outputs {'properties': {'person': {'default': 'Steve', 'title': 'Person'}}, 'title': 'MyModel', 'type': 'object'}
```

@sydney-runkle WDYT?

**Comment by davidhewitt** [comment]
I think as `IPv4Address` is so far handled just in `pydantic`, I think it'd be better to keep the change out of core for now. I wonder, can we change `encode_default` to build a `TypeAdapter` for the field and then serialize using `adapter.dump_python(mode="json")`? That seems like the most general and correct fix. I don't think `encode_default` will be called in a hot loop, so I'd hope for this to be fine?
