### ISSUE TITLE
Return default value if the input is `None`

### ISSUE THREAD

**Issue by Ravencentric** [pydantic/pydantic#8972]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Let's take this simple model as an example
```py
>>> from pydantic import BaseModel
>>>
>>>
>>> class Foo(BaseModel):
...     bar: list[int] | None = [0,1,2]
...     baz: list[str] | None = ["a", "b", "c"]
...
>>> Foo()
Foo(bar=[0, 1, 2], baz=['a', 'b', 'c'])

>>> Foo(bar=[1,2], baz=["a","b"])
Foo(bar=[1, 2], baz=['a', 'b'])

>>> Foo(bar=None, baz=None) # Explicitly pass `None`
Foo(bar=None, baz=None) # Current Behavior

>>> Foo(bar=None, baz=None) # Explicitly pass `None`
Foo(bar=[0, 1, 2], baz=['a', 'b', 'c']) # Feature request: Return default value if the input is `None`, possibly a model setting in ConfigDict?
```

There already seems to be some demand for this:
- https://github.com/pydantic/pydantic/issues/1851
- https://stackoverflow.com/questions/63428454/can-i-make-a-default-value-in-pydantic-if-none-is-passed-in-the-field-without-us

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@Ravencentric,

I think it probably makes sense to use a custom validator for this. For example:

```py
from pydantic import BaseModel, ValidationInfo, field_validator


class Foo(BaseModel):
    bar: list[int] | None = [0,1,2]
    baz: list[str] | None = ["a", "b", "c"]

    @field_validator('bar', 'baz')
    @classmethod
    def check_alphanumeric(cls, v: str, info: ValidationInfo) -> str:
        if v is None:
            return cls.model_fields[info.field_name].default
        return v

print(repr(Foo()))
# Foo(bar=[0, 1, 2], baz=['a', 'b', 'c'])

print(repr(Foo(bar=[1,2], baz=["a","b"])))
# Foo(bar=[1, 2], baz=['a', 'b'])

print(repr(Foo(bar=None, baz=None))) # Explicitly pass `None`
# Foo(bar=[0, 1, 2], baz=['a', 'b', 'c'])
```

I haven't seen an abundance of demand for this feature. If there's significant community interest, we could reconsider making this a flag on a field, but for now I think the field validator approach (a change in user code) makes the most sense!

**Comment by yotaro-shimose** [comment]
@sydney-runkle 
Thank you for the example.

Can we do the same in BeforeValidator? I love the Annotated + Validator pattern as it provides stronger reusability. But I couldn't access the default value information in the validator function in this case.

Specifically I'd like to do something like this.
```python
def validator(v: Any, info: ValidationInfo) -> Any:
    print(
        info
    )  # ValidationInfo(config={'title': 'MyClass'}, context=None, data={}, field_name='field')
    if v is None:
        default = get_default_somehow()
        return default
    return v


class MyClass(BaseModel):
    field: Annotated[int, Field(default=0), BeforeValidator(validator)]


MyClass.model_validate({"field": None})
```

Although I can explicitly add BeforeValidator like following, writing default value twice looks a bit weird.

```python
def null_default_validator(default: Any) -> BeforeValidator:
    def validator(v: Any) -> Any:
        if v is None:
            return default
        return v

    return BeforeValidator(validator)


class MyClass(BaseModel):
    field: Annotated[int, Field(default=0), null_default_validator(default=0)]


MyClass.model_validate({"field": None})
```

**Comment by tsalex1992** [comment]
I have to say that I would have wanted this feature.
Here is my usecase - I'm getting a serialized api request to my service - and the sender doesn't have the option to exclude undefined fields, so they have to send them as nulls which get serialized to None in python.

The thing is - that I already have a default value which I want this field to take in the case it is None.
Right now the default value works only for the case it haven't been sent(undefined).

I want an option to configure this behavior so it'll use the default on None as well - it will give me more freedom.
Otherwise what I need to do is to manually populate the field in the validator - or in usage always check if the field is not None which is redundunt.

**Comment by saurookadook** [comment]
@yotaro-shimose and @tsalex1992 - Just in case you might find it helpful, our team encountered a slightly similar issue and came up with [another possible solution](https://github.com/pydantic/pydantic/issues/9083#issuecomment-2018971746). 

Sadly, it doesn't fit with the Annotated + Validator pattern but it _is_ fairly reusable. With your `Foo` example above, for instance:

```python
# some/path/to/utils.py
def generic_validator_function_with_default(class_ref, value, info):
    return (
        value
        if value is not None
        else get_default_value_from_field_config(class_ref, info)
    )


def get_default_value_from_field_config(class_ref, info):
    field = class_ref.model_fields[info.field_name]
    return field.default_factory() if callable(field.default_factory) else field.default


# some/path/to/models/foo.py
from some.path.to.utils import generic_validator_function_with_default

class Foo(BaseModel):
    bar: list[int] | None = [0,1,2]
    baz: list[str] | None = ["a", "b", "c"]

    @field_validator('bar', 'baz')
    @classmethod
    def handle_field_default(cls, value, info):
        return generic_validator_function_with_default(cls, value, info)
        
```

**Comment by yotaro-shimose** [comment]
@saurookadook 
Thank you for your suggestion. I love that example as it shows good reusability.

As your workaround says, it might be good to have reference to the class to be wrapped in function validators. Hopefully it works with python Annotated syntax so that pydantic maintainers can implement it.

**Comment by MarkusSagen** [comment]
Having this syntax would be great for shared library code as well
Is there anything one can do to help out on this issue?

**Comment by sydney-runkle** [comment]
@MarkusSagen,

I'd be happy to review a PR with support for this via a field flag if the API is pretty clean, given that there seems to be a decent amount of requests for this. I think we want to do this on the field level and not the config level, but I'm not sure...

**Comment by Ravencentric** [comment]
In the API I'm dealing with, I needed it globally on every model so a model_config level would be appreciated

**Comment by MarkusSagen** [comment]
Thank you @sydney-runkle 
Do you have any pointers for which file the changes would be placed in
I've not yet worked with the internals of Pyadntic

**Comment by DmytroHrabovyi** [comment]
Being able to set defaults like this would also be useful for the cases when using `ConfigDict(from_attributes=True)` mode, which is going to remove the need to validate each field which could possibly be `None`  in the database.

**Comment by Adrian-at-CrimsonAzure** [comment]
After a bit of tinkering, I arrived independently arrived at a similar solution to @saurookadook which is added to our common `BaseModel` that contains our configuration and util functions:
```python
    @field_validator("*", mode="before")
    @classmethod
    def not_none(cls, v, val_info):
        """
        Convert None to Default on optional fields.
        Why doesn't Pydantic have this option?
        """
        field = cls.__fields__[val_info.field_name]
        if v is None and (default := field.get_default(call_default_factory=True)) is not None:
            return default
        return v
```
This could also be broken out into a function and called with `_not_none = field_validator("my_field", "my_field2")(not_none)` or used inside a `WrapValidator`, but in our case any `Optional` field can potentially be populated with `None` when we'd rather have our default values.

I'd still rather have a `Field(replace_none_with_default=True)` option though.

**Comment by liang-cicada** [comment]
Here's another solution.
`from pydantic import BaseModel, model_validator

from typing import Optional

class TestModel(BaseModel):
    name: str
    age: Optional[int]=0
    
    @model_validator(mode='before')
    @classmethod
    def remove_none(cls, data):
        if isinstance(data, dict):
            return {k: v for k, v in data.items() if v is not None}
        return data

data = {"name": "test", "age": None}
model = TestModel(**data)`

**Comment by AdrianB-sovo** [comment]
See also this: https://github.com/pydantic/pydantic/discussions/8585
But for that, we would need to have access to the model's class inside ValidationInfo.

**Comment by Kalebe16** [comment]
After some studies I came to this result, it works, but it is extremely inelegant, it would be great if pydantic already did this by default, having to create this subclass is not the best thing in the world as I have to duplicate this in all my python packages, or create another python package just for this code below, either way, it's not elegant

```python
from typing import Dict, Any
from pydantic import BaseModel
from pydantic_core import PydanticUndefinedType

class CustomBaseModel(BaseModel):
    @model_validator(mode='before')
    def set_defaults_for_none(cls, values: Dict[str, Any]):
        fields = cls.model_fields
        for field_name, field_info in fields.items():
            value = values.get(field_name)
            default_value = (
                field_info.default
                if not isinstance(field_info.default, PydanticUndefinedType)
                else None
            )
            default_factory = (
                field_info.default_factory
                if not isinstance(
                    field_info.default_factory, PydanticUndefinedType
                )
                else None
            )

            if value is None:
                if default_value is not None:
                    values[field_name] = default_value
                elif default_factory is not None:
                    values[field_name] = default_factory()

        return values

```

**Comment by umar-anzar** [comment]
> @Ravencentric,

> I haven't seen an abundance of demand for this feature. If there's significant community interest, we could reconsider making this a flag on a field, but for now I think the field validator approach (a change in user code) makes the most sense!

I typically use Pydantic schema classes in GPT prompts to ensure the response is in JSON format. However, when the GPT model doesn't find a value for a field, it initializes the field with None instead of using the default value. This issue suggests the need for a flag in the field class to handle such cases appropriately.

**Comment by sydney-runkle** [comment]
Semi-related, the `example` in this section: https://docs.pydantic.dev/latest/concepts/json/#partial-json-parsing

**Comment by dcosson** [comment]
Going back to the @Ravencentric's original example, IMO the current behavior is actually preferable as written because the type annotation marked the field as optional (`list[int] | None`). In that case it makes sense that None should be an allowed value that you can explicitly pass in.

However I think in most cases if you have a default value to use for a field then you don't want that field to be optional.

For example:
```
class Foo(BaseModel):
    bar: list[int]= [0,1,2]

Foo()
# Foo(bar=[1,2,3])

Foo(bar=None)
# raises ValidationError 
```
In that case it would be preferable if it used the default value instead of raising an error.


The model_validator workaround that others mentioned does work, but that also raises the question why doesn't a mode="before" field validator work? That part is very unexpected that the None type validation runs before the validator when the validator was supposed to happen before.

**Comment by k4nar** [comment]
Based on the example suggested by @sydney-runkle, this seems to be working well and should contend everyone in this thread :slightly_smiling_face: :
```python
from pydantic import BaseModel, field_validator
from pydantic_core import PydanticUseDefault


class Foo(BaseModel):
    bar: list[int] = [0,1,2]
    baz: list[str] = ["a", "b", "c"]

    @field_validator("*", mode="before")
    @classmethod
    def none_to_default(cls, v):
        if v is None:
            raise PydanticUseDefault()
        return v

assert Foo(bar=None, baz=None) == Foo()
```

**Comment by Meetesh-Saini** [comment]
Hey @sydney-runkle, I'd like to work on this. I agree with @dcosson's suggestion, so I made some local changes to pydantic-core, and this is what I have so far:
```py
from typing import Optional
from pydantic import BaseModel

class Foo(BaseModel):
    bar: list[int] = [0, 1]
    baz: list[int] = [2, 3]
    daz: list[int] = [4, 6]
    caz: Optional[list[int]] = [0, 0]
    faz: Optional[list[int]] = [7, 8]

print(Foo(bar=[9, 0], daz=None, caz=None))
# bar=[9, 0] baz=[2, 3] daz=[4, 6] caz=None faz=[7, 8]
```

I think an API like the following would work well for everyone,
```py
class Foo(BaseModel):
    # explicitly `True`, overrides `Config`
    bar : list[int] = Field(default=[1,2], none_as_default=True)

    # explicitly `False`, overrides `Config`
    baz : list[int] = Field(default=[1,2], none_as_default=False)
    
    # behaviour depends on `Config`
    bar : list[int] = Field(default=[1,2])

    class Config:
        # default `True`
        none_as_default = False
```

**Comment by dromer** [comment]
While raising `PydanticUseDefault()` works well for us in practice, this is now causing errors in our test suite:

`pydantic_core._pydantic_core.SchemaError: Uncaught UseDefault error, please check your usage of `default` validators.`

**Comment by Viicos** [comment]
We tend to avoid adding new parameters/flags to the core API of Pydantic (fields, config, `model_dump_*`/`model_validate_*` methods) if this can be implemented relatively easily using validators. Moreover, one could then request _I want to use the default value if `MyNoneTypeSingleton` is provided_, making the `none_as_default` not extensible.

Here is a simple way to implement such a behavior:

```python
from pydantic import AfterValidator, BaseModel
from pydantic_core import PydanticUseDefault

from typing import Annotated, TypeVar, Any


def default_if_none(value: Any) -> Any:
    if value is None:
        raise PydanticUseDefault()
    return value


T = TypeVar('T')

DefaultIfNoneV1 = Annotated[T, AfterValidator(default_if_none)]
DefaultIfNoneV2 = Annotated[T | None, AfterValidator(default_if_none)]


class Foo(BaseModel):
    bar: DefaultIfNoneV1[list[int] | None] = [0, 1, 2]
    # or:
    # baz: DefaultIfNoneV2[list[int]] = [0, 1, 2]

Foo(bar=None)
#> Foo(bar=[0, 1, 2])
```

**Comment by k4nar** [comment]
However `PydanticUseDefault` should be documented, it’s not the case today.

**Comment by changhc** [comment]
Sorry about raising this when things are already being implemented, but is this really a valid feature? I stand with @dcosson's comment and to me this is like breaking type checking. Allowing `None` when a field is not optional will never work in a strongly typed language and the point of pydantic is to provide such a guardrail in typing from what I understand. Also, how does one deal with type-checking like mypy or pylance with this feature?

Default values set like the following should be sufficient, essentially identical to having default arguments for the initialiser:
```py
class Foo(BaseModel):
    bar: list[int]= [0,1,2]

Foo()
```

Even if we really want to go with this feature, that `none_as_default` config value should default to `False` to keep the existing behaviour.

**Comment by AdrianB-sovo** [comment]
@changhc Only if you use Pydantic as some kind of dataclass in your code and ignore the other important feature of Pydantic: JSON serialization/deserialization.
Sometimes, you want to deserialize a structure where fields can be `null` in the JSON — which isn't always generated by your own service/code —, but you don't want to always have to handle the possible `None` values in your code (e.g. only handle `list[str]` instead of `list[str] | None`). 
So, in your code, the values always match your type hints and only the frontier between your code and the JSON input handle the `None` value.

**Comment by Viicos** [comment]
https://github.com/pydantic/pydantic/pull/11060 is a complete rewrite of the validators documentation, and [`PydanticUseDefault`](https://validators-docs.pydantic-docs.pages.dev/api/pydantic_core/#pydantic_core.PydanticUseDefault) is now documented in the [utilities types](https://validators-docs.pydantic-docs.pages.dev/concepts/validators/#special-types).


> While raising `PydanticUseDefault()` works well for us in practice, this is now causing errors in our test suite:
> 
> `pydantic_core._pydantic_core.SchemaError: Uncaught UseDefault error, please check your usage of `default` validators.`

@dromer this error happens when no default value is provided for a field.

Marking the issue as resolved. Please let us know if `PydanticUseDefault` does not fulfill your needs.

**Comment by dromer** [comment]
> @dromer this error happens when no default value is provided for a field.

That is not the case in our code. We did explicitly set a default value and expected it to be used.
It works in production but our test suite fails with this error on the same object.

I will try to collect a minimum test case and create a new ticket later.

**Comment by Ronnocerman** [comment]
@Viicos 

I think I have a nice and ergonomic solution.

As far as I can tell Pydantic does not have an easy way to optionally specify parameters.

What I mean is if you had:

```
class SomeModel(BaseModel):
  a: int = 1
  b: str = "2"
  c: int = 3

def get_model(a: Optional[int] = None, b: Optional[str] = None, c: Optional[int] = None) -> SomeModel:
  SomeModel(
    a = a,
    b = b,
    c = c,
  )
```

Then you're not obeying proper typing in get_model, and further-- if you were to call

`foo = get_model()`

a,b, and c would be initialized to None.

As far as I can tell, there's no ergonomic way to provide multiple parameters like this. There are a few ways this might be accomplished that I find unergonomic. For instance--

Using a param dict is unergonomic due to extra local variables and the fact that you now have to stringify the param names:
```
def get_model(a: Optional[int] = None, b: Optional[str] = None, c: Optional[int] = None) -> SomeModel:
  param_dict = {"a": a, "b": b, "c": c}
  SomeModel(
    **{key: value for key, value in param_dict.items() if value is not None}
  )
```

Mutating the model is unergonomic due to changing the field values after creation, which negates the ability to make them frozen and it also introduces another local variable and branching flow conditionals:

```
def get_model(a: Optional[int] = None, b: Optional[str] = None, c: Optional[int] = None) -> SomeModel:
  model = SomeModel()
  if a is not None:
    model.a = a
  if b is not None:
    model.b = b
  if c is not None:
    model.c = c
  return model
```

Inspecting the defaults is unergonomic due to verbosity and the fact that if the model name changes, you'll have more fields to update.

```
def get_model(a: Optional[int] = None, b: Optional[str] = None, c: Optional[int] = None) -> SomeModel:
  return SomeModel(
    a = a if a is not None else SomeModel.model_fields["a"],
    b = b if b is not None else SomeModel.model_fields["b"],
    c = c if c is not None else SomeModel.model_fields["c"],
  )
```

I also find it quite unergonomic to need to add validators that raise "PydanticUseDefault" for None values (and it also excludes the ability to use None as an explicit value).

Might I propose the ability to use PydanticUseDefault like so:

```
def get_model(a: Optional[int] = None, b: Optional[str] = None, c: Optional[int] = None) -> SomeModel:
  SomeModel(
    a = a if a is not None else PydanticUseDefault(),
    b = b if b is not None else PydanticUseDefault(),
    c = c if c is not None else PydanticUseDefault(),
  )
```

Having a magic value that is interpreted to mean "Actually use the default, even though I provided a field".

I think it's miles more ergonomic than the alternatives, and is more maintainable at scale. Theoretically, it also satisfies the "Use None as default" case really well too. All that one would have to do is map "None" to "PydanticUseDefault()" in the values before passing them to the constructor. You wouldn't even need to update the model to add a validator.


My proposal would make it easy to

**Comment by TomW1605** [comment]
> > [@dromer](https://github.com/dromer) this error happens when no default value is provided for a field.
> 
> That is not the case in our code. We did explicitly set a default value and expected it to be used. It works in production but our test suite fails with this error on the same object.
> 
> I will try to collect a minimum test case and create a new ticket later.

did you ever work out a why this was happening in your test suite? im running into the same issue despite explicitly setting a default.

**Comment by Viicos** [comment]
@TomW1605 if you have a MRE of the issue you are encountering I can take a look.

**Comment by TomW1605** [comment]
> [@TomW1605](https://github.com/TomW1605) if you have a MRE of the issue you are encountering I can take a look.

i dont right now, i will try and write one tomorrow.

**Comment by TomW1605** [comment]
ok, wasnt able to reproduce this and turns out its on me. i thought all the fields had a default but there was one that had an alias but no default and because it had the = and the Field object i missed that there was no default there.

that does bring up another point though, the error message `Uncaught UseDefault error, please check your usage of default validators` is not very helpfull. i think it would be better here if raising `PydanticUseDefault` on a field without a default acted the same as if you hadnt provided any value (since that is basically what is happening) and gave the full standard missing value error message so you know where it is erroring.

either that, or is there a way to check if a default exists before raising `PydanticUseDefault` or catch the `SchemaError` when there is no default so we can handle it manually? (@Viicos i am using your `default_if_none` function)

**Comment by Viicos** [comment]
As `PydanticUseDefault` is used in the body of the validators, Pydantic can't know in advance (during model creation) if it is used. However, I improved the error message in https://github.com/pydantic/pydantic-core/pull/1730.
