### ISSUE TITLE
Pydantic URL doesn't have decode attribute.

### ISSUE THREAD

**Issue by ssaini-phyllo** [pydantic/pydantic#9056]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

While parsing URL of type pydantic URL, I am getting exception 
AttributeError: 'pydantic_core._pydantic_core.Url' object has no attribute 'decode'

### Example Code

```Python
from urllib.parse import urlparse

HttpUrl = Annotated[Url, UrlConstraints(max_length=2083, allowed_schemes=['http', 'https'])]

url = parse_obj_as(HttpUrl, url)
parsed_url = urlparse(url)
```

### Python, Pydantic & OS Version

```Text
pydantic version - 2.6.4
urllib3 - 1.26.18
fastapi - 0.110.0
starlette - '0.36.3'
python - 3.9.8
OS - MacOS
```

**Comment by sydney-runkle** [comment]
@ssaini-phyllo,

You can just do `urlparse(str(url))`, as `urlparse` takes a `str` url argument. Though just as a general note, I'd recomment using `TypeAdapter` instead of `parse_obj_as`. Also, a pydantic `Url` has all of the features that you might want from `urlparse` (host, fragment, etc), so not sure why you need it in the first place.

See this performance example in the docs for more context: https://docs.pydantic.dev/latest/why/#performance
