### ISSUE TITLE
Schema for `Literal` differs between version 2.6 and 2.7 

### ISSUE THREAD

**Issue by vigneshmanick** [pydantic/pydantic#9402]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The schema for the fields that are marked `Literal` is different between versions 2.6 and 2.7.

The version 2.7 has both `enum` and `const` as keys in the schema. See example below. Is this expected? 

### Example Code

```Python
from pydantic import BaseModel, Field
from typing import Literal

class Base(BaseModel):
    type: str = Field(
        ...,
    )

class MyModel(Base):
    type: Literal["modela"]

MyModel.model_json_schema()

#Pydantic v2.6
#{'properties': {'type': {'const': 'modela', 'title': 'Type'}},
# 'required': ['type'],
# 'title': 'MyModel',
# 'type': 'object'}

# Pydantic v2.7
#{'properties': {'type': {'const': 'modela',
#   'enum': ['modela'],
#   'title': 'Type',
#   'type': 'string'}},
# 'required': ['type'],
# 'title': 'MyModel',
# 'type': 'object'}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
pydantic-core version: 2.18.2
pydantic-core build: profile=release pgo=false
install path: /scratch/mv/myprograms/miniconda3/envs/pydantic2.7/lib/python3.11/site-packages/pydantic
python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
platform: Linux-3.10.0-1160.45.1.el7.x86_64-x86_64-with-glibc2.17
related packages: typing_extensions-4.11.0
commit: unknown
```

**Comment by lindapaiste** [comment]
> The version 2.7 has both `enum` and `const` as keys in the schema. See example below. Is this expected?

Worth noting that @dmontagu raised concerns when this was introduced in #8944
> However, I think we should be careful about merging this, as any change to the JSON schema usually comes with some complaints. In particular, it's probably a good idea to track down the initial commit adding the use of constant and **determine if it might be a problem to include the duplicate information about the enum value.**

Having both `enum` and `const` properties isn't valid under the OpenAPI spec and it breaks some of the tools that consume the JSON output.

I'm having similar problems but in my case I am not using the `Literal` type at all.  The `const` property will get added to all `Enum` types which have only one value, whether or not `Literal` is used.  Is that supposed to be happening?

https://github.com/pydantic/pydantic/blob/4d7bef62aeff10985fe67d13477fe666b13ba070/pydantic/json_schema.py#L778-L780

**Comment by vigneshmanick** [comment]
thanks for the info. I feel this should not be the case? it should either be `const` or `enum` but not both for the same field. 

In our case, our documentation generation script output the field `type` to have 2 available values `modela` and again `enum: modela`  which is confusing for those reading the documentation.  I feel it should either have one value only or atleast this be an opt in

**Comment by lindapaiste** [comment]
Consider the following code example:
```py
from enum import Enum

from pydantic import BaseModel

from typing_extensions import Literal


class SpeciesEnum(str, Enum):
    CAT = 'cat'


class PetWithEnum(BaseModel):
    name: str
    species: SpeciesEnum


class PetWithLiteral(BaseModel):
    name: str
    species: Literal['cat']


print(PetWithEnum.model_json_schema())

print(PetWithLiteral.model_json_schema())
```

Here's the raw output across 3 different Pydantic versions.

Version 1.10 used `'enum': ['cat'], 'type': 'string'`
```
PetWithEnum
{'title': 'PetWithEnum', 'type': 'object', 'properties': {'name': {'title': 'Name', 'type': 'string'}, 'species': {'$ref': '#/definitions/SpeciesEnum'}}, 'required': ['name', 'species'], 'definitions': {'SpeciesEnum': {'title': 'SpeciesEnum', 'description': 'An enumeration.', 'enum': ['cat'], 'type': 'string'}}}

PetWithLiteral
{'title': 'PetWithLiteral', 'type': 'object', 'properties': {'name': {'title': 'Name', 'type': 'string'}, 'species': {'title': 'Species', 'enum': ['cat'], 'type': 'string'}}, 'required': ['name', 'species']}
```

Version 2.6 used `'const': 'cat', 'type': 'string'`
```
PetWithEnum
{'$defs': {'SpeciesEnum': {'const': 'cat', 'title': 'SpeciesEnum', 'type': 'string'}}, 'properties': {'name': {'title': 'Name', 'type': 'string'}, 'species': {'$ref': '#/$defs/SpeciesEnum'}}, 'required': ['name', 'species'], 'title': 'PetWithEnum', 'type': 'object'}

PetWithLiteral
{'properties': {'name': {'title': 'Name', 'type': 'string'}, 'species': {'const': 'cat', 'title': 'Species'}}, 'required': ['name', 'species'], 'title': 'PetWithLiteral', 'type': 'object'}
```

Version 2.7 uses `'const': 'cat', 'enum': ['cat'], 'type': 'string'`
```
PetWithEnum
{'$defs': {'SpeciesEnum': {'const': 'cat', 'enum': ['cat'], 'title': 'SpeciesEnum', 'type': 'string'}}, 'properties': {'name': {'title': 'Name', 'type': 'string'}, 'species': {'$ref': '#/$defs/SpeciesEnum'}}, 'required': ['name', 'species'], 'title': 'PetWithEnum', 'type': 'object'}

PetWithLiteral
{'properties': {'name': {'title': 'Name', 'type': 'string'}, 'species': {'const': 'cat', 'enum': ['cat'], 'title': 'Species', 'type': 'string'}}, 'required': ['name', 'species'], 'title': 'PetWithLiteral', 'type': 'object'}
```

In every version there is no fundamental difference between the model which uses a `Literal` string `'cat'` and the model which uses a string `Enum` that happens to have only one value.  

IMO, there probably should be more of a difference between the two setups.  I would think that the `Literal` version would have `'const': 'cat'` and the `Enum` version would have `'enum': ['cat']`.

There needs to be some way for me to tell Pydantic what form of output I want.  Maybe it's an option, maybe it's by using `Literal` or not.

---

Here's how the `SpeciesEnum` looks across the versions.  IMO 2.7 is an improvement over 2.6 because 2.6 feels like a mistake -- this is defined as an `Enum` so it should be an enum whether it has one value or two.

Considering the code:
```python
class SpeciesEnum1(str, Enum):
    CAT = 'cat'

class SpeciesEnum2(str, Enum):
    CAT = 'cat'
    DOG = 'dog'
```

Version 1.10 - both have `enum` only
```
'SpeciesEnum1': {
  'title': 'SpeciesEnum1',
  'description': 'An enumeration.',
  'enum': ['cat'],
  'type': 'string'
},
'SpeciesEnum2': {
  'title': 'SpeciesEnum2',
  'description': 'An enumeration.',
  'enum': ['cat', 'dog'],
  'type': 'string'
}
```

Version 2.6 - one has `const` only and the other has `enum` only
```
'SpeciesEnum1': {
  'const': 'cat',
  'title': 'SpeciesEnum1',
  'type': 'string'
},
'SpeciesEnum2': {
  'enum': ['cat', 'dog'],
  'title': 'SpeciesEnum2',
  'type': 'string'
}
```

Version 2.7 - one has both `const` and `enum` and the other has `enum` only
```
'SpeciesEnum1': {
  'const': 'cat',
  'enum': ['cat'],
  'title': 'SpeciesEnum1',
  'type': 'string'
}, 
'SpeciesEnum2': {
  'enum': ['cat', 'dog'],
  'title': 'SpeciesEnum2',
  'type': 'string'
}
```

**Comment by austinyu** [comment]
According to the specification of json schema for [enum](https://json-schema.org/draft/2020-12/json-schema-validation#name-enum) and [const](https://json-schema.org/draft/2020-12/json-schema-validation#name-const), 

> "Use of this keyword is functionally equivalent to an enum with a single value."

From json schema perspective, it does not matter if the generated json schema is `enum` or `const` or both. 
However, if there are considerable amount of consumers of the generated schema that distinguish between the two, we should distinguish `enum` with one value from `const`. Currently, we are kind of relying on `Literal` type hint for both cases because there is no type hint for `const` yet. If we need it, may be we can do something like this? 

```
class DiffModel(BaseModel):
    const_field: CONST['this_is_constant']
    lit_field: Literal['this_is_constant']
```

Output of json schema: 

```
'const_field': {
  'const': 'this_is_constant',
  'title': 'ConstField',
  'type': 'string'
}, 
'lit_field': {
  'enum': ['this_is_constant'],
  'title': 'LitField',
  'type': 'string'
}
```

Explicitly providing an annotation for people who actually need `const` json schema validation keyword in my opinion is a more scalable solution than keep mutating the behavior of `Literal` annotation,

**Comment by dmontagu** [comment]
@lindapaiste can you point me at some reference indicating that including both `enum` and `const` in the same schema is invalid? Or at some tools that mishandle that scenario? If I recall correctly, I added both because it _fixed_ misbehavior in a tool that I was using that consumed the openapi schema, so it isn't _universally_ problematic 😅 but I would consider it a higher priority to have a more first-class solution for modifying the JSON schema for this if different tools need different behavior to behave correctly.

I'll note that there is a built-in way to override JSON schema generation in pydantic — subclassing `GenerateJsonSchema` — but I'm not sure if fastapi provides a way to specify this currently. For reference (and possibly useful as a workaround for others), I used this code prior to #8944 being merged, which monkeypatches the `GenerateJsonSchema` type used by fastapi:
```python
class CustomGenerateJsonSchema(GenerateJsonSchema):
    def literal_schema(self, schema: core_schema.LiteralSchema) -> JsonSchemaValue:
        """Generates a JSON schema that matches a literal value.
        Args:
            schema: The core schema.
        Returns:
            The generated JSON schema.
        """
        expected = [v.value if isinstance(v, Enum) else v for v in schema['expected']]
        # jsonify the expected values
        expected = [to_jsonable_python(v) for v in expected]

        result: dict[str, Any] = {'enum': expected}
        if len(expected) == 1:
            result['const'] = expected[0]

        types = {type(e) for e in expected}
        if types == {str}:  # pragma: no branch
            result['type'] = 'string'
        elif types == {int}:  # pragma: no cover
            result['type'] = 'integer'
        elif types == {float}:  # pragma: no cover
            result['type'] = 'number'
        elif types == {bool}:  # pragma: no cover
            result['type'] = 'boolean'
        elif types == {list}:  # pragma: no cover
            result['type'] = 'array'
        return result


# Patch the fastapi GenerateJsonSchema to use our custom one
fastapi.openapi.utils.GenerateJsonSchema = CustomGenerateJsonSchema  # type: ignore
```

**Comment by dmitrysleptsov** [comment]
Hey @dmontagu 👋 ,
I will try to provide more info if you don't mind.

> Or at some tools that mishandle that scenario?

I noticed this behavior in FastAPI autogenerated API docs. These are examples of how it looks in Swagger and ReDoc.
Example code:
```python
from pydantic import BaseModel


class Message(BaseModel):
    field: Literal["value"]
```

**Swagger**
![image](https://github.com/pydantic/pydantic/assets/61187246/581d895d-9c85-434b-a202-157affb8895e)

**ReDoc**
![image](https://github.com/pydantic/pydantic/assets/61187246/4e20be36-285e-4f82-8314-94e8e235fe26)


In Swagger UI it doesn't look that bad, but in ReDoc it looks a bit confusing. 


>can you point me at some reference indicating that including both enum and const in the same schema is invalid?

TBH, from a JSON-schema perspective, there are no restrictions about including both of them. At least, I didn't find anything in the documentation for [enum](https://json-schema.org/understanding-json-schema/reference/enum) or [const](https://json-schema.org/understanding-json-schema/reference/const). I'm not an expert, just sharing what I've found 😄 .


> If I recall correctly, I added both because it fixed misbehavior in a tool that I was using that consumed the openapi schema, so it isn't universally problematic 😅

As I understand, it was added because of [this issue](https://github.com/pydantic/pydantic/issues/8905). It looks like the problem was in this [early return](https://github.com/pydantic/pydantic/pull/8944/files#diff-a85df49955cda137dd8914c5c2c662511c672ae6519fbee16e689997e9923c65L736) that returned before `type` field was added. For me, everything works (including the correct type for Literal) if I make the following changes in this part: https://github.com/pydantic/pydantic/blob/4d7bef62aeff10985fe67d13477fe666b13ba070/pydantic/json_schema.py#L778-L780

```diff
- result: dict[str, Any] = {'enum': expected}
- if len(expected) == 1:
-     result['const'] = expected[0]
+ result: dict[str, Any] = {'const': expected[0]} if len(expected) == 1 else {'enum': expected}
```

**Comment by tomasmorello** [comment]
Hi @dmontagu,

I think that indeed there is an issue. If you try to run the output through swagger, it will say it's invalid as:

> should NOT have additional properties
 additionalProperty: const

This is being throw each time that const & enum are generated (At least is what I receive).

```
components:
  schemas:
    ServiceProvider:
      properties:
        Name:
          type: string
          enum:
            - ProviderA
          title: Name
```

However, each time I delete the const from the schema it will pass the verification. I've also tried to keep the const and removing the enum, but that doesn't fix the issue.

**Comment by Viicos** [comment]
> I think that indeed there is an issue. If you try to run the output through swagger, it will say it's invalid as:

You shouldn't get any issues with https://editor-next.swagger.io/

**Comment by Viicos** [comment]
Here is what I propose:

```python
class MultiEnum(Enum):
    A = 'a'
    B = 'b'

class SingleEnum(Enum):
    A = 'a'

class Model(BaseModel):
    f1: MultiEnum      # --> {'type': 'string', enum: ['a', 'b']}
    f2: SingleEnum    # --> {'type': 'string', enum: ['a']}
    f3: Literal['a']        # --> {'type': 'string', const: 'a'}
    f4: Literal['a', 'b']  # --> {'type': 'string', enum: ['a', 'b']}
```

- Always generate an `enum` for enums, even if it contains a single member.
- Generate a `const` for single literals, `enum` for multiple values in a literal.

It was mentioned in this thread that `enum` was added because it would otherwise misbehave in a tool consuming the generated schema; but in that case it seems best to fix the issue on the consumer side

**Comment by sydney-runkle** [comment]
@Viicos,

This seems like a good plan forward to me. Wdyt @dmontagu?
