### ISSUE TITLE
Pydantic v2 no longer seems to parse "dict-able" objects

### ISSUE THREAD

**Issue by gygabyte017** [pydantic/pydantic#9406]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi, I'm porting an application from pydantic v1 to v2, I'm getting issues when parsing `Record` objects coming from `asyncpg` package (https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg.Record).

Here's what I did with pydantic v1:
- fetching data from postgres connection using `asyncpg`
- it returns a `list[Record]`
- I parse the list with `parse_obj_as` against a pydantic model which reflects the columns I'm fetching
- it works since the `Record` object is "dict-able"

Now, with pydantic v2, it doesn't automatically try to parse "dict-able" objects, it seems to expect necessarily a dict, see sample code.

Could you explain if this is the intended behavior and if can be configurable somehow, to avoid refactoring my code?
Thank you

### Example Code

```Python
from pydantic import BaseModel, parse_obj_as


class MyModel(BaseModel):
    field: int


db_result = connection.fetch("...")  # list of Record

parse_obj_as(list[MyModel], db_result)
# Error: Input should be a valid dictionary or instance of MyModel [type=model_type, input_value=<Record field=123>}, 'description': ''}>, input_type=Record]

TypeAdapter(list[MyModel]).validate_python(db_result)  # Same error

parse_obj_as(list[MyModel], (dict(r) for r in db_result))  # This works
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=false
                 install path: /Users/a464122/Dev/PythonProjects/dam-behavior-core/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.4.1-x86_64-i386-64bit
             related packages: mypy-1.10.0 typing_extensions-4.11.0 fastapi-0.111.0
                       commit: unknown
```

**Comment by syniex** [comment]
I initiated this discussion 10 months ago:  https://github.com/pydantic/pydantic/discussions/6917.

Here's an interim solution:

```python
from typing import Any

from asyncpg import Record
from pydantic import BaseModel, model_validator

class MyModel(BaseModel):
    field: int
    
    @model_validator(mode='before')
    def _database_entry(cls, v: Any) -> Any:
        if isinstance(v, Record):
            return dict(v)
        return v
```
This code snippet offers a temporary workaround.

**Comment by samuelcolvin** [comment]
Hi, so sorry no one ever got back to this. The problem is that for some reason `Record` is not an instance of mapping:

```python
In [4]: import asyncpg

In [5]: conn = await asyncpg.connect(user='postgres', password='postgres')

In [6]: rows = await conn.fetch('select 1 as foo')

In [7]: rows
Out[7]: [<Record foo=1>]

In [8]: rows[0]
Out[8]: <Record foo=1>

In [9]: from typing import Mapping

In [10]: isinstance(rows[0], Mapping)
Out[10]: False
```

---

We check that something is an instance of mapping (logic [here](https://github.com/pydantic/pydantic-core/blob/e1fc99dd3207157aad77defc20ab6873fd268b5b/src/input/input_python.rs#L378)) before trying to validate it as if it's a dict/mapping.

I think that's generally the correct thing to do, but I see 3 ways forward in this specific case:
1. (ideally) get the asyncpg guys to make `Record` pass the `Mapping` isinstance check, I'll create an issue
2. use your approach above of a validator, you could wrap that into a custom type and thereby make it easier to reuse
3. (least attractive) a config flag that means we try to iterate over `.items` if it exists, regardless of the whether the thing is a `Mapping`

**Comment by samuelcolvin** [comment]
Turns out there's a much easier solution to this - just use `Mapping.register(asyncpg.Record)`:

```py
import asyncio
from collections.abc import Mapping

import asyncpg
from pydantic import BaseModel

# this tells python that asyncpg.Record is a subclass of Mapping,
# meaning the isinstance check within Pydantic will pass
Mapping.register(asyncpg.Record)


class MyModel(BaseModel):
    foo: int


async def main():
    conn = await asyncpg.connect(user='postgres', password='postgres')

    row = await conn.fetchrow('select 1 as foo')

    m = MyModel.model_validate(row)
    print(m)


if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by syniex** [comment]
That is really smart way, I didn't know pydantic check for mapping.

I would suggest to add this as an option to the documenation.

From reading the [logic](https://github.com/pydantic/pydantic-core/blob/e1fc99dd3207157aad77defc20ab6873fd268b5b/src/input/input_python.rs#L373) we can understand that from_attributes should be true.

Since the default value for `from_attributes` is `None`, it's not immediately clear what behavior that implies. However, based on the [documentation](https://github.com/pydantic/pydantic-core/blob/e1fc99dd3207157aad77defc20ab6873fd268b5b/python/pydantic_core/_pydantic_core.pyi#L103C70-L103C71) it will default to the value from `pydantic_core.core_schema.CoreConfig`.

I tried to search for the specific code responsible for defaulting `from_attributes=None` to `True` and could not find it.

**Comment by samuelcolvin** [comment]
PR welcome to improve documentation, you might specifically reference `asyncpg.Record` as it's a widely used type type which is usable as a Mapping, but doesn't pass the isinstance check out-of-the-box.

---

`from_attributes` won't help you with `asyncpg.Record`, since you can't access columns via attributes, e.g. `record.foo` will raise an `AttributeError`.

You can pass `from_attributes` when calling `model_validate`:

https://github.com/pydantic/pydantic/blob/7061f36bc721ef4f173ef8f2e098f25e1eaea705/pydantic/main.py#L529-L536
