### ISSUE TITLE
Type of validation context

### ISSUE THREAD

**Issue by OhioDschungel6** [pydantic/pydantic#9411]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using BaseModel.model_validate_json() or BaseModel.model_validate() the optional parameter "context" is typed to be a dict[str, Any].
This context is made available to validators via the ValidationInfo object.
The type of the info.context object is "Any | None" instead of "dict[str,Any] | None".

### Example Code

```Python
from typing import Any

from pydantic import BaseModel, model_validator
from pydantic_core.core_schema import ValidationInfo


class Model(BaseModel):
    @model_validator(mode="after")
    def validator(self, info: ValidationInfo) -> Any:
        info.context  # this returns a object of type "Any | None"


Model.model_validate_json("{}", context={})  # type of context has to be "dict[str, Any] | None"
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
               python version: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: mypy-1.10.0 typing_extensions-4.11.0
```

**Comment by sydney-runkle** [comment]
@OhioDschungel6,

Indeed, looks like our type hints could be improved. Would you be interested in opening a PR to fix this issue? Thanks for bringing it to our attention!

**Comment by mjog** [comment]
Can we keep `ValidationInfo`'s type annotations for `context` instead of `Model.model_validate[_json]` please? I.e. change the latter to `Any | None` rather than the former to a dict?

The change to `Model.model_validate[_json]` must have been pretty recent - I have code written as far back as Sep 2023 that passes in objects (not dicts) to validation code and a system of strongly typed context objects. It would be a massive pita to convert them to dicts and I'd lose some nice static type safety.

**Comment by OhioDschungel6** [comment]
@sydney-runkle I have fixed the type hints in [9508](https://github.com/pydantic/pydantic/pull/9508)
I agree with @mjog that Any is the correct type.
