### ISSUE TITLE
Mypy doesn't understand the signature of `__init__` of a `RootModel`

### ISSUE THREAD

**Issue by kikones34** [pydantic/pydantic#9662]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When trying to initialize a `RootModel`, mypy doesn't understand the signature of `__init__`. It believes that only `root` can be passed as an argument. However, pydantic supports passing the arguments of the inner models to the root model to initialize it.

The example code runs and has no validation errors at runtime, however mypy outputs the following errors:
```
root_model_test.py:16: error: Unexpected keyword argument "type" for "ClassAny"  [call-arg]
root_model_test.py:16: error: Unexpected keyword argument "a_stuff" for "ClassAny"  [call-arg]
Found 2 errors in 1 file (checked 1 source file)
```

I'm not sure how viable it is to make mypy understand the correct signature given the discriminator. If that's too hard, perhaps some compromise solution can be reached? Right now, typing has to be completely disabled with a type: ignore, even though there is no real typing problem.

Note: I am using the pydantic mypy plugin.

### Example Code

```Python
from pydantic import BaseModel, RootModel, Field
from typing import Literal

class ClassA(BaseModel):
    type: Literal["a"]
    a_stuff: str
    

class ClassB(BaseModel):
    type: Literal["b"]
    b_stuff: str

class ClassAny(RootModel):
    root: ClassA | ClassB = Field(discriminator="type")

c = ClassAny(
    type="a",
    a_stuff="hello",
)
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.7.4
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
                 install path: /home/k34/.local/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, Apr 27 2024, 19:00:21) [GCC 11.4.0]
                     platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.12.2 mypy-1.10.0
                       commit: unknown
```

**Comment by dmontagu** [comment]
So, because the approach you've used here is not compatible with `@dataclass_transform`, I wouldn't expect it to ever be supported by IDEs, pyright, or other non-mypy type-checkers. Between that, and the fact that I think it would be quite difficult to implement (though may be feasible by generating `__init__` overloads in the mypy plugin, I'm not sure how to do that but I'm guessing the APIs exist...), I'm not especially keen to implement or maintain it.

I would review a PR if someone else cares enough to implement this in our mypy plugin, but my recommendation would probably be to instead just use the `root` keyword argument, which _will_ work with all "standard" type-checkers that support `@dataclass_transform`. More explicitly, I would recommend: `c = ClassAny(root=ClassA(type="a", a_stuff="hello"))` in python code, even though the shortened form is supported at runtime.

**Comment by sydney-runkle** [comment]
Going to close this as not planned for now. Thanks @dmontagu for advising on this front.
