### ISSUE TITLE
Allow subclassing of `ValidationError`

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#9686]
Probably belongs in `pydantic-core`, but keeping this here for tracking purposes.

This would allow support for more custom errors, ex: changing the error `loc` as requested in https://github.com/pydantic/pydantic/issues/8092.

**Comment by Youssefares** [comment]
I'm going to look into this, feel free to assign to me, very keen to see this feature ✨

**Comment by sydney-runkle** [comment]
Great! I think the implementation will largely be in `pydantic-core`.

**Comment by Youssefares** [comment]
Still looking at this.. Not sure what to do with `.from_exception_data` yet.

I maybe wrong but just looking at python for now (pyo3 asside) and factories. There's a way to do this:

```
class Super():
    def __init__(self, msg):
        self.msg = msg

    @classmethod
    def factory(cls, msg) -> Self:
        return cls(msg)

class Sub(Super):
    pass

def test_sub():
    assert isinstance(Sub.factory(msg='la'), Sub)

# success
```

so long as factory is a class method, I don't think there's an equivalent with a static method which it is at the moment https://github.com/pydantic/pydantic-core/blob/main/python/pydantic_core/_pydantic_core.pyi#L746-L765.

Now, I think that's a non breaking change.. the problem is: that's not so easy to implement with pyo3, as far as I can see, there's no easy way to downcast to a PyType, especially with no constructor defined for the parent `ValidationError`.

Would appreciate some guidance if you've encountered something like this before. Neither a rust nor a pyo3 guru here.

**Comment by sydney-runkle** [comment]
> Now, I think that's a non breaking change

Nice find - I think I agree with you here!

> the problem is: that's not so easy to implement with pyo3, as far as I can see, there's no easy way to downcast to a PyType, especially with no constructor defined for the parent ValidationError.

Huh, interesting question. Most likely for @davidhewitt or @BoxyUwU. What do you folks think here?

**Comment by davidhewitt** [comment]
If I understand correctly, I think you want the rust implementation of `from_exception_data` to have this signature:

```rust
    #[classmethod]
    #[pyo3(signature = (title, line_errors, input_type="python", hide_input=false))]
    fn from_exception_data(
        cls: Bound<'_, PyType>,
        py: Python,
        title: PyObject,
        line_errors: Bound<'_, PyList>,
        input_type: &str,
        hide_input: bool,
    ) -> PyResult<Py<Self>> {
```

**Comment by sydney-runkle** [comment]
Hey @Youssefares,

Thanks for your help here! @davidhewitt ping - hopefully we can move this associated PR forward for v2.10!

**Comment by sydney-runkle** [comment]
Closed by https://github.com/pydantic/pydantic-core/pull/1413, but we need to document this in `pydantic` before the v2.10 release. Will do soon!
