### ISSUE TITLE
Add full support for PEP 695 like syntax

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#9782]
We currently have a variety of cases that fail (or just don't actually work) with syntax specified in https://peps.python.org/pep-0695/

Let's fix this for v2.11!

**Comment by sydney-runkle** [comment]
https://github.com/pydantic/pydantic/issues/8984

**Comment by changhc** [comment]
Hi @sydney-runkle, I would like to work on this issue. I'll start from the cases mentioned in the referenced issue.

**Comment by sydney-runkle** [comment]
Going to remove from our v2.10 milestone - though we're making good progress here, this doesn't fully fall within the v2.10 scope.

**Comment by Viicos** [comment]
While investigating https://github.com/pydantic/pydantic/issues/11031, I noticed that we _accidentally_ support PEP 695 for Pydantic models, but we should probably implement it in a proper way as we are currently relying on an implementation detail.

PEP 695 introduces a new annotation scope, and our parent namespace logic (which in theory should only be enabled if the model is defined in an inner scope -- e.g. a function) just so happens to fetch data from this scope (see [the documentation](https://docs.python.org/3/reference/compound_stmts.html#generic-classes) about new style generics). In `parent_frame_namespace`, we have the following check:

https://github.com/pydantic/pydantic/blob/d5f4bde014f12e0b2d03d46d77925d808053ff16/pydantic/_internal/_typing_extra.py#L445-L449

which ends up being `False` in this case:

```python
# A top level Pydantic model
class Model[T](BaseModel):
    pass
```

because `frame.f_code.co_name` is `'<generic parameters of Model>'`. It contains the following:

```python
{'T': T, '.generic_base': typing.Generic[T], '.type_params': (T,)}
```

Instead, we should find a proper way to support this, so that it also works with dataclasses, typed dictionaries, etc.
