### ISSUE TITLE
Incompatible return value type on validate_call decorated functions with validate_return=True

### ISSUE THREAD

**Issue by gsakkis** [pydantic/pydantic#9986]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Follow up to https://github.com/pydantic/pydantic/issues/9100 for `validate_return=True`.

### Example Code

```Python
from pydantic import validate_call

@validate_call(validate_return=True)
def f(v: str) -> int:
    return v


assert f("2") == 2
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
pydantic-core version: 2.20.1
pydantic-core build: profile=release pgo=true
python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:34:54) [Clang 16.0.6 ]
platform: macOS-14.1-arm64-arm-64bit
related packages: typing_extensions-4.12.1 pydantic-settings-2.3.4 mypy-1.11.0
```

**Comment by sydney-runkle** [comment]
@gsakkis,

What's the issue that you're reporting, exactly? `"2"` is being converted to `2` here, as strict mode is not being used.

If you use `strict=True` in the config, then you get the result that I think you're expecting:

```py
from pydantic import validate_call, ConfigDict

@validate_call(validate_return=True, config=ConfigDict(strict=True))
def f(v: str) -> int:
    return v


assert f("2") == 2
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for f
  Input should be a valid integer [type=int_type, input_value='2', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/int_type
"""
```

**Comment by gsakkis** [comment]
@sydney-runkle it's a typing error just like in the original issue, not a runtime error:
```
error: Incompatible return value type (got "str", expected "int")  [return-value]
```

**Comment by dmontagu** [comment]
So, the reason we are getting an error is because the type-checker is working inside-out here. As part of type checking the following code:
```python
from pydantic import validate_call

@validate_call(validate_return=True)
def f(v: str) -> int:
    return v


assert f("2") == 2
```
It's going to type-check:
```python
def f(v: str) -> int:
    return v
```
This is clearly a type error. The decorator on the outside could theoretically change the return type of the decorated function, but ultimately the decorated function _itself_ would still have a type error — given the input `v` is of type `str`, this function definitely returns a `str`, not an `int`. The _decorated_ version of this function returns an int, but not the inner/pre-decorated function.

Even if it were possible to suppress the type-checker errors for this with a plugin, I am very hesitant to open that can of worms; every time we do something outside the intended behavior of the type system it becomes a significant maintenance burden as new versions of mypy are released etc., and any code relying on it will still show type errors in pyright/pycharm/vscode/etc. (everything besides mypy), and for that reason I don't really like adding additional functionality to the plugin unless absolutely necessary.

The main problem I see with the `validate_call` api today is that there's no way to override the return type when you are purposely returning a value that doesn't match the annotated return type. If we add another (overload) signature with an argument for `validate_return_as` or similar then we should be able to get the type system to understand that that will be the return value of the decorated function. I would propose that as the way forward if we want to better support this case, as it is the most type-checking-correct thing to do, and should work with all type-checkers. I'd be happy to review a PR introducing this API, or could potentially get to it myself at some point; either way, I don't think it should be very hard to implement.

However, I'll note that if this were my code, I would probably just use `return typing.cast(int, v)  # validate_call will convert the returned result` or even a `# type: ignore` and not worry about it too much.

**Comment by dmontagu** [comment]
I'll note that if anyone wants to take a stab at implementing this, here is a reasonable starting point:

```diff
diff --git a/pydantic/_internal/_validate_call.py b/pydantic/_internal/_validate_call.py
index 3fae2d10e..a21bf4171 100644
--- a/pydantic/_internal/_validate_call.py
+++ b/pydantic/_internal/_validate_call.py
@@ -5,6 +5,7 @@ from functools import partial
 from typing import Any, Awaitable, Callable
 
 import pydantic_core
+from pydantic_core._pydantic_core import PydanticUndefined
 
 from ..config import ConfigDict
 from ..plugin._schema_validator import create_schema_validator
@@ -29,6 +30,7 @@ class ValidateCallWrapper:
         config: ConfigDict | None,
         validate_return: bool,
         namespace: dict[str, Any] | None,
+        validate_return_as: Any = PydanticUndefined,
     ):
         if isinstance(function, partial):
             func = function.func
@@ -67,9 +69,12 @@ class ValidateCallWrapper:
             config_wrapper.plugin_settings,
         )
 
-        if validate_return:
+        if validate_return or validate_return_as != PydanticUndefined:
             signature = inspect.signature(function)
-            return_type = signature.return_annotation if signature.return_annotation is not signature.empty else Any
+            if validate_return_as != PydanticUndefined:
+                return_type = validate_return_as
+            else:
+                return_type = signature.return_annotation if signature.return_annotation is not signature.empty else Any
             gen_schema = _generate_schema.GenerateSchema(config_wrapper, namespace)
             schema = gen_schema.clean_schema(gen_schema.generate_schema(return_type))
             validator = create_schema_validator(
diff --git a/pydantic/validate_call_decorator.py b/pydantic/validate_call_decorator.py
index 115169451..6b58969b5 100644
--- a/pydantic/validate_call_decorator.py
+++ b/pydantic/validate_call_decorator.py
@@ -3,7 +3,9 @@
 from __future__ import annotations as _annotations
 
 import functools
-from typing import TYPE_CHECKING, Any, Callable, TypeVar, overload
+from typing import TYPE_CHECKING, Any, Callable, ParamSpec, TypeVar, overload
+
+from pydantic_core._pydantic_core import PydanticUndefined
 
 from ._internal import _typing_extra, _validate_call
 
@@ -13,6 +15,14 @@ if TYPE_CHECKING:
     from .config import ConfigDict
 
     AnyCallableT = TypeVar('AnyCallableT', bound=Callable[..., Any])
+    P = ParamSpec('P')
+    T = TypeVar('T')
+
+
+@overload
+def validate_call(
+    *, config: ConfigDict | None = None, validate_return_as: T
+) -> Callable[[Callable[P, Any]], Callable[P, T]]: ...
 
 
 @overload
@@ -31,6 +41,7 @@ def validate_call(
     *,
     config: ConfigDict | None = None,
     validate_return: bool = False,
+    validate_return_as: Any = PydanticUndefined,
 ) -> AnyCallableT | Callable[[AnyCallableT], AnyCallableT]:
     """Usage docs: https://docs.pydantic.dev/2.9/concepts/validation_decorator/
 
@@ -41,7 +52,8 @@ def validate_call(
     Args:
         func: The function to be decorated.
         config: The configuration dictionary.
-        validate_return: Whether to validate the return value.
+        validate_return: Whether to validate the annotated return value of `func`.
+        validate_return_as: An explicitly specified type to use while validating the returned value.
 
     Returns:
         The decorated function.
@@ -53,7 +65,9 @@ def validate_call(
             name = type(function).__name__
             raise TypeError(f'The `@{name}` decorator should be applied after `@validate_call` (put `@{name}` on top)')
 
-        validate_call_wrapper = _validate_call.ValidateCallWrapper(function, config, validate_return, local_ns)
+        validate_call_wrapper = _validate_call.ValidateCallWrapper(
+            function, config, validate_return, local_ns, validate_return_as
+        )
 
         @functools.wraps(function)
         def wrapper_function(*args, **kwargs):
```

You'd need to add some tests and maybe clean up some of the API changes, but I think it would get the type checking you want.

**Comment by gsakkis** [comment]
Thanks a lot @dmontagu, I might take a stab at it but I agree it's probably not worth the effort & maintenance burden.

>So, the reason we are getting an error is because the type-checker is working inside-out here.

Out of curiosity, doesn't the same happen with the plain `@validate_call` without `validate_return=True`? Wondering what's the reason of the asymmetry between (input) parameter types and (output) return type.
